// runtime/loficity/words.h — GENERATED from Lofi Cities' title word lists (CITY_WORDS / NOUNS / ADJS / TIMES /
// TEMPLATES), accents folded to ASCII one-for-one so the 32-character title check counts the same.
static const char *LC_NOUNS[] = { "lullaby", "daydream", "reverie", "echoes", "letters", "polaroids", "headlights", "streetlights", "reflections", "window seat", "slow dance", "night shift", "coffee", "cassettes", "raindrops", "soft focus", "old photographs", "paper moons", "radio static", "afterglow", "small talk", "notebooks", "warm static", "long walks", "missed calls", "pocket change", "quiet hours", "love letters", "city lights", "sleepwalking", "goodnights", "thoughts", "memories", "footsteps", "secrets", "window light", "tape hiss", "slow motion", "homework", "blue notes", "moonlight", "daydreams", "postcards", "lamplight", "rain songs", "night walks", "loose ends", "mixtapes", "late buses", "open windows", "paper boats", "half-light", "sketches", "tangerines", "umbrellas", "wishes", "waltz", "nocturne", "cigarettes", "fireflies" };
static const char *LC_ADJS[] = { "sleepy", "velvet", "hazy", "quiet", "dusty", "faded", "soft", "slow", "warm", "blue", "lonely", "sleepless", "gentle", "grainy", "amber", "misty", "drowsy", "rainy", "humming", "flickering", "distant", "mellow", "tired", "golden", "pale", "silver", "wistful", "lazy", "secret", "little", "late", "empty", "hushed", "lost", "tender", "dreamy", "foggy", "mossy", "cozy", "moonlit", "neon", "rainy-day", "nostalgic", "unhurried", "pastel", "second-hand", "far-off", "dim", "lo-fi" };
static const char *LC_TIMES[] = { "3am", "2am", "midnight", "after hours", "closing time", "the blue hour", "dawn", "before sunrise", "late night", "sunday night", "4am", "the small hours", "half past one", "nightfall", "last call" };
static const struct { double w; const char *t; } LC_TPL[] = {
    { 10, "{a} {n} in {p}" },
    { 6, "{a} {c} in {p}" },
    { 4, "{a} {n}, {p}" },
    { 3, "{n} over {p}" },
    { 2, "last {c}, {p}" },
    { 2, "{a} {n}" },
    { 2, "{a} {c}" },
    { 1.5, "{p} at {t}" },
    { 1, "{t}, {p}" },
    { 1.5, "{c} at {t}" },
    { 2, "{n} in {p}" },
    { 1.5, "{p} {n}" },
    { 2, "{c} & {n}" },
    { 1.5, "the {a} {c}" },
    { 1, "{c} in {R}" },
    { 0.8, "{w} over {p}" },
    { 0.8, "{w} on {p}" },
    { 0.4, "{p} after dark" },
    { 0.2, "walking {p}" },
    { 0.2, "somewhere in {p}" },
    { 1.5, "{P}" },
    { 1.2, "{c}, {t}" },
    { 0.6, "{Q}" },
    { 1.5, "{n} from {p}" },
    { 2, "{P} at {t}" },
};
#define LC_NCITY 16
typedef struct { const char *id, *name; const char *p[16]; int np; const char *c[24]; int nc; const char *w[5]; int nw; } LcCity;
static const LcCity LC_CITY[LC_NCITY] = {
    { "paris", "Paris",
      { "montmartre", "the seine", "saint-germain", "le marais", "pigalle", "belleville", "the left bank", "pont neuf", "the quais", "canal saint-martin", "ile saint-louis", "the latin quarter", "rue mouffetard", "batignolles", "bastille", "the tuileries" }, 16,
      { "cafe", "accordion", "balcony", "zinc bar", "bookstall", "carousel", "pigeons", "lamplight", "chanson", "bistro", "street piano", "postcard", "croissant", "rooftops", "metro", "boat lights", "espresso", "cobblestones", "shutters", "violin" }, 20,
      { "rain", "drizzle", "puddles", "wet stone", "grey skies" }, 5 },
    { "tokyo", "Tokyo",
      { "shinjuku", "shibuya", "koenji", "shimokitazawa", "golden gai", "akihabara", "nakameguro", "the yamanote", "ginza", "asakusa", "harajuku", "ebisu", "the sumida", "ikebukuro", "kichijoji", "yanaka" }, 16,
      { "vending machine", "konbini", "neon", "umbrellas", "ramen stall", "capsule hotel", "izakaya", "cassette", "lanterns", "crosswalk", "arcade", "noodle bar", "last train", "paper cranes", "taxi lights", "rooftop", "canned coffee", "train window", "shrine bell", "city pop" }, 20,
      { "neon rain", "rain", "drizzle", "wet asphalt", "puddles" }, 5 },
    { "new-york", "New York",
      { "brooklyn", "the bowery", "harlem", "soho", "the village", "queens", "coney island", "chinatown", "the high line", "tribeca", "williamsburg", "astoria", "the east river", "grand central", "little italy", "the lower east side" }, 16,
      { "fire escape", "yellow cab", "bodega", "subway car", "steam vents", "diner", "jazz club", "water tower", "bagels", "streetlamp", "laundromat", "walk-up", "hot dog cart", "rooftop", "late train", "radiator", "crosswalk", "neon sign", "saxophone", "skyline" }, 20,
      { "rain", "steam", "sleet", "city rain", "puddles" }, 5 },
    { "london", "London",
      { "soho", "camden", "the embankment", "brixton", "shoreditch", "hackney", "the thames", "notting hill", "peckham", "covent garden", "king's cross", "the southbank", "primrose hill", "whitechapel", "bermondsey", "waterloo" }, 16,
      { "night bus", "pub", "phone box", "tube", "chip shop", "umbrella", "bookshop", "double-decker", "last orders", "record shop", "lamppost", "canal boat", "big clock", "tea", "cab lights", "bridges", "terraces", "pint glass", "underpass", "foxes" }, 20,
      { "fog", "drizzle", "rain", "grey skies", "mist" }, 5 },
    { "rio", "Rio de Janeiro",
      { "copacabana", "ipanema", "lapa", "santa teresa", "leblon", "botafogo", "sugarloaf", "the lagoon", "urca", "tijuca", "flamengo", "arpoador", "corcovado", "gavea", "the boardwalk", "the favela" }, 16,
      { "samba", "bossa nova", "cable car", "coconuts", "surfboard", "caipirinha", "hill lights", "mosaic", "tram", "hammock", "beach bar", "cavaquinho", "palms", "kiosk", "sandals", "guitar", "lighthouse", "kites", "mango", "swimsuits" }, 20,
      { "warm rain", "sea breeze", "waves", "the tide", "salt air" }, 5 },
    { "istanbul", "Istanbul",
      { "the bosphorus", "galata", "karakoy", "kadikoy", "beyoglu", "balat", "uskudar", "eminonu", "the golden horn", "cihangir", "moda", "ortakoy", "sultanahmet", "the bazaar", "the old city", "the ferry pier" }, 16,
      { "ferry", "simit", "tea glass", "minaret", "lanterns", "street cats", "hammam", "carpets", "tram", "gulls", "backgammon", "cay", "spice stall", "rooftop", "oud", "fishing lines", "bridge lights", "mosaic", "coffee cups", "call to prayer" }, 20,
      { "sea breeze", "rain", "drizzle", "harbour mist", "the current" }, 5 },
    { "hong-kong", "Hong Kong",
      { "victoria harbour", "kowloon", "tsim sha tsui", "mong kok", "central", "wan chai", "sheung wan", "the peak", "yau ma tei", "sham shui po", "causeway bay", "lan kwai fong", "temple street", "the ferry pier", "north point", "jordan" }, 16,
      { "harbour ferry", "neon signs", "junk boat", "dim sum", "milk tea", "egg tarts", "the peak tram", "mahjong", "bamboo poles", "laundry lines", "rooftops", "dai pai dong", "minibus", "ding ding tram", "light show", "harbour lights", "wonton noodles", "pineapple buns", "night market", "water tanks" }, 20,
      { "drizzle", "harbour haze", "warm rain", "humid night", "sea mist" }, 5 },
    { "sydney", "Sydney",
      { "circular quay", "the rocks", "kirribilli", "farm cove", "bennelong point", "milsons point", "barangaroo", "darling harbour", "woolloomooloo", "mrs macquarie's chair", "the botanic garden", "manly", "the heads", "surry hills", "bondi", "luna park" }, 16,
      { "jacaranda", "ferry", "harbour bridge", "opera house", "sails", "water taxi", "flying foxes", "possum", "agapanthus", "bridge climb", "train", "wharf", "park bench", "lamp post", "sandstone", "cockatoo", "lorikeet", "fig tree", "flat white", "channel marker" }, 20,
      { "heat lightning", "summer storm", "humid air", "harbour breeze", "spring rain" }, 5 },
    { "san-francisco", "San Francisco",
      { "russian hill", "hyde street", "lombard street", "north beach", "the presidio", "fort point", "aquatic park", "the marina", "telegraph hill", "nob hill", "crissy field", "sausalito", "the embarcadero", "ocean beach", "the mission", "chinatown" }, 16,
      { "cable car", "foghorn", "painted ladies", "bay window", "sea lions", "lighthouse", "container ship", "sailboat", "sourdough", "the bell", "orange towers", "steep streets", "tall ship", "turret", "streetlamp", "the pier", "headlands", "night ferry", "coffee", "rooftops" }, 20,
      { "fog", "drizzle", "marine layer", "sea breeze", "mist" }, 5 },
    { "hamburg", "Hamburg",
      { "hafencity", "the speicherstadt", "st. pauli", "altona", "the elbe", "the reeperbahn", "ottensen", "the schanze", "the alster", "blankenese", "the fish market", "wilhelmsburg", "eppendorf", "kehrwieder", "the michel", "finkenwerder" }, 16,
      { "container ship", "gantry crane", "harbour ferry", "barkasse", "foghorn", "gulls", "red brick", "copper roofs", "iron bridge", "bollard", "lifebuoy", "oilskin", "lantern", "harbour seal", "glass crown", "canal", "warehouse", "fish roll", "ship's bell", "deck lights" }, 20,
      { "rain", "gusts", "squalls", "storm", "grey skies" }, 5 },
    { "amsterdam", "Amsterdam",
      { "the jordaan", "prinsengracht", "keizersgracht", "herengracht", "the westerkerk", "the nine streets", "de pijp", "bloemgracht", "brouwersgracht", "the amstel", "oud-west", "vondelpark", "haarlemmerdijk", "the ij", "noord", "leidseplein" }, 16,
      { "houseboat", "canal bridge", "bridge lights", "brown cafe", "gables", "hoisting beam", "carillon", "bicycle bell", "cargo bike", "elm seeds", "grey heron", "canal lamps", "window plants", "moored boats", "steep stairs", "bollards", "lantern boat", "coots", "roof garden", "stroopwafel" }, 20,
      { "clear skies", "spring night", "canal mist", "mild breeze", "moonlight" }, 5 },
    { "dubai", "Dubai",
      { "downtown", "the burj lake", "the fountain boardwalk", "sheikh zayed road", "al fahidi", "the creek", "deira", "bur dubai", "jumeirah", "business bay", "the souk", "karama", "satwa", "la mer", "the marina", "al seef" }, 16,
      { "fountain jets", "silver spire", "aviation lights", "led facade", "abra", "metro train", "wind towers", "arcade lamps", "brass lanterns", "dallah", "cardamom coffee", "finjan cups", "dates", "karak tea", "sadu cushions", "shisha", "oud smoke", "date palms", "fairy lights", "street cat", "sand dunes", "camel caravan", "desert campfire" }, 23,
      { "desert breeze", "winter night", "fountain mist", "fine sand", "crescent moon" }, 5 },
    { "madrid", "Madrid",
      { "gran via", "calle de alcala", "the metropolis", "plaza de callao", "red de san luis", "puerta del sol", "chueca", "malasana", "la latina", "lavapies", "plaza de espana", "cibeles", "barrio de las letras", "huertas", "plaza mayor", "el retiro" }, 16,
      { "winged victory", "gold dome", "rooftop neon", "churros", "chocolate", "tinto de verano", "geraniums", "wrought-iron balcony", "persiana", "folding fan", "night bus", "white taxi", "street sweeper", "terrace cafe", "bell tower", "farolas", "cinema sign", "black cat", "poplar fluff", "string lights" }, 20,
      { "warm night", "dry summer air", "poplar fluff", "honey moon", "city glow" }, 5 },
    { "rome", "Rome",
      { "monti", "via cavour", "via dei serpenti", "via panisperna", "piazza della madonna dei monti", "via degli annibaldi", "the colle oppio", "the celio", "the palatine", "the forum", "trastevere", "campo de' fiori", "the pantheon", "piazza navona", "testaccio", "the aventine" }, 16,
      { "colosseum", "arches", "umbrella pines", "bell tower", "sampietrini", "nasone", "trattoria", "checked tablecloths", "candlelight", "string lights", "green shutters", "laundry line", "bougainvillea", "corner shrine", "scooter", "gelato", "street cats", "gulls", "scaffolding", "wine bar" }, 20,
      { "shooting stars", "warm night", "august heat", "perseids", "summer breeze" }, 5 },
    { "prague", "Prague",
      { "mala strana", "the old town", "kampa", "petrin hill", "hradcany", "the vltava", "charles bridge", "josefov", "vinohrady", "zizkov", "letna", "smichov", "nove mesto", "wenceslas square", "old town square", "vysehrad" }, 16,
      { "castle lights", "cathedral spires", "bridge statues", "old lamps", "weir foam", "swans", "paddle steamer", "red tram", "tram bell", "linden blossoms", "cobblestones", "copper domes", "trdelnik", "bridge towers", "metronome", "lattice tower", "river terrace", "embankment bench", "mosaic pavement", "tiled roofs" }, 20,
      { "june night", "linden air", "river breeze", "clear skies", "moonlight" }, 5 },
    { "munich", "Munich",
      { "marienplatz", "the rathaus", "the frauenkirche", "the viktualienmarkt", "schwabing", "maxvorstadt", "haidhausen", "the glockenbach", "the englischer garten", "the isar", "odeonsplatz", "sendlinger tor", "kaufingerstrasse", "the tal", "giesing", "lehel" }, 16,
      { "christmas market", "glockenspiel", "green domes", "mulled wine", "gingerbread hearts", "roasted chestnuts", "pretzels", "wooden stalls", "string lights", "christmas tree", "golden madonna", "lantern", "snowy roofs", "felt hat", "bobble hat", "dachshund", "carillon", "paper star", "candles", "town hall tower" }, 20,
      { "snow", "snowfall", "december night", "frost", "soft flurries" }, 5 },
};
