/* acidcandy_state.h — GENERATED by tools/ctx-gen.js. Do not edit by hand.
 *
 * The per-instance engine context (docs/design/engine-context.md). An AUv3 puts every plug-in
 * instance in ONE process, so state that lives in file-scope statics is shared by every
 * instance — which is why two DAW tracks fight over one rack. These members used to be those
 * statics; the macro block at the bottom means the engine code reads exactly as it did before.
 *
 * The default instance below is a `static` with DESIGNATED INITIALISERS, so every value is
 * still set at compile time exactly as it was, and the rest is still zeroed static storage.
 * That is what makes this a pure move with no init-order risk: nothing can read a member
 * before it is set, because the linker sets it. A real per-instance context is then created
 * by copying this template, which is exact by construction.
 */
#ifndef DE_ACIDCANDY_STATE_H
#define DE_ACIDCANDY_STATE_H

/* self-contained: the members use these, and depending on where this header lands in
 * sound.h they may not have been pulled in yet. */
#include <stdint.h>
#include <stdbool.h>
#include <stdatomic.h>

/* MOVED here from cart.c: the sizes and constants the members below are written in.
 * They have to precede the struct, and moving a #define earlier is always safe because a
 * macro body is only text until it is expanded. */
#define NSLOT 6   // hoisted with the two SONG panels' state below (a macro body is only text until expanded)
#define STEPS 16
enum { M_303A, M_303B, M_808, M_909, M_MST, M_N };
enum { MK_303, MK_DRUM, MK_MST };
/* ⚠ NO `name` HERE. A machine's LABEL is compile-time data, not state, and this struct lives inside
 * the SAVED CartState — so a `const char *` here was restored from ANOTHER PROCESS's address space.
 * It cost the nav labels on every reopened project (and was a wild pointer handed to print()).
 * The labels live in MAC_NAME[] below; only `mute` is genuinely per-project state. */
typedef struct { int kind; int col, lo; int mute; } Machine;
static const char *const MAC_NAME[M_N] = { "303", "303", "808", "909", "MST" };
enum { PS_SEQ, PS_FLAG, PS_FX, PS_GEN, PS_KEY, PS_PAT, PS_PERF };  // 303 LCD content: roll / flags / FX / generate / KEY (root·scale·octave) / PAT (A-D banks) / PERF (live play lenses)
enum { FL_NOTE, FL_ACC, FL_SLD, FL_TIE, FL_OCTU, FL_OCTD, FL_N };   // FL_NOTE = toggle the note itself (so you add notes WITHOUT leaving FLAG for SEQ). (LEN moved out — it's a per-LINE loop length, now a draggable handle at the end of the note-bars, not a per-step flag)
enum { LK_TUNE, LK_DEC, LK_CHAR, LK_VOL, LK_PAN, LK_N };    // continuous-lane params (doff[] index). VOL = per-step level (velocity); PAN = per-step stereo
enum { DD_ACC, DD_PROB, DD_STRK, DD_TUN, DD_DEC, DD_CHAR, DD_VOL, DD_PAN, DD_N };
enum { DS_VCE, DS_KIT, DS_FLAG, DS_GEN, DS_MIX, DS_PAT, DS_PERF };     // drum LCD: VCE (tone+mix knobs, one panel) / kit / flags / generate / (DS_MIX retired — folded into VCE) / PAT (A-D banks) / PERF (ROLL·ACC)
#define NPAT 4
typedef struct { int b_on[STEPS], b_pit[STEPS], b_acc[STEPS], b_sld[STEPS], b_tie[STEPS], b_oct[STEPS], b_plen; } P303;
typedef struct { int grid[TR_NV][STEPS], b_acc[TR_NV][STEPS], prob[TR_NV][STEPS]; float off[LK_N][TR_NV][STEPS]; } P808;
typedef struct { int grid[TR9_NV][STEPS], b_acc[TR9_NV][STEPS], prob[TR9_NV][STEPS], strk[TR9_NV][STEPS]; float off[LK_N][TR9_NV][STEPS]; } P909;
enum { PL_HALF, PL_ACC, PL_OCT, PL_STAC, PL_GLIDE, PL_REV, PL_ROLL, PL_N };   // lens index (for pf_latch/pf_hold). Speed = just HALF (2X/8-12 dropped); accent cross-rhythms (AC3/AC4) dropped — didn't add much
enum { DPL_RP1, DPL_RP2, DPL_RP4, DPL_THIN, DPL_BUSY, DPL_ACC, DPL_N };
typedef struct {                 // the sound-defining half of an Acid — NOT its live handles/change-guards
    float p[ACID_NPARAM];
    int   wave, drvmode, sweep, base, classic, clean;
    float cut_top, drift, echo_send, rev_send;
} AcidSnap;
typedef struct {
    // sequences — every pattern bank of every machine + which bank each has selected
    P303 b_pat303[2][NPAT];
    P808 b_pat808[NPAT];
    P909 b_pat909[NPAT];
    int  b_curpat[M_N];
    // 303 sound (per line)
    AcidSnap b_ac[2];
    int  b_mroot[2], b_mscale[2], b_loct[2], b_kpage[2], b_plen[2];
    // drum sound (global, per voice)
    float b_dtune[TR_NV], b_ddecay[TR_NV], b_dcolor[TR_NV], b_dvol[TR_NV], b_dpan[TR_NV], b_dfine[TR_NV];
    float b_d9tune[TR9_NV], b_d9decay[TR9_NV], b_d9color[TR9_NV], b_d9vol[TR9_NV], b_d9pan[TR9_NV], b_d9fine[TR9_NV];
    float b_m9cut, b_m9res;
    int   mmute[M_N];                // per-MACHINE mute (the cartridge-LED mute); MST's entry is unused
    int   b_dmute[TR_NV], b_d9mute[TR9_NV];
    // master fx + transport
    float b_mglu, b_mflt, b_mfres, b_mfb, b_mpump, b_msend[4], b_fxverb[4], b_dist8, b_dist9, b_level[M_N];
    int   b_mdiv, b_mpcf[STEPS], b_mcrush[STEPS], b_mgate[STEPS];
    float g_bpm_s, bpm01_s, g_swing_s;
} SaveBlob;
typedef struct {
    unsigned      magic;
    int           cur;             // last active/loaded named slot (UI highlight); -1 = none
    int           autos_used;      // 1 = the rolling autosave holds real state (else boot keeps the generated default)
    unsigned char used[NSLOT];     // 1 = that named slot holds a saved song
    SaveBlob      autos;           // rolling autosave — resume-where-you-left-off, SEPARATE from the six deliberate slots
    SaveBlob      slot[NSLOT];     // the six song slots
} SaveBank;
typedef struct { int scr, arm, ml, mh, mn, rl, rh, rn; } DrumUI;

typedef struct {
    float aS[4];
    float aComp;
    float aBpm;
    float aEf;
    int aMode;
    int aEt;
    int aCrush;
    int aGate;
    float aFlm;
    float aFlf;
    float aPhm;
    float aPhf;
    float aSwpRate;
    int aFlon;
    int aPhon;
    float aVw;
    float aVq;
    float aVm;
    float aRv[4];
    float aD8;
    float aD9;
    float aLv[4];
    char bpm3_buf[4];
    int use_bars;
    unsigned tick;
    int note_erase;
    int sng_shf[NSLOT];
    int r2sng_shf[NSLOT];
    int sng_confirm;
    int r2sng_confirm;
    Machine mac[M_N];
    int face;
    int rack_view;
    int r2_focus;
    int r2_selmach;
    int r2_dpaint;
    int r2_octpen[2];
    int r2_303panel[2];
    int r2_drumpanel[2];
    int r2_mstpanel;
    int r2_mstlane;
    int r2_dark;
    Acid ac[2];
    int s_on[2][STEPS];
    int pit[2][STEPS];
    int acc[2][STEPS];
    int sld[2][STEPS];
    int s_sel[2];
    int mroot[2];
    int mscale[2];
    int loct[2];
    int drag_gx;
    int drag_gy;
    int drag_axis;
    int drag_paint;
    int drag_on0;
    int tie[2][STEPS];
    int oct[2][STEPS];
    int plen[2];
    int lpos[2];
    int pscreen[2];
    int kpage[2];
    int seq_grid;
    int keys_mode;
    int key_oct;
    int s_armed;
    int dscreen;
    int darmed;
    int dmut_latch;
    int dmut_hold;
    int dmut_now;
    int drec_latch;
    int drec_hold;
    int drec_now;
    int dmute[TR_NV];
    int d9mute[TR9_NV];
    int paint_val;
    int dgrid[TR_NV][STEPS];
    float dtune[TR_NV];
    float ddecay[TR_NV];
    float dcolor[TR_NV];
    float dvol[TR_NV];
    float dpan[TR_NV];
    float dpanlast[TR_NV];
    float dfine[TR_NV];
    float dtunefine[TR_NV];
    int dsel;
    float dtrig[TR_NV];
    int d9grid[TR9_NV][STEPS];
    float d9tune[TR9_NV];
    float d9decay[TR9_NV];
    float d9color[TR9_NV];
    float d9vol[TR9_NV];
    float d9pan[TR9_NV];
    float d9panlast[TR9_NV];
    float d9fine[TR9_NV];
    float d9tunefine[TR9_NV];
    int d9sel;
    float d9trig[TR9_NV];
    float m9cut;
    float m9res;
    int dacc[TR_NV][STEPS];
    int dprob[TR_NV][STEPS];
    int d9acc[TR9_NV][STEPS];
    int d9prob[TR9_NV][STEPS];
    int d9strk[TR9_NV][STEPS];
    float doff[LK_N][TR_NV][STEPS];
    float d9off[LK_N][TR9_NV][STEPS];
    float mglu;
    float mflt;
    float mfres;
    float mfb;
    float mpump;
    int mdiv;
    float msend[4];
    float fxverb[4];
    float dist8;
    float dist9;
    float level[M_N];
    int mpcf[STEPS];
    int mcrush[STEPS];
    int mgate[STEPS];
    int mstflow;
    float flmix;
    float flfb;
    float phmix;
    float phfb;
    int flon;
    int phon;
    int mswdiv;
    int fxpage;
    int fxdry_latch;
    int fxdry_hold;
    int vowon;
    float vowvow;
    float vowq;
    float vowmix;
    int vowspeak;
    float vowglide;
    float vowcur;
    float vowtgt;
    int vowstep;
    float vowdens;
    float vowgate;
    float vowgtgt;
    float vowgap;
    int vowfired;
    P303 pat303[2][NPAT];
    P808 pat808[NPAT];
    P909 pat909[NPAT];
    int curpat[M_N];
    int armpat[M_N];
    int playing;
    int s_step;
    int laststep;
    int laststep303[2];
    float mbop;
    float g_bpm;
    float bpm01;
    float g_phase;
    float g_last_t;
    float g_swing;
    int pf_latch[PL_N][2];
    int pf_hold[PL_N][2];
    int pf_half[2];
    int pf_acc[2];
    int pf_oct[2];
    int pf_stac[2];
    int pf_glide[2];
    int pf_rev[2];
    int pf_roll[2];
    int rollctr[2];
    int roll_pit[2];
    int roll_acc[2];
    int dpf_latch[DPL_N][2];
    int dpf_hold[DPL_N][2];
    int pf_rp1[2];
    int pf_rp2[2];
    int pf_rp4[2];
    int pf_thin[2];
    int pf_busy[2];
    int pf_dacc[2];
    int rpt_base[2];
    int rpt_n[2];
    int rpt_was[2];
    int g_drag_frame;
    int g_drag_y;
    /* nav_poison MOVED OUT of CartState (2026-08-14) — see AcidScratch below. It is an array of
     * WIDGET POINTERS, and CartState is a SAVED slice, so it would have been written into the host's
     * project file and restored into another process as six stale addresses. Found by
     * tools/lint-saved-state.js on its first run. */
    SaveBank g_bank;
    SaveBlob g_scratch;
    int save_cooldown;
    int mout_on;
    int mout_clk;
    int mo_held[2];
    int mo_clk_sent;
    int mo_was_playing;
    DrumUI drum_ui[2];
    int de_ctx_inited_;   // set once, when this instance copies the template below
    /* ⚠ APPEND ONLY, AND AT THE VERY END — everything above this line is in projects people have
     * already saved. A new field added HERE prefix-restores cleanly (older blobs are shorter, so it
     * keeps its template default); inserting one ABOVE would keep the struct the same size, pass the
     * engine's fingerprint, and land every value in the wrong field. tools/lint-saved-state.js holds
     * this line for you. See docs/design/engine-instance-seam.md → migration. */
    int bend_range;       // pitch-bend range in semitones (per project). 2 = the standard default.
} CartState;

/* the compile-time defaults — one line per static that carried a non-zero initialiser */
static CartState de_cart_default = {
    .bend_range = 5,           /* semitones — a PERFECT FOURTH at full deflection (the maker's call:
                              * 2 was too polite for acid). Per project, so it can be retuned. */
    .aS = { -1, -1, -1, -1 },
    .aComp = -1,
    .aBpm = -1,
    .aEf = -1,
    .aMode = -2,
    .aEt = -1,
    .aCrush = -1,
    .aGate = -1,
    .aFlm = -2,
    .aFlf = -2,
    .aPhm = -2,
    .aPhf = -2,
    .aSwpRate = -2,
    .aFlon = -1,
    .aPhon = -1,
    .aVw = -2,
    .aVq = -2,
    .aVm = -2,
    .aRv = { -1, -1, -1, -1 },
    .aD8 = -1,
    .aD9 = -1,
    .aLv = { -1, -1, -1, -1 },
    .use_bars = 1,
    .sng_confirm = -1,
    .r2sng_confirm = -1,
    .mac = { { MK_303,  CLR_PINK,      CLR_DARK_PURPLE, 1 }, { MK_303,  CLR_ORANGE,    CLR_DARK_ORANGE, 1 }, { MK_DRUM, CLR_TRUE_BLUE, CLR_DARK_BLUE,   0 }, { MK_DRUM, CLR_YELLOW,    CLR_DARK_ORANGE, 0 }, { MK_MST,  CLR_GREEN,     CLR_DARK_GREEN,  0 }, },
    .face = M_303A,
    .rack_view = -1,
    .r2_selmach = M_808,
    .r2_octpen = { 0, 0 },
    .r2_303panel = { 0, 0 },
    .r2_drumpanel = { 1, 1 },
    .r2_mstlane = -1,
    .s_sel = { 0, 0 },
    .mroot = { 0, 0 },
    .mscale = { 0, 0 },
    .loct = { 0, 0 },
    .plen = { STEPS, STEPS },
    .lpos = { 0, 0 },
    .pscreen = { PS_SEQ, PS_SEQ },
    .s_armed = FL_NOTE,
    .dscreen = DS_VCE,
    .darmed = DD_ACC,
    .dsel = TR_BD,
    .d9sel = TR9_BD,
    .m9cut = 0.40f,
    .m9res = 0.33f,
    .mglu = 0.30f,
    .mflt = 0.5f,
    .mfres = 0.35f,
    .mfb = 0.35f,
    .mdiv = 2,
    .msend = { 0.10f, 0.10f, 0.0f, 0.0f },
    .fxverb = { 0, 0, 0, 0 },
    .level = { 1, 1, 1, 1, 1 },
    .flmix = 0.5f,
    .flfb = 0.5f,
    .phmix = 0.5f,
    .phfb = 0.5f,
    .fxpage = -1,
    .vowvow = 0.5f,
    .vowq = 0.6f,
    .vowmix = 0.7f,
    .vowglide = 0.35f,
    .vowcur = 0.5f,
    .vowtgt = 0.5f,
    .vowdens = 0.5f,
    .vowgate = 1.0f,
    .vowgtgt = 1.0f,
    .vowgap = 1.0f,
    .curpat = { 0, 0, 0, 0, 0 },
    .armpat = { -1, -1, -1, -1, -1 },
    .playing = 1,
    .laststep = -1,
    .laststep303 = { -1, -1 },
    .g_bpm = 132,
    .bpm01 = 0.5143f,
    .rollctr = { -1, -1 },
    .roll_pit = { 24, 24 },
    .g_drag_frame = -100,
    .g_drag_y = 100,
    .mout_clk = 1,
    .mo_held = { -1, -1 },
    .drum_ui = { { DS_VCE, DD_ACC, 0,0,0, 0,0,0 }, { DS_VCE, DD_ACC, 0,0,0, 0,0,0 } },
};

/* HOW THE MACROS FIND THE STATE — the same fork every cart-land header takes (cart_ctx.h).
 *
 * DEFAULT: the template IS the state. `de_cart->x` folds to `de_cart_default.x`, which is
 * the same file-scope storage the statics had, so a cart that is not a plug-in rack pays
 * nothing and renders byte-identically. That path is what almost every cart compiles.
 *
 * OPT-IN (a rack an AUv3 can load twice): each instance gets its OWN copy of the template
 * through de_state_for, keyed by the address of a sentinel this translation unit owns —
 * unique by construction, so nothing needs a registry. The copy is what carries the 59
 * non-zero defaults: de_state_for hands back ZEROED memory, and a sequencer booting with
 * every tempo and level at 0 is not the same instrument.
 *
 * ⚠ NEVER CACHE the returned pointer. Another header registering its key can grow the
 * state block and move every slice; a pointer held across calls is a use-after-realloc.
 * ⚠ The template is READ-ONLY in the opt-in path — nothing writes through it, so instance
 * 7 copies the same pristine values instance 0 did. (The engine had to learn this the
 * hard way: it copied a template instance 0 had already mutated, and shipped live heap
 * pointers to a second instance, which corrupted the heap in GarageBand.) */
#ifndef DE_CART_CTX
#define de_cart (&de_cart_default)
#else
static char de_cart_key_;
static CartState *de_cart_(void) {
    /* _saved: this is the rack the PLAYER built — knobs, patterns, machine selection — so it is what
     * de_save_state writes into the host's session state and restores on reopen. Every member is a
     * plain value; the one POINTER that used to live here (nav_poison, an array of widget addresses)
     * moved to AcidScratch below, because a saved slice is restored into a different process where an
     * address from this one names nothing. Kept honest by tools/lint-saved-state.js. */
    CartState *c = (CartState *)de_state_for_saved(&de_cart_key_, (int)sizeof(CartState));
    if (c && !c->de_ctx_inited_) { *c = de_cart_default; c->de_ctx_inited_ = 1; }
    return c;
}
#define de_cart de_cart_()
#endif

/* ── SCRATCH: per-instance, but NEVER saved ───────────────────────────────────────────────────────
 * The nav-focus poison list is UI bookkeeping rebuilt as you move around the panel, and it holds
 * WIDGET POINTERS. It has to be per-instance for the same reason everything else here does (two racks
 * must not share a focus ring), but it must not travel in a session blob. Hence the second slice:
 * `de_state_for` rather than `de_state_for_saved`. */
/* ⚠ HOST-MIDI LIVE STATE LIVES HERE, NOT IN CartState — deliberately. It is not intent (the host owns
 * it, and a wheel position is meaningless to restore), and keeping it out means wiring the mod wheel
 * did NOT change the saved layout, so projects saved before it keep loading. Putting it in CartState
 * would have grown the slice, moved the fingerprint, and silently invalidated every existing project
 * for a value nobody wanted back. */
typedef struct {
    void *nav_poison[6]; int nav_poison_n;
    int   mod_cc;            /* last CC1 seen, 0..127. Zero-init is CORRECT and needs no seeding: a
                              * wheel at rest and a host that never sent one both mean "do not
                              * override the FLT knob", so 0 is the neutral in both paths. */
    int   bend_last;         /* last pitch-bend pushed, so a bend only rides the voice on CHANGE and
                              * a 303 SLIDE (which is itself a note_pitch glide) is left alone at 0 */
    int   last_midi[2];      /* the note each 303 line is currently sounding, for bend to offset from */
} AcidScratch;
#ifndef DE_CART_CTX
static AcidScratch de_acid_scratch_default;
#define de_acid_scratch (&de_acid_scratch_default)
#else
static char de_acid_scratch_key_;
static AcidScratch *de_acid_scratch_(void) {
    return (AcidScratch *)de_state_for(&de_acid_scratch_key_, (int)sizeof(AcidScratch));
}
#define de_acid_scratch de_acid_scratch_()
#endif

/* the access block: every name the cart already uses, pointed at the context.
 * NOTHING below this line changes between the two paths above. */
#define aS             (de_cart->aS)
#define aComp          (de_cart->aComp)
#define aBpm           (de_cart->aBpm)
#define aEf            (de_cart->aEf)
#define aMode          (de_cart->aMode)
#define aEt            (de_cart->aEt)
#define aCrush         (de_cart->aCrush)
#define aGate          (de_cart->aGate)
#define aFlm           (de_cart->aFlm)
#define aFlf           (de_cart->aFlf)
#define aPhm           (de_cart->aPhm)
#define aPhf           (de_cart->aPhf)
#define aSwpRate       (de_cart->aSwpRate)
#define aFlon          (de_cart->aFlon)
#define aPhon          (de_cart->aPhon)
#define aVw            (de_cart->aVw)
#define aVq            (de_cart->aVq)
#define aVm            (de_cart->aVm)
#define aRv            (de_cart->aRv)
#define aD8            (de_cart->aD8)
#define aD9            (de_cart->aD9)
#define aLv            (de_cart->aLv)
#define bpm3_buf       (de_cart->bpm3_buf)
#define use_bars       (de_cart->use_bars)
#define tick           (de_cart->tick)
#define note_erase     (de_cart->note_erase)
#define sng_shf        (de_cart->sng_shf)
#define r2sng_shf      (de_cart->r2sng_shf)
#define sng_confirm    (de_cart->sng_confirm)
#define r2sng_confirm  (de_cart->r2sng_confirm)
#define mac            (de_cart->mac)
#define face           (de_cart->face)
#define rack_view      (de_cart->rack_view)
#define r2_focus       (de_cart->r2_focus)
#define r2_selmach     (de_cart->r2_selmach)
#define r2_dpaint      (de_cart->r2_dpaint)
#define r2_octpen      (de_cart->r2_octpen)
#define r2_303panel    (de_cart->r2_303panel)
#define r2_drumpanel   (de_cart->r2_drumpanel)
#define r2_mstpanel    (de_cart->r2_mstpanel)
#define r2_mstlane     (de_cart->r2_mstlane)
#define r2_dark        (de_cart->r2_dark)
#define ac             (de_cart->ac)
#define s_on           (de_cart->s_on)
#define pit            (de_cart->pit)
#define acc            (de_cart->acc)
#define sld            (de_cart->sld)
#define s_sel          (de_cart->s_sel)
#define mroot          (de_cart->mroot)
#define mscale         (de_cart->mscale)
#define loct           (de_cart->loct)
#define drag_gx        (de_cart->drag_gx)
#define drag_gy        (de_cart->drag_gy)
#define drag_axis      (de_cart->drag_axis)
#define drag_paint     (de_cart->drag_paint)
#define drag_on0       (de_cart->drag_on0)
#define tie            (de_cart->tie)
#define oct            (de_cart->oct)
#define plen           (de_cart->plen)
#define lpos           (de_cart->lpos)
#define pscreen        (de_cart->pscreen)
#define kpage          (de_cart->kpage)
#define seq_grid       (de_cart->seq_grid)
#define keys_mode      (de_cart->keys_mode)
#define key_oct        (de_cart->key_oct)
#define s_armed        (de_cart->s_armed)
#define dscreen        (de_cart->dscreen)
#define darmed         (de_cart->darmed)
#define dmut_latch     (de_cart->dmut_latch)
#define dmut_hold      (de_cart->dmut_hold)
#define dmut_now       (de_cart->dmut_now)
#define drec_latch     (de_cart->drec_latch)
#define drec_hold      (de_cart->drec_hold)
#define drec_now       (de_cart->drec_now)
#define dmute          (de_cart->dmute)
#define d9mute         (de_cart->d9mute)
#define paint_val      (de_cart->paint_val)
#define dgrid          (de_cart->dgrid)
#define dtune          (de_cart->dtune)
#define ddecay         (de_cart->ddecay)
#define dcolor         (de_cart->dcolor)
#define dvol           (de_cart->dvol)
#define dpan           (de_cart->dpan)
#define dpanlast       (de_cart->dpanlast)
#define dfine          (de_cart->dfine)
#define dtunefine      (de_cart->dtunefine)
#define dsel           (de_cart->dsel)
#define dtrig          (de_cart->dtrig)
#define d9grid         (de_cart->d9grid)
#define d9tune         (de_cart->d9tune)
#define d9decay        (de_cart->d9decay)
#define d9color        (de_cart->d9color)
#define d9vol          (de_cart->d9vol)
#define d9pan          (de_cart->d9pan)
#define d9panlast      (de_cart->d9panlast)
#define d9fine         (de_cart->d9fine)
#define d9tunefine     (de_cart->d9tunefine)
#define d9sel          (de_cart->d9sel)
#define d9trig         (de_cart->d9trig)
#define m9cut          (de_cart->m9cut)
#define m9res          (de_cart->m9res)
#define dacc           (de_cart->dacc)
#define dprob          (de_cart->dprob)
#define d9acc          (de_cart->d9acc)
#define d9prob         (de_cart->d9prob)
#define d9strk         (de_cart->d9strk)
#define doff           (de_cart->doff)
#define d9off          (de_cart->d9off)
#define mglu           (de_cart->mglu)
#define mflt           (de_cart->mflt)
#define mfres          (de_cart->mfres)
#define mfb            (de_cart->mfb)
#define mpump          (de_cart->mpump)
#define mdiv           (de_cart->mdiv)
#define msend          (de_cart->msend)
#define fxverb         (de_cart->fxverb)
#define dist8          (de_cart->dist8)
#define dist9          (de_cart->dist9)
#define level          (de_cart->level)
#define mpcf           (de_cart->mpcf)
#define mcrush         (de_cart->mcrush)
#define mgate          (de_cart->mgate)
#define mstflow        (de_cart->mstflow)
#define flmix          (de_cart->flmix)
#define flfb           (de_cart->flfb)
#define phmix          (de_cart->phmix)
#define phfb           (de_cart->phfb)
#define flon           (de_cart->flon)
#define phon           (de_cart->phon)
#define mswdiv         (de_cart->mswdiv)
#define fxpage         (de_cart->fxpage)
#define fxdry_latch    (de_cart->fxdry_latch)
#define fxdry_hold     (de_cart->fxdry_hold)
#define vowon          (de_cart->vowon)
#define vowvow         (de_cart->vowvow)
#define vowq           (de_cart->vowq)
#define vowmix         (de_cart->vowmix)
#define vowspeak       (de_cart->vowspeak)
#define vowglide       (de_cart->vowglide)
#define vowcur         (de_cart->vowcur)
#define vowtgt         (de_cart->vowtgt)
#define vowstep        (de_cart->vowstep)
#define vowdens        (de_cart->vowdens)
#define vowgate        (de_cart->vowgate)
#define vowgtgt        (de_cart->vowgtgt)
#define vowgap         (de_cart->vowgap)
#define vowfired       (de_cart->vowfired)
#define pat303         (de_cart->pat303)
#define pat808         (de_cart->pat808)
#define pat909         (de_cart->pat909)
#define curpat         (de_cart->curpat)
#define armpat         (de_cart->armpat)
#define playing        (de_cart->playing)
#define s_step         (de_cart->s_step)
#define laststep       (de_cart->laststep)
#define laststep303    (de_cart->laststep303)
#define mbop           (de_cart->mbop)
#define g_bpm          (de_cart->g_bpm)
#define bpm01          (de_cart->bpm01)
#define g_phase        (de_cart->g_phase)
#define g_last_t       (de_cart->g_last_t)
#define g_swing        (de_cart->g_swing)
#define pf_latch       (de_cart->pf_latch)
#define pf_hold        (de_cart->pf_hold)
#define pf_half        (de_cart->pf_half)
#define pf_acc         (de_cart->pf_acc)
#define pf_oct         (de_cart->pf_oct)
#define pf_stac        (de_cart->pf_stac)
#define pf_glide       (de_cart->pf_glide)
#define pf_rev         (de_cart->pf_rev)
#define pf_roll        (de_cart->pf_roll)
#define rollctr        (de_cart->rollctr)
#define roll_pit       (de_cart->roll_pit)
#define roll_acc       (de_cart->roll_acc)
#define dpf_latch      (de_cart->dpf_latch)
#define dpf_hold       (de_cart->dpf_hold)
#define pf_rp1         (de_cart->pf_rp1)
#define pf_rp2         (de_cart->pf_rp2)
#define pf_rp4         (de_cart->pf_rp4)
#define pf_thin        (de_cart->pf_thin)
#define pf_busy        (de_cart->pf_busy)
#define pf_dacc        (de_cart->pf_dacc)
#define rpt_base       (de_cart->rpt_base)
#define rpt_n          (de_cart->rpt_n)
#define rpt_was        (de_cart->rpt_was)
#define g_drag_frame   (de_cart->g_drag_frame)
#define g_drag_y       (de_cart->g_drag_y)
#define bend_range     (de_cart->bend_range)
#define nav_poison     (de_acid_scratch->nav_poison)
#define nav_poison_n   (de_acid_scratch->nav_poison_n)
#define mod_cc         (de_acid_scratch->mod_cc)
#define bend_last      (de_acid_scratch->bend_last)
#define last_midi      (de_acid_scratch->last_midi)
#define g_bank         (de_cart->g_bank)
#define g_scratch      (de_cart->g_scratch)
#define save_cooldown  (de_cart->save_cooldown)
#define mout_on        (de_cart->mout_on)
#define mout_clk       (de_cart->mout_clk)
#define mo_held        (de_cart->mo_held)
#define mo_clk_sent    (de_cart->mo_clk_sent)
#define mo_was_playing (de_cart->mo_was_playing)
#define drum_ui        (de_cart->drum_ui)

#endif
