/* pedalboard_state.h — GENERATED by tools/ctx-gen.js. Do not edit by hand.
 *
 * The per-instance engine context (docs/design/engine-context.md). An AUv3 puts every plug-in
 * instance in ONE process, so state that lives in file-scope statics is shared by every
 * instance — which is why two DAW tracks fight over one rack. These members used to be those
 * statics; the macro block at the bottom means the engine code reads exactly as it did before.
 *
 * The default instance below is a `static` with DESIGNATED INITIALISERS, so every value is
 * still set at compile time exactly as it was, and the rest is still zeroed static storage.
 * That is what makes this a pure move with no init-order risk: nothing can read a member
 * before it is set, because the linker sets it. A real per-instance context is then created
 * by copying this template, which is exact by construction.
 */
#ifndef DE_PEDALBOARD_STATE_H
#define DE_PEDALBOARD_STATE_H

/* self-contained: the members use these, and depending on where this header lands in
 * sound.h they may not have been pulled in yet. */
#include <stdint.h>
#include <stdbool.h>
#include <stdatomic.h>

/* MOVED here from cart.c: the sizes and constants the members below are written in.
 * They have to precede the struct, and moving a #define earlier is always safe because a
 * macro body is only text until it is expanded. */
#define NSTR   6
#define MAXK   4
#define NROOT  7
enum { C_BIT, C_EQ, C_CHO, C_PHA, C_FLG, C_TAP, C_TRM, C_WAH, C_RVB, C_FMT, C_PAN, C_FIL, C_RNG, C_DLY, C_LOFI, C_FUZZ, C_GRN, C_EQ2, C_OD, C_SHW, C_GATE, C_SHMR, NCAT };
typedef struct { int cat; float k[MAXK]; bool on; } Slot;
enum { CAB_NONE, CAB_AMP, CAB_LESLIE };
#define KM_N   8
typedef struct { int used, cat, knob, gf, ltf; float gval; } KMeta;
enum { TH_NONE, TH_MIN, TH_SUS4, TH_SUS2, TH_5, NTHIRD };   // the THIRDS group (none = major)
enum { SV_NONE, SV_7, SV_MAJ7, NSEV };                      // the SEVENTH group
enum { AP_OFF, AP_STRUM, AP_TRAVIS };
typedef struct { int id, mode, slot, knob, cat, prevY, x, y; } Ptr;   // id MUST be first (pointer.h)

typedef struct {
    int saX;
    int saY;
    int saW;
    int saH;
    Slot chain[NCAT];
    int chain_n;
    float scroll_x;
    bool palette_open;
    int dirty;
    int cab_tenant;
    bool cabfuzz_applied;
    int cab_voicing;
    int cab_speed;
    float cab_k[2];
    int drag_cat;
    int drag_knob;
    bool drag_fine;
    int frame_no;
    KMeta kmeta[KM_N];
    bool rig_open;
    const char *ROOT_NAME[NROOT];
    int sel_third;
    int sel_sev;
    bool sel_add9;
    int sel_root;
    int str_midi[NSTR];
    float amp[NSTR];
    float vib_ph[NSTR];
    int pend[NSTR];
    const char *AP_NAME[3];
    int autoplay;
    bool ap_own_chord;
    int cart_bpm;
    int apos;
    bool guitar_in;
    int ap_gtr_in;
    float fmt_vowel;
    float fmt_target;
    float fmt_env;
    int fmt_step;
    float fmt_lfo_ph;
    float fmt_last_v;
    Ptr ptr[PTR_MAX];
    int de_ctx_inited_;   // set once, when this instance copies the template below
} CartState;

/* the compile-time defaults — one line per static that carried a non-zero initialiser */
static CartState de_cart_default = {
    .dirty = 1,
    .cab_tenant = CAB_NONE,
    .cab_voicing = 2,
    .cab_speed = LESLIE_SLOW,
    .cab_k = { 0.5f, 0.5f },
    .drag_cat = -99,
    .drag_knob = -1,
    .ROOT_NAME = { "E", "F", "G", "A", "B", "C", "D" },
    .sel_third = TH_NONE,
    .sel_sev = SV_NONE,
    .sel_root = 2,
    .AP_NAME = { "off", "strum", "travis" },
    .autoplay = AP_STRUM,
    .cart_bpm = 100,
    .ap_gtr_in = -1,
    .fmt_vowel = 0.5f,
    .fmt_target = 0.5f,
    .fmt_last_v = -2.0f,
};

/* HOW THE MACROS FIND THE STATE — the same fork every cart-land header takes (cart_ctx.h).
 *
 * DEFAULT: the template IS the state. `de_cart->x` folds to `de_cart_default.x`, which is
 * the same file-scope storage the statics had, so a cart that is not a plug-in rack pays
 * nothing and renders byte-identically. That path is what almost every cart compiles.
 *
 * OPT-IN (a rack an AUv3 can load twice): each instance gets its OWN copy of the template
 * through de_state_for, keyed by the address of a sentinel this translation unit owns —
 * unique by construction, so nothing needs a registry. The copy is what carries the 59
 * non-zero defaults: de_state_for hands back ZEROED memory, and a sequencer booting with
 * every tempo and level at 0 is not the same instrument.
 *
 * ⚠ NEVER CACHE the returned pointer. Another header registering its key can grow the
 * state block and move every slice; a pointer held across calls is a use-after-realloc.
 * ⚠ The template is READ-ONLY in the opt-in path — nothing writes through it, so instance
 * 7 copies the same pristine values instance 0 did. (The engine had to learn this the
 * hard way: it copied a template instance 0 had already mutated, and shipped live heap
 * pointers to a second instance, which corrupted the heap in GarageBand.) */
#ifndef DE_CART_CTX
#define de_cart (&de_cart_default)
#else
static char de_cart_key_;
static CartState *de_cart_(void) {
    CartState *c = (CartState *)de_state_for(&de_cart_key_, (int)sizeof(CartState));
    if (c && !c->de_ctx_inited_) { *c = de_cart_default; c->de_ctx_inited_ = 1; }
    return c;
}
#define de_cart de_cart_()
#endif

/* the access block: every name the cart already uses, pointed at the context.
 * NOTHING below this line changes between the two paths above. */
#define saX             (de_cart->saX)
#define saY             (de_cart->saY)
#define saW             (de_cart->saW)
#define saH             (de_cart->saH)
#define chain           (de_cart->chain)
#define chain_n         (de_cart->chain_n)
#define scroll_x        (de_cart->scroll_x)
#define palette_open    (de_cart->palette_open)
#define dirty           (de_cart->dirty)
#define cab_tenant      (de_cart->cab_tenant)
#define cabfuzz_applied (de_cart->cabfuzz_applied)
#define cab_voicing     (de_cart->cab_voicing)
#define cab_speed       (de_cart->cab_speed)
#define cab_k           (de_cart->cab_k)
#define drag_cat        (de_cart->drag_cat)
#define drag_knob       (de_cart->drag_knob)
#define drag_fine       (de_cart->drag_fine)
#define frame_no        (de_cart->frame_no)
#define kmeta           (de_cart->kmeta)
#define rig_open        (de_cart->rig_open)
#define ROOT_NAME       (de_cart->ROOT_NAME)
#define sel_third       (de_cart->sel_third)
#define sel_sev         (de_cart->sel_sev)
#define sel_add9        (de_cart->sel_add9)
#define sel_root        (de_cart->sel_root)
#define str_midi        (de_cart->str_midi)
#define amp             (de_cart->amp)
#define vib_ph          (de_cart->vib_ph)
#define pend            (de_cart->pend)
#define AP_NAME         (de_cart->AP_NAME)
#define autoplay        (de_cart->autoplay)
#define ap_own_chord    (de_cart->ap_own_chord)
#define cart_bpm        (de_cart->cart_bpm)
#define apos            (de_cart->apos)
#define guitar_in       (de_cart->guitar_in)
#define ap_gtr_in       (de_cart->ap_gtr_in)
#define fmt_vowel       (de_cart->fmt_vowel)
#define fmt_target      (de_cart->fmt_target)
#define fmt_env         (de_cart->fmt_env)
#define fmt_step        (de_cart->fmt_step)
#define fmt_lfo_ph      (de_cart->fmt_lfo_ph)
#define fmt_last_v      (de_cart->fmt_last_v)
#define ptr             (de_cart->ptr)

#endif
