// rhythmbox.h — GENERATED by tools/gen-rhythmbox.js from
// docs/design/rhythm-box-patterns.md. DO NOT HAND-EDIT: edit the doc, then regenerate.
//
// 64 preset rhythms and 386 lanes, read off three manufacturers' own documents
// (service manuals and a 1979 databook). The doc carries the provenance, the page and
// figure numbers, the per-rhythm confidence markers and the caveats; this header carries
// only the bits. Anything you want to CLAIM about this data, check in the doc first.
//
// A lane is a 48-bit mask over COUNTS, so one rhythm is a handful of integers and the whole
// library costs a few KB of rodata.
//
// THREE THINGS THAT ARE NOT OPTIONAL if you play this data (all measured, see the doc):
//  1. counts_per_beat and bars are PER RHYTHM, not per machine. The FR-2L waltz divides its
//     24-count bar by THREE (8-count beats) while its 4/4 rhythms divide by four, and its
//     slow rock reads all 48 counts as ONE 12/8 bar. Read rb->per_beat, never assume.
//  2. `unused` marks counts a rhythm SKIPS (the TR-77 hatches them on the page). A hit can
//     never fall there; stepping over them is what gives that rhythm its meter.
//  3. RB_GATE lanes are HELD, not struck (a brush swish, a guiro). Firing a one-shot for a
//     gate lane is wrong. Lanes flagged RB_PARTIAL have a region the source left UNREAD.
//  4. A lane flagged RB_RESETCOL is NOT AN INSTRUMENT: on the SGS chip a rhythm shorter than
//     32 states is made by crossing its 8th instrument column, which then carries the reset
//     instead. The datasheet says so and the data agrees in all 7 cases (0 exceptions), so
//     every short SGS rhythm has SEVEN instruments, not eight. Skip these lanes when you
//     lay out voices, or you will wire a drum to a counter.
//
// LANE LABELS ARE PROVISIONAL on the FR-2L: its scan is ~75 dpi and the letterforms are
// interpolation, so lane ORDER is reliable and the letters are not. Assign voices by order
// and taste; do not claim which voice plays which lane. The SGS lanes are chip PINS, and
// its two masks map pins to instruments DIFFERENTLY (doc §4).
#ifndef RHYTHMBOX_H
#define RHYTHMBOX_H

#define RB_HIT     0   // struck: fire a one-shot on each set bit
#define RB_GATE    1   // held: the set bits are the counts the sound is SOUNDING
#define RB_PARTIAL  1   // lane flag: part of this lane was UNREAD in the source
#define RB_RESETCOL 2   // lane flag: NOT an instrument — this column carries the RESET

typedef struct {
    const char        *label;   // as printed (provisional on the FR-2L, see above)
    const char        *code;    // the machine's own pulse-train / trigger number, verbatim
    unsigned char      kind;    // RB_HIT or RB_GATE
    unsigned char      flags;   // RB_PARTIAL, or 0
    unsigned long long mask;    // bit i set = a mark on count i
    unsigned long long maybe;   // bit i set = the source read this cell as UNCERTAIN
} RbLane;

typedef struct {
    const char        *name;
    const char        *machine;
    unsigned char      counts;    // counts in one pass of the pattern
    unsigned char      per_bar;
    unsigned char      per_beat;  // PER RHYTHM (see note 1 above)
    unsigned char      bars;
    unsigned char      nlanes;
    unsigned long long unused;    // counts this rhythm skips (see note 2 above)
    const RbLane      *lane;
} RbRhythm;

// ── Ace Tone Rhythm Ace FR-2L (c.1969) ──
static const RbLane RB_FR2L_L0[] = {
    { "M", "", RB_HIT, 0, 0x249259249259ULL, 0x0ULL },
    { "C", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "Cb", "", RB_HIT, 0, 0x208208208208ULL, 0x0ULL },
    { "Cy", "", RB_HIT, 0, 0x8000008ULL, 0x0ULL },
    { "Lc", "", RB_HIT, 0, 0x8000008ULL, 0x0ULL },
    { "LcBd", "", RB_HIT, 0, 0x41001041001ULL, 0x0ULL },
};
static const RbLane RB_FR2L_L1[] = {
    { "Cy", "25", RB_HIT, 0, 0x40040040040ULL, 0x0ULL },
    { "Cy'", "5", RB_HIT, 0, 0x249249249249ULL, 0x0ULL },
    { "Cb+Hb", "17", RB_HIT, 0, 0x8040040201ULL, 0x0ULL },
    { "Lc+Bd", "2", RB_HIT, 0, 0x1001001001ULL, 0x0ULL },
};
static const RbLane RB_FR2L_L2[] = {
    { "Cy", "1", RB_HIT, 0, 0x1000001ULL, 0x0ULL },
    { "M", "34'", RB_HIT, 0, 0x10100010100ULL, 0x0ULL },
    { "Sd", "39", RB_HIT, 0, 0x10100010100ULL, 0x0ULL },
    { "Bd", "1", RB_HIT, 0, 0x1000001ULL, 0x0ULL },
};
static const RbLane RB_FR2L_L3[] = {
    { "B", "34", RB_GATE, RB_PARTIAL, 0x0ULL, 0x0ULL },
    { "(row 2)", "?", RB_HIT, 0, 0x10000000000ULL, 0x0ULL },
    { "Sd", "5?", RB_HIT, 0, 0x41041041041ULL, 0x0ULL },
    { "Bd", "3?", RB_HIT, 0, 0x41041041041ULL, 0x0ULL },
};
static const RbLane RB_FR2L_L4[] = {
    { "C+Hb", "31'", RB_HIT, 0, 0x1000001000ULL, 0x0ULL },
    { "Hc", "32", RB_HIT, 0, 0x100100100100ULL, 0x0ULL },
    { "Lc'Bd", "1", RB_HIT, 0, 0x1000001ULL, 0x0ULL },
};
static const RbLane RB_FR2L_L5[] = {
    { "Cy'", "5", RB_HIT, 0, 0x249249249249ULL, 0x0ULL },
    { "Sd", "25+30", RB_HIT, 0, 0x40240040240ULL, 0x0ULL },
    { "Bd'", "3", RB_HIT, 0, 0x41041041041ULL, 0x0ULL },
    { "Bd", "1", RB_HIT, 0, 0x1000001ULL, 0x0ULL },
};
static const RbLane RB_FR2L_L6[] = {
    { "Cy'", "2+9+33", RB_HIT, 0, 0x111111111111ULL, 0x0ULL },
    { "Sd", "31", RB_HIT, 0, 0x1000001000ULL, 0x0ULL },
    { "Bd", "1", RB_HIT, 0, 0x1000001ULL, 0x0ULL },
};
static const RbLane RB_FR2L_L7[] = {
    { "Cy", "25", RB_HIT, 0, 0x40040040040ULL, 0x0ULL },
    { "(lane2)", "33", RB_HIT, 0, 0x10000000000ULL, 0x0ULL },
    { "Sd", "25", RB_HIT, 0, 0x40040040040ULL, 0x0ULL },
    { "Bd'", "2", RB_HIT, 0, 0x1001001001ULL, 0x0ULL },
    { "Bd", "3", RB_HIT, 0, 0x41041041041ULL, 0x0ULL },
};
static const RbLane RB_FR2L_L8[] = {
    { "M", "", RB_HIT, 0, 0x440440440440ULL, 0x0ULL },
    { "Cy", "", RB_HIT, 0, 0x1001001001ULL, 0x0ULL },
    { "(lane3)", "", RB_HIT, 0, 0x10000000000ULL, 0x0ULL },
    { "Sd", "", RB_HIT, 0, 0x440440440440ULL, 0x0ULL },
    { "Bd", "", RB_HIT, 0, 0x41041041041ULL, 0x0ULL },
};
static const RbLane RB_FR2L_L9[] = {
    { "M", "", RB_HIT, 0, 0x249249249249ULL, 0x0ULL },
    { "Cb", "", RB_HIT, 0, 0x41041041041ULL, 0x0ULL },
    { "Hb", "", RB_HIT, 0, 0x1041001041ULL, 0x0ULL },
    { "Lc", "", RB_HIT, 0, 0x240000240000ULL, 0x0ULL },
    { "Bd", "", RB_HIT, 0, 0x40201040201ULL, 0x0ULL },
};
static const RbLane RB_FR2L_L10[] = {
    { "Sd", "", RB_HIT, 0, 0x41240040040ULL, 0x0ULL },
    { "Cy", "", RB_HIT, 0, 0x1001001001ULL, 0x0ULL },
    { "Bd", "", RB_HIT, 0, 0x1001001001ULL, 0x0ULL },
};
static const RbLane RB_FR2L_L11[] = {
    { "Sd", "", RB_HIT, 0, 0x410410410410ULL, 0x0ULL },
    { "Sd'", "", RB_HIT, 0, 0x41041041041ULL, 0x0ULL },
    { "Cy", "", RB_HIT, 0, 0x41041041041ULL, 0x0ULL },
    { "Bd", "", RB_HIT, 0, 0x41041041041ULL, 0x0ULL },
};
static const RbLane RB_FR2L_L12[] = {
    { "M", "", RB_HIT, 0, 0x1001001001ULL, 0x0ULL },
    { "Cy", "", RB_HIT, 0, 0x200000200000ULL, 0x0ULL },
    { "Sd", "", RB_HIT, 0, 0x200000200000ULL, 0x0ULL },
    { "Sd'", "", RB_HIT, 0, 0x41041041041ULL, 0x0ULL },
    { "Bd", "", RB_HIT, 0, 0x41041041041ULL, 0x0ULL },
};
static const RbLane RB_FR2L_L13[] = {
    { "M", "", RB_HIT, 0, 0x249249249248ULL, 0x0ULL },
    { "Hc", "", RB_HIT, 0, 0x240001240001ULL, 0x0ULL },
    { "Lc", "", RB_HIT, 0, 0x1200001200ULL, 0x0ULL },
    { "Bd", "", RB_HIT, 0, 0x1000001ULL, 0x0ULL },
};
static const RbLane RB_FR2L_L14[] = {
    { "L1 M", "", RB_HIT, 0, 0x249249249259ULL, 0x0ULL },
    { "L2 C", "", RB_HIT, 0, 0x1040040201ULL, 0x0ULL },
    { "L3 Hb", "", RB_HIT, 0, 0x209048249048ULL, 0x0ULL },
    { "L4 Hc", "", RB_HIT, 0, 0x40201040201ULL, 0x0ULL },
    { "L5 Lc", "", RB_HIT, 0, 0x240000240000ULL, 0x0ULL },
    { "L6 Bd", "", RB_HIT, 0, 0x1001001001ULL, 0x0ULL },
};
static const RbLane RB_FR2L_L15[] = {
    { "M?", "", RB_HIT, 0, 0x249249249249ULL, 0x0ULL },
    { "Cb?", "", RB_HIT, 0, 0x41041041041ULL, 0x0ULL },
    { "Hb?", "", RB_HIT, 0, 0x1249001241ULL, 0x0ULL },
    { "Lc?", "", RB_HIT, 0, 0x240000240000ULL, 0x0ULL },
    { "Bd?", "", RB_HIT, 0, 0x201000201ULL, 0x0ULL },
};
static const RbRhythm RB_FR2L[] = {
    { "BEGUINE", "FR2L", 48, 24, 6, 2, 6, 0x0ULL, RB_FR2L_L0 },
    { "Bossanova", "FR2L", 48, 24, 6, 2, 4, 0x0ULL, RB_FR2L_L1 },
    { "Waltz", "FR2L", 48, 24, 8, 2, 4, 0x0ULL, RB_FR2L_L2 },
    { "Dixieland", "FR2L", 48, 24, 6, 2, 4, 0x0ULL, RB_FR2L_L3 },
    { "Western", "FR2L", 48, 24, 6, 2, 3, 0x0ULL, RB_FR2L_L4 },
    { "Rock'n Roll", "FR2L", 48, 24, 6, 2, 4, 0x0ULL, RB_FR2L_L5 },
    { "Slow Rock", "FR2L", 48, 48, 12, 1, 3, 0x0ULL, RB_FR2L_L6 },
    { "Fox Trot", "FR2L", 48, 24, 6, 2, 5, 0x0ULL, RB_FR2L_L7 },
    { "Swing", "FR2L", 48, 24, 6, 2, 5, 0x0ULL, RB_FR2L_L8 },
    { "Cha-Cha", "FR2L", 48, 24, 6, 2, 5, 0x0ULL, RB_FR2L_L9 },
    { "March", "FR2L", 48, 24, 6, 2, 3, 0x0ULL, RB_FR2L_L10 },
    { "Shuffle", "FR2L", 48, 24, 6, 2, 4, 0x0ULL, RB_FR2L_L11 },
    { "Tango", "FR2L", 48, 24, 6, 2, 5, 0x0ULL, RB_FR2L_L12 },
    { "SAMBA", "FR2L", 48, 24, 6, 2, 4, 0x0ULL, RB_FR2L_L13 },
    { "RHUMBA", "FR2L", 48, 24, 6, 2, 6, 0x0ULL, RB_FR2L_L14 },
    { "MAMBO", "FR2L", 48, 24, 6, 2, 5, 0x0ULL, RB_FR2L_L15 },
};
#define RB_FR2L_N 16

// ── Roland Rhythm TR-77 (1972), 16 ruled columns of a 32-state bar ──
static const RbLane RB_TR77_L0[] = {
    { "CY", "14", RB_HIT, 0, 0x4444ULL, 0x0ULL },
    { "HH", "20", RB_HIT, 0, 0xffffULL, 0x0ULL },
    { "SD", "11", RB_HIT, 0, 0x4c4cULL, 0x0ULL },
    { "BD", "9", RB_HIT, 0, 0x1919ULL, 0x0ULL },
};
static const RbLane RB_TR77_L1[] = {
    { "CY", "14", RB_HIT, 0, 0x4444ULL, 0x0ULL },
    { "HH", "20", RB_HIT, 0, 0xffffULL, 0x0ULL },
    { "SD", "25 + 40", RB_HIT, 0, 0x9290ULL, 0x0ULL },
    { "BD", "18 + 33", RB_HIT, 0, 0x705ULL, 0x0ULL },
};
static const RbLane RB_TR77_L2[] = {
    { "CY", "20", RB_HIT, 0, 0x7777ULL, 0x0ULL },
    { "SD", "40", RB_HIT, 0, 0x1010ULL, 0x0ULL },
    { "BD", "18", RB_HIT, 0, 0x101ULL, 0x0ULL },
};
static const RbLane RB_TR77_L3[] = {
    { "CY", "21", RB_HIT, 0, 0x7777ULL, 0x0ULL },
    { "SD", "40", RB_HIT, 0, 0x1010ULL, 0x0ULL },
    { "BD", "15' + 18'", RB_HIT, 0, 0x4141ULL, 0x0ULL },
};
static const RbLane RB_TR77_L4[] = {
    { "C+HB", "40", RB_HIT, 0, 0x1010ULL, 0x0ULL },
    { "LB", "35", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "LC+BD", "18", RB_HIT, 0, 0x101ULL, 0x0ULL },
};
static const RbLane RB_TR77_L5[] = {
    { "CY", "3", RB_HIT, 0, 0x1111ULL, 0x0ULL },
    { "SD", "14+40", RB_HIT, 0, 0x5454ULL, 0x0ULL },
    { "BD", "3", RB_HIT, 0, 0x1111ULL, 0x0ULL },
    { "Me", "5", RB_HIT, 0, 0x1111ULL, 0x0ULL },
};
static const RbLane RB_TR77_L6[] = {
    { "CY", "", RB_HIT, 0, 0x505ULL, 0x202ULL },
    { "SD", "", RB_HIT, 0, 0x2424ULL, 0x0ULL },
    { "BD", "", RB_HIT, 0, 0x101ULL, 0x0ULL },
};
static const RbLane RB_TR77_L7[] = {
    { "CY", "", RB_HIT, 0, 0x101ULL, 0x0ULL },
    { "SD", "", RB_HIT, 0, 0x2424ULL, 0x0ULL },
    { "BD", "", RB_HIT, 0, 0x101ULL, 0x0ULL },
};
static const RbLane RB_TR77_L8[] = {
    { "M", "21", RB_HIT, 0, 0xffffULL, 0x0ULL },
    { "C", "26", RB_HIT, 0, 0x1449ULL, 0x0ULL },
    { "HB", "39", RB_HIT, 0, 0x2424ULL, 0x0ULL },
    { "LB", "8", RB_HIT, 0, 0x1b1bULL, 0x0ULL },
    { "LC", "15", RB_HIT, 0, 0xc0c0ULL, 0x0ULL },
};
static const RbLane RB_TR77_L9[] = {
    { "M", "20", RB_HIT, 0, 0xffffULL, 0x0ULL },
    { "C", "26", RB_HIT, 0, 0x1449ULL, 0x0ULL },
    { "HB", "1", RB_HIT, 0, 0xaaaaULL, 0x0ULL },
    { "CY+LB", "4", RB_HIT, 0, 0x202ULL, 0x0ULL },
    { "[unlabelled]", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "LC+BD", "2 (see note)", RB_HIT, 0, 0x5151ULL, 0x0ULL },
};
static const RbLane RB_TR77_L10[] = {
    { "GU", "6(+12)", RB_GATE, RB_PARTIAL, 0x0ULL, 0x0ULL },
    { "M", "20", RB_HIT, 0, 0xfff5ULL, 0xaULL },
    { "CB+HB", "41", RB_HIT, 0, 0x7575ULL, 0x0ULL },
    { "LB", "15", RB_HIT, 0, 0xc0c0ULL, 0x0ULL },
    { "LC", "17", RB_HIT, 0, 0x4949ULL, 0x0ULL },
};
static const RbLane RB_TR77_L11[] = {
    { "GU", "6(+12)", RB_GATE, RB_PARTIAL, 0x0ULL, 0x0ULL },
    { "M", "20", RB_HIT, 0, 0xffffULL, 0x0ULL },
    { "CB+LB", "42'", RB_HIT, 0, 0x5551ULL, 0x4ULL },
    { "HB", "1", RB_HIT, 0, 0xaaaaULL, 0x0ULL },
    { "LC", "15", RB_HIT, 0, 0xc0c0ULL, 0x0ULL },
    { "BD", "17", RB_HIT, 0, 0x4949ULL, 0x0ULL },
};
static const RbLane RB_TR77_L12[] = {
    { "CY", "14", RB_HIT, 0, 0x4444ULL, 0x0ULL },
    { "M", "20", RB_HIT, 0, 0xffffULL, 0x0ULL },
    { "HB", "37", RB_HIT, 0, 0xa85ULL, 0x0ULL },
    { "LB", "40", RB_HIT, 0, 0x1010ULL, 0x0ULL },
    { "BD", "3", RB_HIT, 0, 0x1111ULL, 0x0ULL },
};
static const RbLane RB_TR77_L13[] = {
    { "TB", "13", RB_HIT, 0, 0xccccULL, 0x0ULL },
    { "TB'", "20(330K)", RB_HIT, 0, 0xffffULL, 0x0ULL },
    { "CB+LB", "38", RB_HIT, 0, 0x1a95ULL, 0x0ULL },
    { "HB", "15", RB_HIT, 0, 0xc0c0ULL, 0x0ULL },
    { "LC", "3", RB_HIT, 0, 0x1111ULL, 0x0ULL },
};
static const RbLane RB_TR77_L14[] = {
    { "CY", "14", RB_HIT, 0, 0x4444ULL, 0x0ULL },
    { "HH", "20", RB_HIT, 0, 0xffffULL, 0x0ULL },
    { "RS", "27", RB_HIT, 0, 0x2449ULL, 0x0ULL },
    { "BD", "9", RB_HIT, 0, 0x1919ULL, 0x0ULL },
    { "Me", "5", RB_HIT, 0, 0x1111ULL, 0x0ULL },
};
static const RbLane RB_TR77_L15[] = {
    { "TB'", "20(330K)", RB_HIT, 0, 0xffffULL, 0x0ULL },
    { "CB+LB", "9", RB_HIT, 0, 0x1919ULL, 0x0ULL },
    { "HB", "15", RB_HIT, 0, 0xc0c0ULL, 0x0ULL },
    { "LC", "23", RB_HIT, 0, 0x1800ULL, 0x0ULL },
    { "Me", "5", RB_HIT, 0, 0x1111ULL, 0x0ULL },
};
static const RbLane RB_TR77_L16[] = {
    { "SD", "31", RB_HIT, 0, 0x9f999999ULL, 0x0ULL },
    { "LB", "31", RB_HIT, 0, 0x9f999999ULL, 0x0ULL },
    { "BD", "3", RB_HIT, 0, 0x1010101ULL, 0x0ULL },
};
static const RbLane RB_TR77_L17[] = {
    { "CY", "16", RB_HIT, 0, 0x8080ULL, 0x0ULL },
    { "SD", "34", RB_HIT, 0, 0xd5d5ULL, 0x0ULL },
    { "BD", "42'", RB_HIT, 0, 0x5555ULL, 0x0ULL },
    { "Me", "42 + 5", RB_HIT, 0, 0x5555ULL, 0x0ULL },
};
static const RbRhythm RB_TR77[] = {
    { "ROCK'N ROLL 1", "TR77", 16, 16, 4, 1, 4, 0x0ULL, RB_TR77_L0 },
    { "ROCK'N ROLL 2", "TR77", 16, 16, 4, 1, 4, 0x0ULL, RB_TR77_L1 },
    { "SLOW ROCK", "TR77", 16, 16, 4, 1, 3, 0x8888ULL, RB_TR77_L2 },
    { "BALLAD", "TR77", 16, 16, 4, 1, 3, 0x8888ULL, RB_TR77_L3 },
    { "WESTERN", "TR77", 16, 16, 4, 1, 3, 0x0ULL, RB_TR77_L4 },
    { "6/8 MARCH", "TR77", 16, 8, 4, 2, 4, 0x8888ULL, RB_TR77_L5 },
    { "JAZZ WALTZ", "TR77", 16, 8, 4, 2, 3, 0x8888ULL, RB_TR77_L6 },
    { "WALTZ", "TR77", 16, 8, 4, 2, 3, 0x8888ULL, RB_TR77_L7 },
    { "RHUMBA", "TR77", 16, 16, 4, 1, 5, 0x0ULL, RB_TR77_L8 },
    { "BEGUINE", "TR77", 16, 16, 4, 1, 6, 0x0ULL, RB_TR77_L9 },
    { "CHA-CHA", "TR77", 16, 16, 4, 1, 5, 0x0ULL, RB_TR77_L10 },
    { "MAMBO", "TR77", 16, 16, 4, 1, 6, 0x0ULL, RB_TR77_L11 },
    { "SAMBA 1", "TR77", 16, 16, 4, 1, 5, 0x0ULL, RB_TR77_L12 },
    { "SAMBA 2", "TR77", 16, 16, 4, 1, 5, 0x0ULL, RB_TR77_L13 },
    { "BOSSANOVA", "TR77", 16, 16, 4, 1, 5, 0x0ULL, RB_TR77_L14 },
    { "BAION", "TR77", 16, 16, 4, 1, 5, 0x0ULL, RB_TR77_L15 },
    { "BOLERO", "TR77", 16, 16, 4, 1, 3, 0x0ULL, RB_TR77_L16 },
    { "TANGO", "TR77", 16, 16, 4, 1, 4, 0x0ULL, RB_TR77_L17 },
};
#define RB_TR77_N 18

// ── SGS M252 rhythm LSI, factory masks AA and AD ──
static const RbLane RB_SGS_L0[] = {
    { "OUT 1", "", RB_HIT, 0, 0x1001ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x114110ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x1001ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, RB_RESETCOL, 0x0ULL, 0x0ULL },
};
static const RbLane RB_SGS_L1[] = {
    { "OUT 1", "", RB_HIT, 0, 0x1001ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x998118ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x100100ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x800000ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, RB_RESETCOL, 0x0ULL, 0x0ULL },
};
static const RbLane RB_SGS_L2[] = {
    { "OUT 1", "", RB_HIT, 0, 0x51115111ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0xf1115111ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x40004000ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
};
static const RbLane RB_SGS_L3[] = {
    { "OUT 1", "", RB_HIT, 0, 0x1010101ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0xf0101010ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x1010101ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
};
static const RbLane RB_SGS_L4[] = {
    { "OUT 1", "", RB_HIT, 0, 0x1010101ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x10101010ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x10101ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x99809090ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
};
static const RbLane RB_SGS_L5[] = {
    { "OUT 1", "", RB_HIT, 0, 0x1010101ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x10105010ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x100010ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x44005000ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, 0, 0x1010101ULL, 0x0ULL },
};
static const RbLane RB_SGS_L6[] = {
    { "OUT 1", "", RB_HIT, 0, 0x401401ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x40040ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x55d555ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, RB_RESETCOL, 0x0ULL, 0x0ULL },
};
static const RbLane RB_SGS_L7[] = {
    { "OUT 1", "", RB_HIT, 0, 0x45054505ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x92901290ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x10101010ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, 0, 0x55555555ULL, 0x0ULL },
};
static const RbLane RB_SGS_L8[] = {
    { "OUT 1", "", RB_HIT, 0, 0x249249ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0xb6db6dULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x249249ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, RB_RESETCOL, 0x0ULL, 0x0ULL },
};
static const RbLane RB_SGS_L9[] = {
    { "OUT 1", "", RB_HIT, 0, 0x10411041ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x11444511ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x44444444ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x11111111ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x50005000ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, 0, 0x55555555ULL, 0x0ULL },
};
static const RbLane RB_SGS_L10[] = {
    { "OUT 1", "", RB_HIT, 0, 0x11011101ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x44444444ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x44444444ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x40004ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x400040ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x1c001cULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, 0, 0x55555555ULL, 0x0ULL },
};
static const RbLane RB_SGS_L11[] = {
    { "OUT 1", "", RB_HIT, 0, 0x11411141ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x51115111ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x51115111ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x50005000ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, 0, 0x55555555ULL, 0x0ULL },
};
static const RbLane RB_SGS_L12[] = {
    { "OUT 1", "", RB_HIT, 0, 0x10011001ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x1410141ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x50005000ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x1410141ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x1400000ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, 0, 0x55555555ULL, 0x0ULL },
};
static const RbLane RB_SGS_L13[] = {
    { "OUT 1", "", RB_HIT, 0, 0x1010101ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x1444111ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x10005000ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x1450111ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x10101010ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, 0, 0x55555555ULL, 0x0ULL },
};
static const RbLane RB_SGS_L14[] = {
    { "OUT 1", "", RB_HIT, 0, 0x41414141ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x4101041ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x50505050ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, 0, 0x55555555ULL, 0x0ULL },
};
static const RbLane RB_SGS_L15[] = {
    { "OUT 1", "", RB_HIT, 0, 0x1001ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x118110ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x1001ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, RB_RESETCOL, 0x0ULL, 0x0ULL },
};
static const RbLane RB_SGS_L16[] = {
    { "OUT 1", "", RB_HIT, 0, 0x1010101ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0xf0000000ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0xf0000000ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x11010101ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
};
static const RbLane RB_SGS_L17[] = {
    { "OUT 1", "", RB_HIT, 0, 0x1010101ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x50101110ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x50000000ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x1010101ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
};
static const RbLane RB_SGS_L18[] = {
    { "OUT 1", "", RB_HIT, 0, 0x91111111ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x80101011ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x80101011ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x91919191ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x40000000ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
};
static const RbLane RB_SGS_L19[] = {
    { "OUT 1", "", RB_HIT, 0, 0x14151415ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x4c405580ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x5400fcULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x15444511ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x1101041ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, 0, 0x1010101ULL, 0x0ULL },
};
static const RbLane RB_SGS_L20[] = {
    { "OUT 1", "", RB_HIT, 0, 0x1401ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x440040ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x555555ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x41041ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, RB_RESETCOL, 0x0ULL, 0x0ULL },
};
static const RbLane RB_SGS_L21[] = {
    { "OUT 1", "", RB_HIT, 0, 0x1410141ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x50101010ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x55555555ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x4040404ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
};
static const RbLane RB_SGS_L22[] = {
    { "OUT 1", "", RB_HIT, 0, 0x41414141ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x55105050ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x44101041ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x55555555ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x4101041ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, 0, 0x4101414ULL, 0x0ULL },
};
static const RbLane RB_SGS_L23[] = {
    { "OUT 1", "", RB_HIT, 0, 0x5050505ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x4101041ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x4101041ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x4101141ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x55555555ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x440150ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x54004401ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, 0, 0x4101041ULL, 0x0ULL },
};
static const RbLane RB_SGS_L24[] = {
    { "OUT 1", "", RB_HIT, 0, 0x15111111ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x80010005ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0xd5055105ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x55555555ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x15111111ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, 0, 0x111111ULL, 0x0ULL },
};
static const RbLane RB_SGS_L25[] = {
    { "OUT 1", "", RB_HIT, 0, 0x10411041ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x1100001ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x50000000ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x45144554ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x1011041ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, 0, 0x10010101ULL, 0x0ULL },
};
static const RbLane RB_SGS_L26[] = {
    { "OUT 1", "", RB_HIT, 0, 0x11011001ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x40004ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x44044404ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x440f44ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x555d555dULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x40004ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, 0, 0x1101041ULL, 0x0ULL },
};
static const RbLane RB_SGS_L27[] = {
    { "OUT 1", "", RB_HIT, 0, 0x10011001ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x1400000ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x50005000ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x1410141ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x55555555ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x1410141ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
};
static const RbLane RB_SGS_L28[] = {
    { "OUT 1", "", RB_HIT, 0, 0x1010101ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0x10105010ULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x1010101ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x44005000ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x100010ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
};
static const RbLane RB_SGS_L29[] = {
    { "OUT 1", "", RB_HIT, 0, 0x149249ULL, 0x0ULL },
    { "OUT 2", "", RB_HIT, 0, 0xf4d34dULL, 0x0ULL },
    { "OUT 3", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 4", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 5", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 6", "", RB_HIT, 0, 0x269269ULL, 0x0ULL },
    { "OUT 7", "", RB_HIT, 0, 0x0ULL, 0x0ULL },
    { "OUT 8", "", RB_HIT, RB_RESETCOL, 0x0ULL, 0x0ULL },
};
static const RbRhythm RB_SGS[] = {
    { "TABLE 1 (M252 AA) — RHYTHM 1", "SGS", 24, 24, 8, 1, 8, 0x0ULL, RB_SGS_L0 },
    { "TABLE 1 (M252 AA) — RHYTHM 2", "SGS", 24, 24, 8, 1, 8, 0x0ULL, RB_SGS_L1 },
    { "TABLE 1 (M252 AA) — RHYTHM 3", "SGS", 32, 32, 8, 1, 8, 0x0ULL, RB_SGS_L2 },
    { "TABLE 1 (M252 AA) — RHYTHM 4", "SGS", 32, 32, 8, 1, 8, 0x0ULL, RB_SGS_L3 },
    { "TABLE 1 (M252 AA) — RHYTHM 5", "SGS", 32, 32, 8, 1, 8, 0x0ULL, RB_SGS_L4 },
    { "TABLE 1 (M252 AA) — RHYTHM 6", "SGS", 32, 32, 8, 1, 8, 0x0ULL, RB_SGS_L5 },
    { "TABLE 1 (M252 AA) — RHYTHM 7", "SGS", 24, 24, 8, 1, 8, 0x0ULL, RB_SGS_L6 },
    { "TABLE 1 (M252 AA) — RHYTHM 8", "SGS", 32, 32, 8, 1, 8, 0x0ULL, RB_SGS_L7 },
    { "TABLE 1 (M252 AA) — RHYTHM 9", "SGS", 24, 24, 8, 1, 8, 0x0ULL, RB_SGS_L8 },
    { "TABLE 1 (M252 AA) — RHYTHM 10", "SGS", 32, 32, 8, 1, 8, 0x0ULL, RB_SGS_L9 },
    { "TABLE 1 (M252 AA) — RHYTHM 11", "SGS", 32, 32, 8, 1, 8, 0x0ULL, RB_SGS_L10 },
    { "TABLE 1 (M252 AA) — RHYTHM 12", "SGS", 32, 32, 8, 1, 8, 0x0ULL, RB_SGS_L11 },
    { "TABLE 1 (M252 AA) — RHYTHM 13", "SGS", 32, 32, 8, 1, 8, 0x0ULL, RB_SGS_L12 },
    { "TABLE 1 (M252 AA) — RHYTHM 14", "SGS", 32, 32, 8, 1, 8, 0x0ULL, RB_SGS_L13 },
    { "TABLE 1 (M252 AA) — RHYTHM 15", "SGS", 32, 32, 8, 1, 8, 0x0ULL, RB_SGS_L14 },
    { "TABLE 2 (M252 AD) — RHYTHM 1 (WALTZ)", "SGS", 23, 23, 8, 1, 8, 0x0ULL, RB_SGS_L15 },
    { "TABLE 2 (M252 AD) — RHYTHM 2 (TANGO)", "SGS", 32, 32, 8, 1, 8, 0x0ULL, RB_SGS_L16 },
    { "TABLE 2 (M252 AD) — RHYTHM 3 (MARCH)", "SGS", 32, 32, 8, 1, 8, 0x0ULL, RB_SGS_L17 },
    { "TABLE 2 (M252 AD) — RHYTHM 4 (SWING)", "SGS", 32, 32, 8, 1, 8, 0x0ULL, RB_SGS_L18 },
    { "TABLE 2 (M252 AD) — RHYTHM 5 (MAMBO)", "SGS", 32, 32, 8, 1, 8, 0x0ULL, RB_SGS_L19 },
    { "TABLE 2 (M252 AD) — RHYTHM 6 (SLOW ROCK)", "SGS", 24, 24, 8, 1, 8, 0x0ULL, RB_SGS_L20 },
    { "TABLE 2 (M252 AD) — RHYTHM 7 (BEAT)", "SGS", 32, 32, 8, 1, 8, 0x0ULL, RB_SGS_L21 },
    { "TABLE 2 (M252 AD) — RHYTHM 8 (SAMBA)", "SGS", 32, 32, 8, 1, 8, 0x0ULL, RB_SGS_L22 },
    { "TABLE 2 (M252 AD) — RHYTHM 9 (BOSSA NOVA)", "SGS", 32, 32, 8, 1, 8, 0x0ULL, RB_SGS_L23 },
    { "TABLE 2 (M252 AD) — RHYTHM 10 (CHA-CHA)", "SGS", 32, 32, 8, 1, 8, 0x0ULL, RB_SGS_L24 },
    { "TABLE 2 (M252 AD) — RHYTHM 11 (RUMBA)", "SGS", 32, 32, 8, 1, 8, 0x0ULL, RB_SGS_L25 },
    { "TABLE 2 (M252 AD) — RHYTHM 12 (BEGUINE)", "SGS", 32, 32, 8, 1, 8, 0x0ULL, RB_SGS_L26 },
    { "TABLE 2 (M252 AD) — RHYTHM 13 (BAJON)", "SGS", 32, 32, 8, 1, 8, 0x0ULL, RB_SGS_L27 },
    { "TABLE 2 (M252 AD) — RHYTHM 14 (FOX TROT)", "SGS", 32, 32, 8, 1, 8, 0x0ULL, RB_SGS_L28 },
    { "TABLE 2 (M252 AD) — RHYTHM 15 (SHUFFLE)", "SGS", 24, 24, 8, 1, 8, 0x0ULL, RB_SGS_L29 },
};
#define RB_SGS_N 30

// ── reading a rhythm ──────────────────────────────────────────────────────
static inline int rb_hit(const RbRhythm *r, int lane, int count) {
    return (int)((r->lane[lane].mask >> (count % r->counts)) & 1ULL);
}
static inline int rb_uncertain(const RbRhythm *r, int lane, int count) {
    return (int)((r->lane[lane].maybe >> (count % r->counts)) & 1ULL);
}
static inline int rb_used(const RbRhythm *r, int count) {   // false = a skipped count
    return (int)(((~r->unused) >> (count % r->counts)) & 1ULL);
}
static inline int rb_beat_of(const RbRhythm *r, int count) {
    return (count % r->per_bar) / (r->per_beat ? r->per_beat : 1);
}

#endif // RHYTHMBOX_H
