/* sound_ctx.h — GENERATED by tools/ctx-gen.js. Do not edit by hand.
 *
 * The per-instance engine context (docs/design/engine-context.md). An AUv3 puts every plug-in
 * instance in ONE process, so state that lives in file-scope statics is shared by every
 * instance — which is why two DAW tracks fight over one rack. These members used to be those
 * statics; the macro block at the bottom means the DSP code reads exactly as it did before.
 *
 * The default instance below is a `static` with DESIGNATED INITIALISERS, so every value is
 * still set at compile time exactly as it was, and the rest is still zeroed static storage.
 * That is what makes this a pure move with no init-order risk: nothing can read a member
 * before it is set, because the linker sets it. A real per-instance context is then created
 * by copying this template, which is exact by construction.
 */
#ifndef DE_SOUND_CTX_H
#define DE_SOUND_CTX_H

/* self-contained: the members use these, and depending on where this header lands in
 * sound.h they may not have been pulled in yet. */
#include <stdint.h>
#include <stdbool.h>
#include <stdatomic.h>

/* MOVED here from sound.h: the sizes and constants the members below are written in.
 * They have to precede the struct, and moving a #define earlier is always safe because a
 * macro body is only text until it is expanded. */
#define SOUND_SAMPLE_RATE  44100
#define SOUND_VOICES       32   // polyphony (8→16→32; needs SOUND_HANDLE_BITS≥5). ~9-10KB/voice .bss; CPU is the real cost (every active voice runs per-sample) — long-ringing modal/Karplus engines + chords starved 16
#define SOUND_HANDLE_BITS 5                      // slot field width — must hold SOUND_VOICES-1 (32 voices → 0..31 → 5 bits)
#define SCOPE_LEN 2048
#define SOUND_USER_WAVES 4
#define SOUND_WAVE_LEN   64
#define SOUND_ECHO_MAX (SOUND_SAMPLE_RATE * 2)   // 2s cap on the delay line
#define SPRING_DISP    0.62f         // default dispersion coefficient (the "boing" character)
#define SOUND_REVERB_TANKS 3
#define SOUND_FX_BUSES   8         // bus 0 master + 7 aux (per-instrument). ~82KB of buffers total
#define CHORUS_BUF_LEN   2048      // ~46ms @44100 Hz
#define FLANGER_BUF_LEN   512        // ~11ms @44100 Hz
#define TAPE_BUF_LEN     1024
#define TAPE_INST 2                        // Increment F: tape instances per bus (LO-FI vs standalone TAPE) — each carries its own buffer (~32KB/bus total)
#define CRUSH_INST 2                       // Increment F: crush instances per bus (LO-FI vs standalone BITCRUSH)
#define DRIVE_INST 2                        // Increment F: bus-drive instances (a 2nd drive in the chain — overdrive pedal INTO amp drive)
#define FILT_INST 2                         // Increment F: filter instances per bus (filter A/B; LO-FI vs standalone)
#define EQ_INST 2                         // Increment F: EQ instances per bus (EQ before AND after a dirt stage)
#define SOUND_PHASER_STAGES 8
#define LESLIE_BUF        512        // ~11.6ms horn Doppler delay line (navkit LESLIE_BUFFER_SIZE)
#define N_SC_KEYS 4   // independent trigger buses (kick/snare/…); sidechain_key key index 0..3
#define VOC_BANDS 12
#define AM_RING 8192
enum { AM_SNAP, AM_SHIFT };
#define AM_MAXV 3                     // voices in a stack: the shift itself, + a fifth, + an octave
#define FXMOD_N 7                                   // active targets: studio.h FXMOD_FILTER_CUT(0)..FXMOD_SHIMMER_MIX(6)
#define VARI_BUF (SOUND_SAMPLE_RATE * 2)   // 2 s — room for a long dive before the read laps the write
#define EMIT_DL_LEN  3072      // grain buffer per bus (~70ms @44100), stereo

typedef struct {
    int hn_gen[SOUND_VOICES];
    bool hn_used[SOUND_VOICES];
    int held_voice[SOUND_VOICES];
    float scope_buf[SCOPE_LEN];
    int scope_w;
    bool scope_ever;
    float scope2_bufL[SCOPE_LEN];
    float scope2_bufR[SCOPE_LEN];
    int scope2_w;
    bool scope2_ever;
    float *rec_ring;
    volatile int rec_w;
    volatile long rec_total;
    volatile bool rec_arm;
    float user_wave[SOUND_USER_WAVES][SOUND_WAVE_LEN];
    int bow_body_next;
    int bow_body_overflow;
    float echo_buf[SOUND_ECHO_MAX];
    int echo_widx;
    float echo_time;
    float echo_time_target;
    float echo_fb;
    float echo_tone_coef;
    float echo_lp;
    float echo_dc_x1;
    float echo_dc_y1;
    bool echo_used;
    float echo_ins_buf[SOUND_ECHO_MAX];
    int echo_ins_widx;
    float echo_ins_time;
    float echo_ins_time_target;
    float echo_ins_fb;
    float echo_ins_tone_coef;
    float echo_ins_lp;
    float echo_ins_mix;
    bool echo_ins_used;
    float echo_ins_bbd;
    float echo_ins_tone;
    float echo_ins_wph;
    float echo_ins_fph;
    int g_pan_law;
    float rvb_spring;
    float rvb_spring_disp;
    bool reverb_used;
    int fx_next_bus;
    int8_t bus_tank[SOUND_FX_BUSES];
    int tank_bus[SOUND_REVERB_TANKS];
    int rvb_bus_overflow;
    float cho_buf[SOUND_FX_BUSES][CHORUS_BUF_LEN];
    int cho_widx[SOUND_FX_BUSES];
    float cho_phase[SOUND_FX_BUSES];
    float cho_rate[SOUND_FX_BUSES];
    float cho_depth[SOUND_FX_BUSES];
    float cho_mix[SOUND_FX_BUSES];
    bool cho_used[SOUND_FX_BUSES];
    float flg_buf[SOUND_FX_BUSES][FLANGER_BUF_LEN];
    int flg_widx[SOUND_FX_BUSES];
    float flg_phase[SOUND_FX_BUSES];
    float flg_rate[SOUND_FX_BUSES];
    float flg_depth[SOUND_FX_BUSES];
    float flg_fb[SOUND_FX_BUSES];
    float flg_mix[SOUND_FX_BUSES];
    float flg_dc_x1[SOUND_FX_BUSES];
    float flg_dc_y1[SOUND_FX_BUSES];
    bool flg_used[SOUND_FX_BUSES];
    float tape_bufL[SOUND_FX_BUSES][TAPE_INST][TAPE_BUF_LEN];
    float tape_bufR[SOUND_FX_BUSES][TAPE_INST][TAPE_BUF_LEN];
    int tape_widx[SOUND_FX_BUSES][TAPE_INST];
    float tape_wph[SOUND_FX_BUSES][TAPE_INST];
    float tape_fph[SOUND_FX_BUSES][TAPE_INST];
    float tape_lpL[SOUND_FX_BUSES][TAPE_INST];
    float tape_lpR[SOUND_FX_BUSES][TAPE_INST];
    float tape_wow[SOUND_FX_BUSES][TAPE_INST];
    float tape_flut[SOUND_FX_BUSES][TAPE_INST];
    float tape_sat[SOUND_FX_BUSES][TAPE_INST];
    bool tape_used[SOUND_FX_BUSES][TAPE_INST];
    float crush_bits[SOUND_FX_BUSES][CRUSH_INST];
    float crush_rate[SOUND_FX_BUSES][CRUSH_INST];
    float crush_mix[SOUND_FX_BUSES][CRUSH_INST];
    float crush_holdL[SOUND_FX_BUSES][CRUSH_INST];
    float crush_holdR[SOUND_FX_BUSES][CRUSH_INST];
    int crush_cnt[SOUND_FX_BUSES][CRUSH_INST];
    bool crush_used[SOUND_FX_BUSES][CRUSH_INST];
    float drvins_amt[SOUND_FX_BUSES][DRIVE_INST];
    int drvins_mode[SOUND_FX_BUSES][DRIVE_INST];
    float drvins_mix[SOUND_FX_BUSES][DRIVE_INST];
    bool drvins_used[SOUND_FX_BUSES][DRIVE_INST];
    float drvins_dcx[SOUND_FX_BUSES][DRIVE_INST][2];
    float drvins_dcy[SOUND_FX_BUSES][DRIVE_INST][2];
    int drvins_voice;
    float drvins_tone;
    float drvins_lp1[SOUND_FX_BUSES][DRIVE_INST][2];
    float drvins_lp2[SOUND_FX_BUSES][DRIVE_INST][2];
    float wah_env[SOUND_FX_BUSES];
    float wah_ic1[SOUND_FX_BUSES];
    float wah_ic2[SOUND_FX_BUSES];
    float wah_sens[SOUND_FX_BUSES];
    float wah_res[SOUND_FX_BUSES];
    float wah_mix[SOUND_FX_BUSES];
    bool wah_used[SOUND_FX_BUSES];
    float wah_lfo_rate[SOUND_FX_BUSES];
    float wah_lfo_phase[SOUND_FX_BUSES];
    int filt_mode[SOUND_FX_BUSES][FILT_INST];
    float filt_cut[SOUND_FX_BUSES][FILT_INST];
    float filt_res[SOUND_FX_BUSES][FILT_INST];
    float filt_ic1L[SOUND_FX_BUSES][FILT_INST];
    float filt_ic2L[SOUND_FX_BUSES][FILT_INST];
    float filt_ic1R[SOUND_FX_BUSES][FILT_INST];
    float filt_ic2R[SOUND_FX_BUSES][FILT_INST];
    bool filt_used[SOUND_FX_BUSES][FILT_INST];
    float fmt_freq[SOUND_FX_BUSES][4];
    float fmt_k[SOUND_FX_BUSES][4];
    float fmt_amp[SOUND_FX_BUSES][4];
    float fmt_ic1[SOUND_FX_BUSES][4];
    float fmt_ic2[SOUND_FX_BUSES][4];
    float fmt_mix[SOUND_FX_BUSES];
    bool fmt_used[SOUND_FX_BUSES];
    float eq_low_g[SOUND_FX_BUSES][EQ_INST];
    float eq_mid_g[SOUND_FX_BUSES][EQ_INST];
    float eq_high_g[SOUND_FX_BUSES][EQ_INST];
    float eq_loL[SOUND_FX_BUSES][EQ_INST];
    float eq_loR[SOUND_FX_BUSES][EQ_INST];
    float eq_hiL[SOUND_FX_BUSES][EQ_INST];
    float eq_hiR[SOUND_FX_BUSES][EQ_INST];
    bool eq_used[SOUND_FX_BUSES][EQ_INST];
    float trem_rate[SOUND_FX_BUSES];
    float trem_depth[SOUND_FX_BUSES];
    int trem_shape[SOUND_FX_BUSES];
    float trem_phase[SOUND_FX_BUSES];
    bool trem_used[SOUND_FX_BUSES];
    float pan_rate[SOUND_FX_BUSES];
    float pan_depth[SOUND_FX_BUSES];
    int pan_shape[SOUND_FX_BUSES];
    float pan_phase[SOUND_FX_BUSES];
    bool pan_used[SOUND_FX_BUSES];
    float rm_freq[SOUND_FX_BUSES];
    float rm_mix[SOUND_FX_BUSES];
    float rm_phase[SOUND_FX_BUSES];
    bool rm_used[SOUND_FX_BUSES];
    float phaser_rate[SOUND_FX_BUSES];
    float phaser_depth[SOUND_FX_BUSES];
    float phaser_fb[SOUND_FX_BUSES];
    float phaser_mix[SOUND_FX_BUSES];
    int phaser_stages[SOUND_FX_BUSES];
    float phaser_phase[SOUND_FX_BUSES];
    float phaser_stL[SOUND_FX_BUSES][SOUND_PHASER_STAGES];
    float phaser_pvL[SOUND_FX_BUSES][SOUND_PHASER_STAGES];
    float phaser_stR[SOUND_FX_BUSES][SOUND_PHASER_STAGES];
    float phaser_pvR[SOUND_FX_BUSES][SOUND_PHASER_STAGES];
    float phaser_dcx[SOUND_FX_BUSES][2];
    float phaser_dcy[SOUND_FX_BUSES][2];
    bool phaser_used[SOUND_FX_BUSES];
    bool phaser_optical[SOUND_FX_BUSES];
    int leslie_speed[SOUND_FX_BUSES];
    float leslie_drive[SOUND_FX_BUSES];
    float leslie_bal[SOUND_FX_BUSES];
    float leslie_dopp[SOUND_FX_BUSES];
    float leslie_mix[SOUND_FX_BUSES];
    bool leslie_used[SOUND_FX_BUSES];
    float leslie_hornPh[SOUND_FX_BUSES];
    float leslie_drumPh[SOUND_FX_BUSES];
    float leslie_hornRt[SOUND_FX_BUSES];
    float leslie_drumRt[SOUND_FX_BUSES];
    float leslie_xoL[SOUND_FX_BUSES];
    float leslie_xoR[SOUND_FX_BUSES];
    int leslie_wpos[SOUND_FX_BUSES];
    float leslie_bufL[SOUND_FX_BUSES][LESLIE_BUF];
    float leslie_bufR[SOUND_FX_BUSES][LESLIE_BUF];
    float sc_key_lvl[N_SC_KEYS];
    bool voc_on;
    float voc_mix;
    float voc_mod;
    float voc_f[VOC_BANDS];
    float voc_q1;
    float voc_mk;
    float voc_c_lp[VOC_BANDS];
    float voc_c_bp[VOC_BANDS];
    float voc_m_lp[VOC_BANDS];
    float voc_m_bp[VOC_BANDS];
    float voc_env[VOC_BANDS];
    float voc_uv_amt;
    float voc_uv;
    int voc_nz;
    float voc_nk;
    float voc_n_lp[VOC_BANDS];
    float voc_n_bp[VOC_BANDS];
    int extin_mon_on;
    float extin_mon_gain;
    float voc_mic_amt;
    float am_inbuf[AM_RING];
    float am_outbuf[AM_RING];
    float am_nrm[AM_RING];
    long am_w;
    float am_T;
    long am_ea;
    long am_eps[8];
    int am_epi;
    int am_pd;
    float am_amt;
    int am_on;
    int am_root;
    int am_scale;
    long am_ts[AM_MAXV];
    int am_mode;
    int am_nv;
    float am_semis;
    float am_gain;
    int8_t grain_tank_of[SOUND_FX_BUSES];
    int grain_next;
    int grain_overflow;
    float drop_env;
    float drop_prev;
    float drop_lpL;
    float drop_lpR;
    float noise_hiss;
    float noise_hum;
    int noise_mains;
    bool noise_used;
    unsigned int noise_seed;
    float noise_lpL;
    float noise_lpR;
    float noise_hum_ph;
    int8_t shim_bus_of[SOUND_FX_BUSES];
    int shim_next;
    int shim_overflow;
    bool fxmod_any;
    bool fxmod_on[SOUND_FX_BUSES][FXMOD_N];
    bool fxmod_prime[SOUND_FX_BUSES][FXMOD_N];
    float fxmod_cur[SOUND_FX_BUSES][FXMOD_N];
    float fxmod_tgt[SOUND_FX_BUSES][FXMOD_N];
    float fxlfo_rate[SOUND_FX_BUSES][FXMOD_N];
    float fxlfo_depth[SOUND_FX_BUSES][FXMOD_N];
    float fxlfo_ctr[SOUND_FX_BUSES][FXMOD_N];
    float fxlfo_phase[SOUND_FX_BUSES][FXMOD_N];
    int fxlfo_shape[SOUND_FX_BUSES][FXMOD_N];
    float vari_bufL[VARI_BUF];
    float vari_bufR[VARI_BUF];
    int vari_wpos;
    float vari_rpos;
    float vari_target;
    float vari_speed;
    bool vari_used;
    bool vari_ever;
    float steal_tailL;
    float steal_tailR;
    float g_listener_x;
    float g_listener_y;
    float g_listener_vx;
    float g_listener_vy;
    float g_spatial_ref;
    float g_spatial_max;
    float g_spatial_rolloff;
    float g_spatial_c;
    bool emit_on[SOUND_FX_BUSES];
    float emit_x[SOUND_FX_BUSES];
    float emit_y[SOUND_FX_BUSES];
    float emit_vx[SOUND_FX_BUSES];
    float emit_vy[SOUND_FX_BUSES];
    float emit_gain[SOUND_FX_BUSES];
    float emit_gain_t[SOUND_FX_BUSES];
    float emit_pan[SOUND_FX_BUSES];
    float emit_pan_t[SOUND_FX_BUSES];
    float emit_dopp[SOUND_FX_BUSES];
    float emit_dopp_t[SOUND_FX_BUSES];
    float emit_bufL[SOUND_FX_BUSES][EMIT_DL_LEN];
    float emit_bufR[SOUND_FX_BUSES][EMIT_DL_LEN];
    int emit_wpos[SOUND_FX_BUSES];
    float emit_ph[SOUND_FX_BUSES];
    int fx_bus_overflow;
} DeSound;

/* the compile-time defaults — one line per static that carried a non-zero initialiser */
static DeSound de_snd_default = {
    .echo_time = 0.375f * SOUND_SAMPLE_RATE,
    .echo_time_target = 0.375f * SOUND_SAMPLE_RATE,
    .echo_fb = 0.35f,
    .echo_ins_time = 0.375f * SOUND_SAMPLE_RATE,
    .echo_ins_time_target = 0.375f * SOUND_SAMPLE_RATE,
    .echo_ins_fb = 0.35f,
    .echo_ins_tone = 0.55f,
    .g_pan_law = PAN_LINEAR,
    .rvb_spring_disp = SPRING_DISP,
    .fx_next_bus = 1,
    .drvins_tone = 0.5f,
    .voc_q1 = 0.2f,
    .voc_mk = 1.2f,
    .voc_nz = 0x1a2b3c4d,
    .voc_nk = 2.6f,
    .am_T = 300.0f,
    .am_scale = 1,
    .am_mode = AM_SNAP,
    .am_nv = 1,
    .am_gain = 1.0f,
    .noise_mains = 60,
    .noise_seed = 0x6D2B79F5u,
    .shim_next = 1,
    .vari_target = 1.0f,
    .vari_speed = 1.0f,
    .g_spatial_ref = 24.0f,
    .g_spatial_max = 400.0f,
    .g_spatial_rolloff = 1.0f,
    .g_spatial_c = 340.0f,
};
static DeSound *de_snd = &de_snd_default;

/* the access block: every name the engine already uses, pointed at the context.
 * Step B swaps de_snd for a per-instance pointer; NOTHING below this line changes. */
#define hn_gen               (de_snd->hn_gen)
#define hn_used              (de_snd->hn_used)
#define held_voice           (de_snd->held_voice)
#define scope_buf            (de_snd->scope_buf)
#define scope_w              (de_snd->scope_w)
#define scope_ever           (de_snd->scope_ever)
#define scope2_bufL          (de_snd->scope2_bufL)
#define scope2_bufR          (de_snd->scope2_bufR)
#define scope2_w             (de_snd->scope2_w)
#define scope2_ever          (de_snd->scope2_ever)
#define rec_ring             (de_snd->rec_ring)
#define rec_w                (de_snd->rec_w)
#define rec_total            (de_snd->rec_total)
#define rec_arm              (de_snd->rec_arm)
#define user_wave            (de_snd->user_wave)
#define bow_body_next        (de_snd->bow_body_next)
#define bow_body_overflow    (de_snd->bow_body_overflow)
#define echo_buf             (de_snd->echo_buf)
#define echo_widx            (de_snd->echo_widx)
#define echo_time            (de_snd->echo_time)
#define echo_time_target     (de_snd->echo_time_target)
#define echo_fb              (de_snd->echo_fb)
#define echo_tone_coef       (de_snd->echo_tone_coef)
#define echo_lp              (de_snd->echo_lp)
#define echo_dc_x1           (de_snd->echo_dc_x1)
#define echo_dc_y1           (de_snd->echo_dc_y1)
#define echo_used            (de_snd->echo_used)
#define echo_ins_buf         (de_snd->echo_ins_buf)
#define echo_ins_widx        (de_snd->echo_ins_widx)
#define echo_ins_time        (de_snd->echo_ins_time)
#define echo_ins_time_target (de_snd->echo_ins_time_target)
#define echo_ins_fb          (de_snd->echo_ins_fb)
#define echo_ins_tone_coef   (de_snd->echo_ins_tone_coef)
#define echo_ins_lp          (de_snd->echo_ins_lp)
#define echo_ins_mix         (de_snd->echo_ins_mix)
#define echo_ins_used        (de_snd->echo_ins_used)
#define echo_ins_bbd         (de_snd->echo_ins_bbd)
#define echo_ins_tone        (de_snd->echo_ins_tone)
#define echo_ins_wph         (de_snd->echo_ins_wph)
#define echo_ins_fph         (de_snd->echo_ins_fph)
#define g_pan_law            (de_snd->g_pan_law)
#define rvb_spring           (de_snd->rvb_spring)
#define rvb_spring_disp      (de_snd->rvb_spring_disp)
#define reverb_used          (de_snd->reverb_used)
#define fx_next_bus          (de_snd->fx_next_bus)
#define bus_tank             (de_snd->bus_tank)
#define tank_bus             (de_snd->tank_bus)
#define rvb_bus_overflow     (de_snd->rvb_bus_overflow)
#define cho_buf              (de_snd->cho_buf)
#define cho_widx             (de_snd->cho_widx)
#define cho_phase            (de_snd->cho_phase)
#define cho_rate             (de_snd->cho_rate)
#define cho_depth            (de_snd->cho_depth)
#define cho_mix              (de_snd->cho_mix)
#define cho_used             (de_snd->cho_used)
#define flg_buf              (de_snd->flg_buf)
#define flg_widx             (de_snd->flg_widx)
#define flg_phase            (de_snd->flg_phase)
#define flg_rate             (de_snd->flg_rate)
#define flg_depth            (de_snd->flg_depth)
#define flg_fb               (de_snd->flg_fb)
#define flg_mix              (de_snd->flg_mix)
#define flg_dc_x1            (de_snd->flg_dc_x1)
#define flg_dc_y1            (de_snd->flg_dc_y1)
#define flg_used             (de_snd->flg_used)
#define tape_bufL            (de_snd->tape_bufL)
#define tape_bufR            (de_snd->tape_bufR)
#define tape_widx            (de_snd->tape_widx)
#define tape_wph             (de_snd->tape_wph)
#define tape_fph             (de_snd->tape_fph)
#define tape_lpL             (de_snd->tape_lpL)
#define tape_lpR             (de_snd->tape_lpR)
#define tape_wow             (de_snd->tape_wow)
#define tape_flut            (de_snd->tape_flut)
#define tape_sat             (de_snd->tape_sat)
#define tape_used            (de_snd->tape_used)
#define crush_bits           (de_snd->crush_bits)
#define crush_rate           (de_snd->crush_rate)
#define crush_mix            (de_snd->crush_mix)
#define crush_holdL          (de_snd->crush_holdL)
#define crush_holdR          (de_snd->crush_holdR)
#define crush_cnt            (de_snd->crush_cnt)
#define crush_used           (de_snd->crush_used)
#define drvins_amt           (de_snd->drvins_amt)
#define drvins_mode          (de_snd->drvins_mode)
#define drvins_mix           (de_snd->drvins_mix)
#define drvins_used          (de_snd->drvins_used)
#define drvins_dcx           (de_snd->drvins_dcx)
#define drvins_dcy           (de_snd->drvins_dcy)
#define drvins_voice         (de_snd->drvins_voice)
#define drvins_tone          (de_snd->drvins_tone)
#define drvins_lp1           (de_snd->drvins_lp1)
#define drvins_lp2           (de_snd->drvins_lp2)
#define wah_env              (de_snd->wah_env)
#define wah_ic1              (de_snd->wah_ic1)
#define wah_ic2              (de_snd->wah_ic2)
#define wah_sens             (de_snd->wah_sens)
#define wah_res              (de_snd->wah_res)
#define wah_mix              (de_snd->wah_mix)
#define wah_used             (de_snd->wah_used)
#define wah_lfo_rate         (de_snd->wah_lfo_rate)
#define wah_lfo_phase        (de_snd->wah_lfo_phase)
#define filt_mode            (de_snd->filt_mode)
#define filt_cut             (de_snd->filt_cut)
#define filt_res             (de_snd->filt_res)
#define filt_ic1L            (de_snd->filt_ic1L)
#define filt_ic2L            (de_snd->filt_ic2L)
#define filt_ic1R            (de_snd->filt_ic1R)
#define filt_ic2R            (de_snd->filt_ic2R)
#define filt_used            (de_snd->filt_used)
#define fmt_freq             (de_snd->fmt_freq)
#define fmt_k                (de_snd->fmt_k)
#define fmt_amp              (de_snd->fmt_amp)
#define fmt_ic1              (de_snd->fmt_ic1)
#define fmt_ic2              (de_snd->fmt_ic2)
#define fmt_mix              (de_snd->fmt_mix)
#define fmt_used             (de_snd->fmt_used)
#define eq_low_g             (de_snd->eq_low_g)
#define eq_mid_g             (de_snd->eq_mid_g)
#define eq_high_g            (de_snd->eq_high_g)
#define eq_loL               (de_snd->eq_loL)
#define eq_loR               (de_snd->eq_loR)
#define eq_hiL               (de_snd->eq_hiL)
#define eq_hiR               (de_snd->eq_hiR)
#define eq_used              (de_snd->eq_used)
#define trem_rate            (de_snd->trem_rate)
#define trem_depth           (de_snd->trem_depth)
#define trem_shape           (de_snd->trem_shape)
#define trem_phase           (de_snd->trem_phase)
#define trem_used            (de_snd->trem_used)
#define pan_rate             (de_snd->pan_rate)
#define pan_depth            (de_snd->pan_depth)
#define pan_shape            (de_snd->pan_shape)
#define pan_phase            (de_snd->pan_phase)
#define pan_used             (de_snd->pan_used)
#define rm_freq              (de_snd->rm_freq)
#define rm_mix               (de_snd->rm_mix)
#define rm_phase             (de_snd->rm_phase)
#define rm_used              (de_snd->rm_used)
#define phaser_rate          (de_snd->phaser_rate)
#define phaser_depth         (de_snd->phaser_depth)
#define phaser_fb            (de_snd->phaser_fb)
#define phaser_mix           (de_snd->phaser_mix)
#define phaser_stages        (de_snd->phaser_stages)
#define phaser_phase         (de_snd->phaser_phase)
#define phaser_stL           (de_snd->phaser_stL)
#define phaser_pvL           (de_snd->phaser_pvL)
#define phaser_stR           (de_snd->phaser_stR)
#define phaser_pvR           (de_snd->phaser_pvR)
#define phaser_dcx           (de_snd->phaser_dcx)
#define phaser_dcy           (de_snd->phaser_dcy)
#define phaser_used          (de_snd->phaser_used)
#define phaser_optical       (de_snd->phaser_optical)
#define leslie_speed         (de_snd->leslie_speed)
#define leslie_drive         (de_snd->leslie_drive)
#define leslie_bal           (de_snd->leslie_bal)
#define leslie_dopp          (de_snd->leslie_dopp)
#define leslie_mix           (de_snd->leslie_mix)
#define leslie_used          (de_snd->leslie_used)
#define leslie_hornPh        (de_snd->leslie_hornPh)
#define leslie_drumPh        (de_snd->leslie_drumPh)
#define leslie_hornRt        (de_snd->leslie_hornRt)
#define leslie_drumRt        (de_snd->leslie_drumRt)
#define leslie_xoL           (de_snd->leslie_xoL)
#define leslie_xoR           (de_snd->leslie_xoR)
#define leslie_wpos          (de_snd->leslie_wpos)
#define leslie_bufL          (de_snd->leslie_bufL)
#define leslie_bufR          (de_snd->leslie_bufR)
#define sc_key_lvl           (de_snd->sc_key_lvl)
#define voc_on               (de_snd->voc_on)
#define voc_mix              (de_snd->voc_mix)
#define voc_mod              (de_snd->voc_mod)
#define voc_f                (de_snd->voc_f)
#define voc_q1               (de_snd->voc_q1)
#define voc_mk               (de_snd->voc_mk)
#define voc_c_lp             (de_snd->voc_c_lp)
#define voc_c_bp             (de_snd->voc_c_bp)
#define voc_m_lp             (de_snd->voc_m_lp)
#define voc_m_bp             (de_snd->voc_m_bp)
#define voc_env              (de_snd->voc_env)
#define voc_uv_amt           (de_snd->voc_uv_amt)
#define voc_uv               (de_snd->voc_uv)
#define voc_nz               (de_snd->voc_nz)
#define voc_nk               (de_snd->voc_nk)
#define voc_n_lp             (de_snd->voc_n_lp)
#define voc_n_bp             (de_snd->voc_n_bp)
#define extin_mon_on         (de_snd->extin_mon_on)
#define extin_mon_gain       (de_snd->extin_mon_gain)
#define voc_mic_amt          (de_snd->voc_mic_amt)
#define am_inbuf             (de_snd->am_inbuf)
#define am_outbuf            (de_snd->am_outbuf)
#define am_nrm               (de_snd->am_nrm)
#define am_w                 (de_snd->am_w)
#define am_T                 (de_snd->am_T)
#define am_ea                (de_snd->am_ea)
#define am_eps               (de_snd->am_eps)
#define am_epi               (de_snd->am_epi)
#define am_pd                (de_snd->am_pd)
#define am_amt               (de_snd->am_amt)
#define am_on                (de_snd->am_on)
#define am_root              (de_snd->am_root)
#define am_scale             (de_snd->am_scale)
#define am_ts                (de_snd->am_ts)
#define am_mode              (de_snd->am_mode)
#define am_nv                (de_snd->am_nv)
#define am_semis             (de_snd->am_semis)
#define am_gain              (de_snd->am_gain)
#define grain_tank_of        (de_snd->grain_tank_of)
#define grain_next           (de_snd->grain_next)
#define grain_overflow       (de_snd->grain_overflow)
#define drop_env             (de_snd->drop_env)
#define drop_prev            (de_snd->drop_prev)
#define drop_lpL             (de_snd->drop_lpL)
#define drop_lpR             (de_snd->drop_lpR)
#define noise_hiss           (de_snd->noise_hiss)
#define noise_hum            (de_snd->noise_hum)
#define noise_mains          (de_snd->noise_mains)
#define noise_used           (de_snd->noise_used)
#define noise_seed           (de_snd->noise_seed)
#define noise_lpL            (de_snd->noise_lpL)
#define noise_lpR            (de_snd->noise_lpR)
#define noise_hum_ph         (de_snd->noise_hum_ph)
#define shim_bus_of          (de_snd->shim_bus_of)
#define shim_next            (de_snd->shim_next)
#define shim_overflow        (de_snd->shim_overflow)
#define fxmod_any            (de_snd->fxmod_any)
#define fxmod_on             (de_snd->fxmod_on)
#define fxmod_prime          (de_snd->fxmod_prime)
#define fxmod_cur            (de_snd->fxmod_cur)
#define fxmod_tgt            (de_snd->fxmod_tgt)
#define fxlfo_rate           (de_snd->fxlfo_rate)
#define fxlfo_depth          (de_snd->fxlfo_depth)
#define fxlfo_ctr            (de_snd->fxlfo_ctr)
#define fxlfo_phase          (de_snd->fxlfo_phase)
#define fxlfo_shape          (de_snd->fxlfo_shape)
#define vari_bufL            (de_snd->vari_bufL)
#define vari_bufR            (de_snd->vari_bufR)
#define vari_wpos            (de_snd->vari_wpos)
#define vari_rpos            (de_snd->vari_rpos)
#define vari_target          (de_snd->vari_target)
#define vari_speed           (de_snd->vari_speed)
#define vari_used            (de_snd->vari_used)
#define vari_ever            (de_snd->vari_ever)
#define steal_tailL          (de_snd->steal_tailL)
#define steal_tailR          (de_snd->steal_tailR)
#define g_listener_x         (de_snd->g_listener_x)
#define g_listener_y         (de_snd->g_listener_y)
#define g_listener_vx        (de_snd->g_listener_vx)
#define g_listener_vy        (de_snd->g_listener_vy)
#define g_spatial_ref        (de_snd->g_spatial_ref)
#define g_spatial_max        (de_snd->g_spatial_max)
#define g_spatial_rolloff    (de_snd->g_spatial_rolloff)
#define g_spatial_c          (de_snd->g_spatial_c)
#define emit_on              (de_snd->emit_on)
#define emit_x               (de_snd->emit_x)
#define emit_y               (de_snd->emit_y)
#define emit_vx              (de_snd->emit_vx)
#define emit_vy              (de_snd->emit_vy)
#define emit_gain            (de_snd->emit_gain)
#define emit_gain_t          (de_snd->emit_gain_t)
#define emit_pan             (de_snd->emit_pan)
#define emit_pan_t           (de_snd->emit_pan_t)
#define emit_dopp            (de_snd->emit_dopp)
#define emit_dopp_t          (de_snd->emit_dopp_t)
#define emit_bufL            (de_snd->emit_bufL)
#define emit_bufR            (de_snd->emit_bufR)
#define emit_wpos            (de_snd->emit_wpos)
#define emit_ph              (de_snd->emit_ph)
#define fx_bus_overflow      (de_snd->fx_bus_overflow)

#endif
