/* sound_ctx.h — GENERATED by tools/ctx-gen.js. Do not edit by hand.
 *
 * The per-instance engine context (docs/design/engine-context.md). An AUv3 puts every plug-in
 * instance in ONE process, so state that lives in file-scope statics is shared by every
 * instance — which is why two DAW tracks fight over one rack. These members used to be those
 * statics; the macro block at the bottom means the DSP code reads exactly as it did before.
 *
 * The default instance below is a `static` with DESIGNATED INITIALISERS, so every value is
 * still set at compile time exactly as it was, and the rest is still zeroed static storage.
 * That is what makes this a pure move with no init-order risk: nothing can read a member
 * before it is set, because the linker sets it. A real per-instance context is then created
 * by copying this template, which is exact by construction.
 */
#ifndef DE_SOUND_CTX_H
#define DE_SOUND_CTX_H

/* self-contained: the members use these, and depending on where this header lands in
 * sound.h they may not have been pulled in yet. */
#include <stdint.h>
#include <stdbool.h>
#include <stdatomic.h>

/* MOVED here from sound.h: the sizes and constants the members below are written in.
 * They have to precede the struct, and moving a #define earlier is always safe because a
 * macro body is only text until it is expanded. */
#define SOUND_SAMPLE_RATE  44100
#define SOUND_VOICES       32   // polyphony (8→16→32; needs SOUND_HANDLE_BITS≥5). ~9-10KB/voice .bss; CPU is the real cost (every active voice runs per-sample) — long-ringing modal/Karplus engines + chords starved 16
#define SOUND_SFX_STEPS    32
#define SOUND_SFX_SLOTS    32
#define SOUND_INSTR_SLOTS  48   // 0-4 = the raw waves; 5-47 cart-defined (rich patch carts like modrack want banks per wave + many macro engines). ~200B/slot
#define SOUND_KS_MAX       1024   // Karplus-Strong delay line cap (~4KB/voice) — bottoms out around 43Hz / MIDI 29
#define ORGAN_SCAN         64     // INSTR_ORGAN scanner-chorus delay taps (~1.5ms; borrows ks_buf's head — organ never uses the Karplus path)
#define SOUND_BOW_BODIES   8      // pool size — a string-quartet cart wants 4 (2 violins/viola/cello); ~9KB each
#define BOW_BODY_MAX       768    // longest line, in samples: DOUBLE BASS 16.67ms = 736 @ 44.1k, + headroom.
typedef struct {
    uint8_t pitch;   // MIDI note (0 = silent)
    uint8_t instr;   // waveform id
    uint8_t vol;     // 0..7
} SfxStep;
typedef struct {
    SfxStep steps[SOUND_SFX_STEPS];
    uint8_t step_dur;   // 10ms units (e.g. 6 = 60ms per step)
    uint8_t length;     // 1..32
    uint8_t loop;       // 1 = repeat when SFX ends
} Sfx;
typedef struct { unsigned int seed; float val, target, phase; } ModState;
typedef struct {
    int   wave;
    int   a_samp, d_samp, r_samp;   // attack / decay / release, in samples
    float sustain;                  // 0..1
    float duty;                     // 0..1 pulse width (only used by INSTR_SQUARE)
    float eng_p[7];                 // EXPERIMENTAL guitar/piano tuning: 0 = fundamental weight, 1 = attack click, 2 = piano double-decay scale, 3 = piano hammer-knock scale, 4 = piano stretched-tuning scale, 5 = piano stiff-string inharmonicity scale
    int   lfo_dest[3];              // LFO_PITCH / LFO_DUTY / LFO_VOLUME / LFO_CUTOFF, per LFO
    float lfo_rate[3];              // Hz
    float lfo_depth[3];             // 0 = off; units depend on dest
    int   lfo_shape[3];             // LFO_SHAPE_* per LFO (default SINE); set by lfo_shape(), copied to new voices
    int   flt_mode;                 // FILTER_OFF / LOW / HIGH / BAND / NOTCH
    float flt_cutoff;               // Hz — the cutoff AT THE REFERENCE PITCH when flt_keytrack != 0
    float flt_keytrack;             // KEYBOARD TRACKING, octaves of cutoff per octave of pitch (audit §B2).
                                    // 0 = absolute Hz (the shipped behaviour, and the default) · 1 = true
                                    // 1V/oct, which is what lets a self-oscillating filter be PLAYED.
    float flt_q;                    // damping coefficient (1/Q); small = resonant
    int   env_dest[3];              // ENV_CUTOFF / ENV_PITCH / ENV_DUTY, per mod-envelope
    int   env_a_samp[3];            // attack, in samples
    int   env_d_samp[3];            // decay, in samples
    float env_amount[3];            // 0 = off; bipolar; units depend on dest (Hz / semitones / 0..1)
    int   flw_dest;                 // envelope FOLLOWER dest (LFO_CUTOFF/VOLUME/PITCH) — the 3rd mod source
    float flw_atk, flw_rel;         // per-sample smoothing coeffs (from attack/release ms)
    float flw_amount;               // 0 = off; Hz for cutoff, 0..1 for volume(duck), semitones for pitch
    float harmonics, timbre, morph; // engine macros 0..1 (INSTR_PLUCK+) — meaning is per-engine; default 0.5
    float drive;                    // post-filter saturation 0..1; 0 = clean bypass (default — old carts unchanged)
    int   drive_mode;               // waveshaper flavour DRIVE_SOFT(0)/HARD/FOLD/ASYM; 0 = tanh (default — old carts unchanged)
    int   bandlimit;                // 0 = raw naive saw (default — old carts byte-identical); 1 = PolyBLEP anti-aliased saw
    float sync_ratio;               // oscillator hard sync: slave:master freq ratio (0 = off, default — old carts unchanged)
    float echo;                     // send to THE echo bus 0..1; 0 = dry (default — old carts unchanged)
    float reverb;                   // reverb send 0..1; 0 = dry (default — old carts unchanged). Target = rvb_tank below
    int   rvb_tank;                 // which reverb tank the send feeds: -1 = the master send (default), 1.. = a reverb_bus() send-bus
    int   sc_key;                   // sidechain trigger key this slot feeds (0..3), via sidechain_key()
    float sc_send;                  // how much this slot drives that key 0..1; 0 = not a trigger (default)
    float voc_send;                 // how much this slot feeds the vocoder MODULATOR 0..1; >0 = send-only (dry muted). vocoder_send()
    int   fx_bus;                   // insert bus for chorus/flanger: 0 = master (default), 1.. = a private aux bus (instrument_chorus/flanger)
    int   bow_body;                 // INSTR_BOWED shared body: 0 = unclaimed, 1.. = bow_bodies[] index+1 (same "0 = none" convention as fx_bus)
    float pan;                      // stereo position -1 L .. 0 center .. +1 R; default 0 = center (linear law, stereo.md)
    float level;                    // per-slot output level (instrument_level); read LIVE at mix. 1.0 = unity/byte-identical bypass, <1 trims — the mixer leg drive/echo/reverb/pan already had
    float tune_mul;                 // slot detune as a freq factor (2^(semis/12)); read LIVE by every
                                    // sounding voice each sample — fire-and-forget hits bend too. default 1
    int   uni_voices;               // UNISON stack: 1 = off (default), 2..7 = N detuned wavetable copies summed (instrument_unison)
    float uni_detune;               // unison spread in semitones (edge voices at ±this); read LIVE per sample like tune_mul. default 0
    uint32_t choke_mask;            // bitmask: bit N set = a new note on this slot kills active voices on slot N
    int   smp_idx;                  // INSTR_SAMPLE: which sound_samples[] slot to play; -1 = none (default). Set by instrument_sample()
    float smp_root;                 // INSTR_SAMPLE: the buffer's root freq (Hz) — the pitch at playback speed 1.0
    float smp_start, smp_end;       // INSTR_SAMPLE: the CHOP — play from start..end as fractions 0..1 (default 0,1 = whole). instrument_sample_region()
    int   smp_mode;                 // INSTR_SAMPLE playback: SAMPLE_NORMAL(0)/REVERSE/LOOP/PINGPONG. instrument_sample_mode()
    int   gl_ms;                    // PORTAMENTO for this patch (instrument_glide): slide time in ms; 0 = no glide (default)
    float gl_scale;                 // GLIDE SCALE amount (instrument_glide_scale): 0 = constant time (default), 1 = per octave
    int   trig;                     // TRIGGER POLICY (instrument_trigger), audit §L4: TRIG_MULTI (0, default —
                                    // every note gets its onset transient) or TRIG_SINGLE (a note started while
                                    // another key on this slot is still down does NOT). A property the
                                    // INSTRUMENT declares, because the right answer differs per instrument:
                                    // Hammond percussion must be single, a flute's chiff must be multi.
} Instrument;
#define SOUND_UNISON_MAX 7   // JP-8000 Super Saw = 7 detuned voices; the max unison stack per slot
typedef struct { float b0, b1, b2, a1, a2, z1, z2; } SoundBiquad;
typedef struct {
    bool   active;
    int    choke_fade;         // >0 = ramping out over a choke (counts down to 0, then deactivates) — a declick fade, not a hard cut
    int    sfx_idx;            // -1 if standalone note
    int    step;
    int    step_samples;
    int    step_len_samples;   // for a one-shot note this is the GATE length; release runs after it
    float  phase;
    float  freq;
    float  vol;                // 0..1
    int    wave;
    int    noise_state;
    // ADSR + LFO snapshot (one-shot notes only; copied from the instrument at note-on)
    int    a_samp, d_samp, r_samp;
    float  sustain;
    float  duty;
    float  rel_start;          // envelope level at the moment the gate ends (release fades from here)
    int    lfo_dest[3];
    float  lfo_rate[3], lfo_depth[3], lfo_phase[3];
    int    lfo_shape[3];        // LFO_SHAPE_* per LFO (default SINE)
    ModState lfo_mod[3];        // per-LFO state for the stateful shapes (S&H / random); seeded at note-on
    int    env_dest[3];              // mod-envelopes (AD; timer = step_samples, retriggered at note-on)
    int    env_a_samp[3], env_d_samp[3];
    float  env_amount[3];
    int    flw_dest;                 // envelope follower: tracks this voice's own amplitude → dest
    float  flw_atk, flw_rel, flw_amount, flw_amp;   // attack/release coeffs, depth, + the running level
    int    flt_mode;
    float  flt_cutoff, flt_q;
    float  flt_low, flt_band;   // SVF running state
    float  lad_s[4];            // FILTER_LADDER: the 4 ladder-stage integrator states (ZDF)
    // held-note (note_on) state + per-param slew (the live voice glides toward these targets)
    bool   held;                   // sustained note_on voice — infinite gate until note_off
    int    owner_slot, owner_gen;  // which handle owns this voice (for stale-handle rejection)
    float  freq_target, vol_target, cutoff_target, duty_target, flt_q_target;
    // PORTAMENTO as a fixed-duration eased ramp (see sound_glide_start). note_glide(ms) sets gl_ms and
    // ms is the real duration: the ramp lands on the target and stops. gl_e/gl_r advance the ease-out
    // curve incrementally so the per-sample cost is one exp2f, not an expf as well.
    int    gl_ms;                  // note_glide() duration in ms; 0 = the short default declick ramp
    float  gl_scale;               // GLIDE SCALE amount: 0 = constant time, 1 = per octave, ~0.2 = the analog law
    int    gl_pos, gl_len;         // ramp position / length in samples. gl_pos >= gl_len means IDLE
    float  gl_from, gl_d;          // start pitch (log2 Hz) and the signed distance to travel, in octaves
    float  gl_e, gl_r;             // running e^(-SHAPE·t): multiply gl_e by gl_r once per sample
    // engine macros (current + slew target, riding the same machinery as cutoff/duty)
    float  harm, timb, mor;
    float  harm_target, timb_target, mor_target;
    float  drv, drv_target;        // post-filter drive (current + slew target, same machinery)
    float  sync_ph;                // hard-sync SLAVE oscillator phase (reset when v->phase wraps)
    float  sync_ratio, sync_ratio_target;  // oscillator hard sync: slave:master freq ratio (0 = off; current + slew target)
    int    uni_voices;             // UNISON stack size snapshot at note-on (1 = off; 2..SOUND_UNISON_MAX)
    float  uni_norm;               // 1/sqrt(voices) loudness normalize, precomputed at note-on
    float  uni_ph[SOUND_UNISON_MAX - 1];  // phase accumulators for the detuned copies (copy 0 = v->phase, the center)
    int    drv_mode;               // waveshaper flavour (DRIVE_*), copied from the instrument at note-on
    int    aa;                     // band-limit the saw (PolyBLEP), copied from the instrument at note-on (0 = raw)
    float  drv_dc_x1, drv_dc_y1;   // DC blocker on the drive output (tanh of an asymmetric wave = DC = a thump)
    float  eko, eko_target;        // echo-bus send (current + slew target, same machinery — note_echo)
    float  rvb, rvb_target;        // reverb-bus send (current + slew target, same machinery — note_reverb)
    int    bus;                    // insert bus for chorus/flanger (snapshot of instr fx_bus at note-on); 0 = master
    int    rvb_bus;                // reverb SEND target bus: 0 = the master parallel send (legacy), 1.. = a reverb_bus() send-bus
    int    sc_key;                 // sidechain trigger key (0..3), snapshot of the instrument at note-on
    float  sc_send;                // how much this voice drives that key 0..1 (0 = not a trigger)
    float  voc_send;               // how much this voice feeds the vocoder modulator (0 = not a modulator; >0 = send-only)
    float  pan, pan_target;        // stereo pan (current + slew target, same machinery — note_pan); -1..1, 0 = center
    int    instr_slot;             // instrument slot this voice was started from (for choke matching)
    float  last_outL, last_outR;   // this voice's previous PANNED contribution per channel — feeds the steal-declick tail
    // spatial audio (spatial.md): world position + velocity → pan/gain/Doppler. sp_on=false →
    // sp_gain=1 & doppler_mul=1 (true bypass), so a non-positioned voice is byte-identical.
    bool   sp_on;                  // positioned in the world (note_pos/hit_at)
    float  sp_x, sp_y, sp_vx, sp_vy;            // world position + velocity (units, units/sec)
    float  sp_gain, sp_gain_target;             // distance attenuation (current + slew target); 1 = bypass
    float  doppler_mul, doppler_target;         // Doppler pitch factor (current + slew target); 1 = bypass
    // Karplus-Strong string state (INSTR_PLUCK): a write head + a FRACTIONAL read tap.
    // Pitch = the tap distance, recomputed every sample from freq*pitch_mul — so vibrato,
    // pitch envelopes, note_pitch and note_glide all bend the string live.
    float  ks_buf[SOUND_KS_MAX];
    int    ks_len, ks_widx;        // ks_len = ALLOCATED length (period*2 headroom for down-bends)
    float  ks_last;                // previous read (the damping average runs across it)
    // modal bar state (INSTR_MALLET): four decaying sine modes, buffer-free. Mode frequencies
    // derive from freq*pitch_mul EVERY sample — the whole pitch machinery bends the bar too.
    float  md_phase[4], md_amp[4]; // per-mode phase + decaying amplitude (the ring lives here)
    float  md_trem_ph;             // vibe motor tremolo phase (morph's top end switches the motor on)
    int    md_strike;              // strike-noise samples remaining (the mallet contact click)
    bool   md_on;                  // struck this note — guards an engine id without a note-on init
    // FM state (INSTR_FM): the carrier rides v->phase (advanced by the mix loop like any
    // wave); only the inaudible modulator needs its own phase + the feedback memory.
    // fm_tph is the DX tine ping (1:1 detent only — see sound_fm_sample).
    float  fm_mph, fm_fb, fm_tph;
    // tonewheel organ state (INSTR_ORGAN): 9 additive drawbar sines (buffer-free), plus a
    // key-click burst, a percussion ping, and the scanner chorus — whose short delay line
    // borrows the head of ks_buf (organ never touches the Karplus path), so it adds no buffer.
    float  org_ph[9];              // per-drawbar phase accumulators
    float  org_click;              // key-click noise-burst envelope (decays ~3ms)
    float  org_perc, org_perc_ph;  // percussion ping envelope + its 2nd-harmonic phase
    float  org_scan_ph;            // scanner LFO phase (6.9Hz, gear-locked to the motor)
    float  org_lp;                 // pre-drive lowpass state — driven organ loses its top (amp/Leslie)
    int    org_widx;               // scanner delay write index into ks_buf[0..ORGAN_SCAN)
    bool   org_on;                 // struck this note — guards an engine id without a note-on init
    // electric-piano state (INSTR_EPIANO): 12 decaying inharmonic sine modes through a pickup
    // nonlinearity + DC blocker, buffer-free (mallet family). Struck/self-decaying like mallet.
    float  ep_ph[12], ep_amp[12], ep_dec[12], ep_ratio[12]; // per-mode phase / amp / decay-frac / ratio
    float  ep_dc_prev, ep_dc_state;  // DC blocker taps (the sum^2 nonlinearity injects DC)
    float  ep_freqnorm;              // register position 0..1 (upper modes + bark fade out high up)
    int    ep_click;                 // tangent-click burst: samples remaining (the percussive chink)
    float  ep_click_amp;             // its peak amp (per-type base × strike velocity × hammer hardness)
    int    ep_type;                  // 0 Rhodes / 1 Wurli / 2 Clav (from harmonics at note-on)
    bool   ep_on;                    // struck this note — guards an engine id without a note-on init
    // membrane-drum state (INSTR_MEMBRANE): six decaying sine modes at circular-membrane
    // (Bessel) ratios, buffer-free (mallet family). Struck/self-decaying. The bayan pitch-bend
    // (morph) is derived from step_samples per sample — no extra state, like PD's DCW.
    float  mb_phase[6], mb_amp[6];   // per-mode phase + decaying amplitude (the head's ring)
    int    mb_strike;                // strike-noise samples remaining (the finger/slap contact)
    bool   mb_on;                    // struck this note — guards an engine id without a note-on init
    // reed-waveguide state (INSTR_REED): a bore delay line (REUSES ks_buf — reed is a distinct
    // wave id, never shares a voice with the Karplus pluck path) + a pressure-driven reed valve.
    // The first SELF-OSCILLATING held voice; every macro clamps to navkit's oscillation window
    // (it chokes/dies outside it — STEP-0, instrument-engines.md §8.8.7). Re-seeded on note-on.
    float  rd_lp;                    // bore-loss 1-pole LP state (bell radiation + wall damping)
    float  rd_dc_prev, rd_dc_state;  // DC blocker (steady blow pressure → large DC — essential)
    float  rd_vib_ph;                // lip-vibrato LFO phase
    float  rd_noise_lp;              // breath-turbulence noise LP (the "air" in the tone)
    float  rd_drift_ph;              // slow LFO phase — humanizes vibrato rate/depth (not a clean LFO)
    float  rd_drift;                 // slow breath-pressure random walk (kills the dead-flat steady state)
    int    rd_attack;                // attack-chiff samples remaining (the noisy tonguing onset)
    float  rd_tilt;                  // output-tilt LP (timbre brightness, built here — STEP-0)
    float  rd_initfreq;              // freq at note-on (bore sized for it; pitch tracking glides off it)
    int    rd_len;                   // bore delay length (half-wavelength); 0 = no note-on init
    int    rd_idx;                   // bore write index into ks_buf
    bool   rd_on;                    // note-on init guard (engine id hit without a strike → silent)
    // pipe/flute state (INSTR_PIPE): STK jet-drive flute — a bore delay (REUSES ks_buf, distinct
    // wave id from the Karplus/reed paths) + a short jet delay + a nonlinear jet deflection.
    // Held/self-oscillating; reuses reed's realism (breath turbulence, humanized vibrato, chiff). §8.8.8.
    float  pp_jet[64];               // jet delay line (lip→labium travel time)
    int    pp_jet_idx;               // jet write index
    int    pp_idx;                   // bore write index into ks_buf
    int    pp_len;                   // bore delay length; 0 = no note-on init
    float  pp_initfreq;              // freq at note-on (pitch tracking glides off it)
    float  pp_lp;                    // open-end reflection LP state (radiation impedance)
    float  pp_dc_prev, pp_dc_state;  // DC blocker
    float  pp_vib_ph, pp_drift_ph, pp_drift, pp_noise_lp;  // humanized vibrato + breath turbulence/drift
    int    pp_attack;                // attack-chiff samples remaining (the tongued "tu" onset)
    bool   pp_on;                    // note-on init guard
    // formant-voice state (INSTR_VOICE): navkit VoicForm port — a glottal pulse through four SVF
    // formants with a continuous vowel morph. EXPERIMENTAL: the raw params live FLAT in vox_p[]
    // (poked by note_aux() — the voxlab fat prototype) instead of riding the 3 macro knobs,
    // so we can audition which three deserve to become harmonics/timbre/morph. vowels-only for now.
    float  vox_p[20];                // raw param TARGETS 0..1 (note_aux idx, must hold VOX_NPARAM): vowel/size/breath/openQ/tilt/vibDepth/vibRate/nasality/openness/frontness + EXPERIMENTAL 10 buzz·11 jitter·12 shimmer·13 creak·14 nasalAF·15 reduce·16 measBW
    float  vox_s[20];                // slewed copies (per-sample one-pole → no zipper on slider moves)
    float  vox_glot_ph;              // glottal pulse phase
    float  vox_tilt_lp;              // spectral-tilt 1-pole state
    float  vox_vib_ph;               // vibrato LFO phase
    float  vox_jit_mul;              // per-period pitch-jitter multiplier (1.0 = none); redrawn each glottal cycle
    float  vox_shim_mul;             // per-period amplitude-shimmer multiplier (1.0 = none)
    int    vox_creak_skip;           // diplophonia/creak: attenuate this glottal period (vocal fry)
    float  vox_naf_low, vox_naf_band; // anti-formant nasality notch SVF state (navkit WAVE_VOICE model)
    float  vox_f_low[4], vox_f_band[4]; // 4 formant SVF states (low, band) — high recomputed per sample
    int    vox_cons;                 // consonant ONSET id (VC_*), -1 = none; set by voice_consonant()
    float  vox_cons_t;               // seconds since the consonant onset began (counts up to its duration)
    int    vox_coda;                 // consonant CODA id (VC_*), -1 = none; set by voice_coda() near release
    float  vox_coda_t;               // seconds since the coda morph began (vowel → consonant at note end)
    bool   vox_on;                   // note-on init guard (engine id hit without a start → silent)
    // guitar state (INSTR_GUITAR): the bodied plucked string — PLUCK's Karplus-Strong string
    // (REUSES ks_buf, distinct wave id from the bare pluck path) + 4 parallel body-resonator
    // bandpass formants + an output DC blocker. macros: harmonics = body (open/clear → resonant/
    // boxy — sets the formant voicing + dry/wet mix at note-on), timbre = string brightness (the
    // excitation lowpass), morph = mute (per-sample feedback: long open ring → tight pizzicato).
    // Buzz/jawari (sitar) deferred to a future preset. Design: instrument-engines.md §8.8.9.
    SoundBiquad gt_body[4];          // body formants (parallel bandpass), voiced from harmonics
    float  gt_bodymix;               // dry string ↔ wet body blend (from harmonics)
    float  gt_dc_prev, gt_dc_state;  // output DC blocker (long-sustain bodies build DC)
    bool   gt_on;                    // note-on init guard (engine id hit without a pluck → silent)
    // piano state (INSTR_PIANO): StifKarp stiff string — our KS string (REUSES ks_buf) + a
    // dispersion allpass chain (the inharmonic "stretched partial" piano shimmer, the engine's
    // defining feature) + a baked grand-piano soundboard (4 body biquads) + an output DC blocker.
    // macros: harmonics = stiffness (dispersion depth + stages), timbre = hammer (excitation
    // lowpass: soft felt → hard), morph = pedal (decay length + high-freq retention: damped
    // staccato → long open sustain). Double-string detune + prepared buzz deferred. §8.8.9.
    float  pn_disp_c[4], pn_disp_s[4];  // dispersion allpass coeffs (set from stiffness) + states
    int    pn_disp_n;                   // active dispersion stages (1..4, by stiffness)
    SoundBiquad pn_body[4];             // per-voicing soundboard formants (set at note-on)
    float  pn_bodymix;
    float  pn_loop_lp, pn_loopco;       // output tone-filter (1-pole LP) state + coeff (per voicing)
    float  pn_symp;                     // sympathetic-resonance level (per voicing)
    float  pn_detune;                   // 2nd-string detune ratio (per voicing; 1.0 = no 2nd string)
    float  pn_dc_prev, pn_dc_state;     // output DC blocker
    // navkit-verbatim KS string: near-lossless loop (decay comes from the AMP ENVELOPE, not the
    // loop — that's what keeps the upper harmonics alive), one-period buffer + fractional-delay
    // allpass tuning, per-voicing brightness/damping.
    float  pn_ksb, pn_ksd;              // ksBrightness (high-harmonic retention) + ksDamping (≈0.999)
    float  pn_ksb_cur;                  // brightness ENVELOPE: strikes bright, settles to pn_ksb (the piano "bloom")
    float  pn_apc, pn_aps;              // fractional-delay allpass coeff + state (pitch tuning)
    float  pn_initf;                    // freq at note-on (pitch-tracking reference)
    float  pn_dampg, pn_damps;          // damper gain (pedal) + slewed state
    float  pn_dd;                       // DOUBLE-DECAY: extra per-period loss right after the strike, relaxes to 0 (~0.2s) — the fast initial drop into a long aftersound. ⚠ It does NOT mean "struck, not plucked" (the old comment claimed that): a PLUCKED guitar has two-rate decay too, from the string's two polarisation planes decaying at different rates (Synth Secrets Part 28), and the piano's own cause is different again — the pairs and tricords interacting so energy transfer to the soundboard slows (Part 42). Common to both families; only the proportions differ. GUITAR/PLUCK should probably borrow it (audit §H3)
    float  pn_knock;                    // HAMMER KNOCK: default onset transient amount (broadband click over eng_click), ON for piano regardless of MODE_STRING_CLICK
    float  pn_ks2[SOUND_KS_MAX];        // detuned 2nd string delay line (own loop)
    int    pn_ks2_widx, pn_ks2_len;
    float  pn_ks2_last, pn_ks2_apc, pn_ks2_aps;
    float  pn_ks2_disp[4];              // 2nd string dispersion states (reuses pn_disp_c coeffs)
    bool   pn_on;                       // note-on init guard
    // bowed state (INSTR_BOWED): navkit's Smith/McIntyre bowed-string waveguide (line-for-line port).
    // Two delay lines meet at the bow contact point — PACKED into ks_buf (distinct wave id, never
    // shares a voice with the Karplus/reed/pipe paths): nut half = ks_buf[0..bw_nutlen), bridge half
    // = ks_buf[bw_nutlen..bw_nutlen+bw_brlen). A hyperbolic stick-slip friction re-excites the
    // string → self-oscillation; held like reed/pipe. STEP-0 (navkit-bowsweep.c) found the Helmholtz
    // wedge — the macros are pinned inside it: harmonics = bow position β (note-on split), timbre =
    // bow pressure (0.10–0.26, the narrow axis), morph = bow velocity/swell (wider wedge as it grows).
    int    bw_nutlen, bw_brlen;         // delay-line split lengths (sum = full wavelength, ≤ KS_MAX-1)
    int    bw_nutidx, bw_bridx;         // write indices within each half (bridge offset by bw_nutlen)
    float  bw_nutrefl, bw_brrefl;       // reflection-filter states (nut end / bridge end)
    float  bw_initfreq;                 // freq at note-on (bore sized for it; pitch tracking glides off it)
    float  bw_vib_ph, bw_drift_ph, bw_drift, bw_noise_lp;  // humanized pitch-vibrato + bow-noise (rosin) + drift
    int    bw_attack;                   // bow-bite onset samples (the catch at note start)
    float  bw_dc_prev, bw_dc_state;     // output DC blocker (steady bow drives a large DC)
    bool   bw_on;                       // note-on init guard
    bool   bw_pizz;                     // PIZZICATO: seed the string with a pluck + bypass the bow
                                        // friction, so the SAME waveguide (string + body) rings down
                                        // instead of self-oscillating. Set from eng_p[0] >= 0.5 at note-on.
    // ── BOWED BODY (§M2, plan 2.4) — opt-in, default OFF ──────────────────────────────────────
    // §F4 found INSTR_BOWED shipping with NO body resonator at all; its output comment even names the
    // body it does not model ("the bridge-side signal — what the body radiates"). Reid's Part 22 says an
    // instrument body IS a small reverberant room, in "the delay range of about 1mS to 4mS", built as
    // three short parallel lines. Both that and a bandpass-formant alternative were built and A/B'd (§M2
    // asked for exactly that); the owner's ear liked the body but could not separate the two models, so the
    // COMBS were kept on §M2's own argument — physically derived rather than hand-tuned, ~3x the colouring,
    // and the mechanism that could also serve GUITAR's body and the piano tricord. The formant variant and
    // its MODE_BOW_BODYTYPE knob were removed rather than carried forever (verdict: plan §2.4).
    // THE BODY IS NOT HERE: it lives PER SLOT in the bow_bodies[] pool, because an instrument has ONE box
    // that every string drives. See that pool for the model, the sizing, and the once-per-sample rule.
    // Only the blend AMOUNT is per-voice — the voice reads the shared body's output and mixes it into its
    // own signal, so the body still passes through this voice's filter/env/drive chain.
    float  bw_bd_amt;                   // body blend (eng_p[1], MODE_BOW_BODY; 0 = off = the bare string)
    int    bw_bd_slot;                  // which bow_bodies[] entry this voice feeds; -1 = none (body off)
    // fundamental reinforcement (guitar + piano): a sub-oscillator at the note's pitch, envelope-
    // following the string, mixed under it — adds the low-end WEIGHT a bare KS string lacks (the
    // "thin" cure). Plus an onset noise CLICK (pick/hammer transient). Both amounts come from
    // eng_p[] (set via instrument_mode, note-on — the permanent per-engine aux channel, decision 0017; NOT baked to constants).
    float  eng_p[7];                    // copied from the instrument at note-on (0 weight · 1 attack · 2 piano decay-scale · 3 piano knock-scale · 4 piano stretch-scale · 5 piano stiff-scale)
    float  eng_subph, eng_env;          // sub-osc phase + envelope follower
    int    eng_click;                   // onset-click samples remaining
    // brass state (INSTR_BRASS): STK BrassInstrument (Cook/Scavone) — a bore delay (REUSES ks_buf,
    // distinct wave id, never shares a voice with the reed/pipe/bowed/Karplus paths) closed by an
    // inverting bell reflection, driven by a LIP VALVE modeled as a 2-pole resonant biquad (the
    // mass-spring lip; its resonance tracks just ABOVE the played pitch → lip-slur / harmonic lock).
    // The defining timbre is pressure-driven BRASSINESS: high blow + high timbre steepens the
    // circulating wave (a shockwave) → the overtones explode (quiet=round, loud=blatty). Held/
    // self-oscillating like reed; the amp ADSR gates it. STEP-0 + macros: §8.8.10.
    int    br_len;                      // bore delay length (half-wavelength one-way); 0 = no note-on init
    int    br_idx;                      // bore write index into ks_buf
    float  br_initfreq;                 // freq at note-on (bore sized for it; pitch tracking glides off it)
    float  br_lip_y1, br_lip_y2;        // lip biquad output history (the normalized resonant bandpass)
    float  br_lip_x1, br_lip_x2;        // lip biquad input history (b2 = -b0 bandpass needs x[n-2])
    float  br_lp;                       // bell-radiation 1-pole LP state
    float  br_dc_prev, br_dc_state;     // bore-return DC blocker (steady blow → large DC)
    float  br_out_prev, br_out_state;   // OUTPUT DC blocker (the asymmetric brassiness shaper injects DC)
    float  br_env;                      // bore-output amplitude follower (level → shock-wave brightness)
    float  br_hp;                       // OUTPUT high-shelf 1-pole state (the level-coupled "blat" lift)
    float  br_vib_ph, br_drift_ph, br_drift, br_noise_lp;  // humanized lip-vibrato + breath turbulence/drift
    int    br_attack;                   // speak-transient samples remaining (the "tah" onset)
    bool   br_on;                       // note-on init guard (engine id hit without a note-on → silent)
    // sample-playback state (INSTR_SAMPLE, mic-and-sampling.md piece 2): read sound_samples[smp_idx].data
    // at a fractional position; speed = (played freq)/smp_root. Minimal one-shot forward playback.
    int    smp_idx;                     // sound_samples[] slot snapshot from the instrument; -1 = none/silent
    float  smp_root;                    // root freq (Hz) snapshot — the pitch at playback speed 1.0
    float  smp_start_f, smp_end_f;      // chop bounds snapshot (fractions 0..1); play smp_start_f*len .. smp_end_f*len
    int    smp_mode;                    // SAMPLE_NORMAL/REVERSE/LOOP/PINGPONG snapshot
    float  smp_dir;                     // playback direction for PINGPONG: +1 forward / -1 back
    double smp_pos;                     // fractional read position into the buffer (double: no drift over long buffers)
    bool   smp_on;                      // note-on init guard (engine id hit without a start → silent)
} Voice;
#define SOUND_HANDLE_BITS 5                      // slot field width — must hold SOUND_VOICES-1 (32 voices → 0..31 → 5 bits)
#define SCOPE_LEN 2048
#define SOUND_SAMPLE_SLOTS 8
typedef struct { float *data; int len; bool loaded; } SoundSample;  // data = malloc'd mono PCM -1..1
#define SOUND_USER_WAVES 4
#define SOUND_WAVE_LEN   64
typedef struct {
    float buf[3][BOW_BODY_MAX];   // the three parallel delay lines
    int   pos[3], len[3];         // read/write head + length, per line
    float lp[3];                  // one-pole damping in each loop (a body's RT60 falls with frequency)
    float in;                     // this sample's summed string input from every voice on the slot
    float wet_share;              // last sample's output, divided by the number of voices reading it
    int   readers;                // voices that fed it this sample (refilled every sample)
    int   quiet;                  // consecutive unfed samples — the lines get zeroed when this runs out
    float size;                   // the scale factor this box is currently BUILT at (see bow_body_scale)
    bool  live;                   // claimed by a slot, so worth clocking
} BowBody;
#define SOUND_ECHO_MAX (SOUND_SAMPLE_RATE * 2)   // 2s cap on the delay line
#define REVERB_COMB_1 1559         // comb delay times in samples @44100 Hz, mutually prime (navkit)
#define REVERB_COMB_2 1621
#define REVERB_COMB_3 1493
#define REVERB_COMB_4 1427
#define REVERB_ALLPASS_1 223
#define REVERB_ALLPASS_2 557
#define REVERB_PREDELAY  882       // fixed 20ms pre-delay (SOUND_SAMPLE_RATE/50)
#define SPRING_AP_STAGES 8
#define SPRING_AP_MAX    128         // max per-stage delay (buffer size)
#define SPRING_DISP    0.62f         // default dispersion coefficient (the "boing" character)
// PLATE voicing (reverb_plate) — input diffusion lines, in ONE flat buffer per tank that the four
// stages index by offset (so the sizes are exact, not padded to a common max like the spring's).
#define PLATE_AP_STAGES 4
#define PLATE_AP_TOTAL  1074         // 149+211+293+421 — ~4.3KB/tank of .bss (zero bytes of wasm)
#define PLATE_WIDTH     0.55f        // default L/R spread of the two pickups (reverb_plate_width)
#define SOUND_REVERB_TANKS 3
typedef struct {
    float comb1[REVERB_COMB_1], comb2[REVERB_COMB_2], comb3[REVERB_COMB_3], comb4[REVERB_COMB_4];
    float ap1[REVERB_ALLPASS_1], ap2[REVERB_ALLPASS_2];
    float predelay[REVERB_PREDELAY];
    int   cp1, cp2, cp3, cp4;        // comb write positions
    int   ap_p1, ap_p2;              // allpass positions
    int   pd_p;                      // predelay write position
    float clp1, clp2, clp3, clp4;    // per-comb damping LP states
    float spring_ap[SPRING_AP_STAGES][SPRING_AP_MAX];  // stretched-allpass dispersion delay lines (rvb_spring > 0)
    int   spring_app[SPRING_AP_STAGES];                // their write positions
    float spring_hp, spring_lp;                        // spring band-limit filter states
    float plate_ap[PLATE_AP_TOTAL];                    // plate input-diffusion allpass lines (rvb_plate > 0)
    int   plate_app[PLATE_AP_STAGES];                  // their write positions
    float plate_hp, plate_br;                          // plate low-cut + top-lift filter states
    float fb, damp;                  // config from size/damping — set by reverb() (tank 0) / reverb_bus()
    float mix;                       // dry/wet blend at the insert: 1 = wet-replace (a dedicated send-bus), <1 = in-line (reverb_insert)
    bool  used;                      // per-tank dormancy: a dormant tank is skipped (costs zero)
} ReverbTank;
#define SOUND_FX_BUSES   8         // bus 0 master + 7 aux (per-instrument). ~82KB of buffers total
#define CHORUS_BUF_LEN   2048      // ~46ms @44100 Hz
#define FLANGER_BUF_LEN   512        // ~11ms @44100 Hz
#define TAPE_BUF_LEN     1024
#define TAPE_INST 2                        // Increment F: tape instances per bus (LO-FI vs standalone TAPE) — each carries its own buffer (~32KB/bus total)
#define CRUSH_INST 2                       // Increment F: crush instances per bus (LO-FI vs standalone BITCRUSH)
#define DRIVE_INST 2                        // Increment F: bus-drive instances (a 2nd drive in the chain — overdrive pedal INTO amp drive)
#define FILT_INST 2                         // Increment F: filter instances per bus (filter A/B; LO-FI vs standalone)
#define EQ_INST 2                         // Increment F: EQ instances per bus (EQ before AND after a dirt stage)
#define SOUND_PHASER_STAGES 8
#define LESLIE_BUF        512        // ~11.6ms horn Doppler delay line (navkit LESLIE_BUFFER_SIZE)
#define N_SC_KEYS 4   // independent trigger buses (kick/snare/…); sidechain_key key index 0..3
// key<0 = glue (self-keyed). env2 = the slowly-bled PEAK MEMORY that glue's dual-slope recovery
// measures its fall from; mk_num/mk_den are slow energy-out/energy-in averages and gavg their ratio,
// which IS glue's automatic makeup. A keyed sidechain touches none of them, so the pump is unchanged.
typedef struct { bool used; int key; float amount, atk, rel, env, env2, gavg, mk_num, mk_den; } SideChain;
#define VOC_BANDS 12
#define AM_RING 8192
enum { AM_SNAP, AM_SHIFT };
#define AM_MAXV 3                     // voices in a stack: the shift itself, + a fifth, + an octave
#define SOUND_GRAIN_TANKS  2                          // pool size: master + one instrument bus at once (~1MB total)
#define GRAIN_BUF_LEN      (SOUND_SAMPLE_RATE * 3)    // 3 s capture (navkit uses 5 s; 3 s is plenty of lookback, half the RAM)
#define GRAIN_MAX_GRAINS   24                         // max simultaneous grains (navkit GRAN_DELAY_MAX_GRAINS)
typedef struct {
    float readPos, posInc, envPhase, envInc, amp;   // navkit GranDelayGrain: read cursor, speed, Hanning phase+inc, level
    bool  active;
} GrainVoice;
typedef struct {
    float buf[GRAIN_BUF_LEN];
    GrainVoice grains[GRAIN_MAX_GRAINS];
    int    writePos;
    float  spawnTimer, lastOut;
    unsigned int noiseSeed;
    float  mix, feedback, grainSize, density, position, scatter;   // grainSize ms · density /s · position/scatter 0..1 · feedback 0..0.9
    float  pitch, pitch_spread;    // grain transpose: semitones -24..24 (0 = unchanged) + random per-grain detune 0..1
    bool   freeze, used, reverse;  // reverse = grains play backwards through the buffer
} GrainTank;
#define SHW_BUF_LEN  (SOUND_SAMPLE_RATE / 16)   // ~62 ms — room for a drifting short delay
#define N_INSERTS (FX_MULTIBAND + 1)           // array size / kind validation cap: pedals + FORMANT/FILTER/PAN/RINGMOD (default) + FX_REVERB/ECHO/GRAINS/DRIVE/SHALLOW/GATE/SQUASH (placed via fx_order). Chain length is capped separately by FX_ORDER_SLOTS.
#define FX_ORDER_SLOTS 16                   // fx_order packs 16 slots (4 ints × 4 bytes, 1 byte/slot: kind 5 bits | instance 3 bits). Kinds 0..31, instances 0..7. A chain longer than 16 is truncated.
typedef enum {
    SR_SFX          = 0,
    /* 1 retired — music track, cut 2026-06, see decisions/ */
    SR_NOTE         = 2,
    SR_INSTR        = 3,
    SR_INSTR_DUTY   = 4,
    SR_INSTR_LFO    = 5,
    SR_INSTR_FILTER = 6,
    SR_NOTE_ON      = 7,
    SR_NOTE_OFF     = 8,
    SR_NOTE_PITCH   = 9,
    SR_NOTE_VOL     = 10,
    SR_NOTE_CUTOFF  = 11,
    SR_NOTE_DUTY    = 12,
    SR_NOTE_OFF_ALL = 13,
    SR_NOTE_RES     = 14,
    SR_NOTE_LFO     = 15,
    SR_NOTE_FILTER  = 16,
    SR_NOTE_GLIDE   = 17,
    SR_INSTR_ENV    = 18,
    SR_NOTE_ENV     = 19,
    SR_WAVE_SET     = 20,
    SR_INSTR_MACRO  = 21,
    SR_NOTE_MACRO   = 22,
    SR_INSTR_CHOKE  = 23,
    SR_INSTR_DRIVE  = 24,
    SR_NOTE_DRIVE   = 25,
    SR_ECHO         = 26,
    SR_INSTR_ECHO   = 27,
    SR_NOTE_ECHO    = 28,
    SR_INSTR_TUNE   = 29,
    SR_INSTR_FOLLOW = 30,
    SR_NOTE_FOLLOW  = 31,
    SR_VOICE_PARAM  = 32,   // EXPERIMENTAL INSTR_VOICE raw-param poke (voxlab): a=idx, b=val*1000
    SR_VOICE_CONS   = 33,   // EXPERIMENTAL INSTR_VOICE consonant onset (voxlab): a=consonant id (VC_*), -1 = none
    SR_VOICE_CODA   = 34,   // EXPERIMENTAL INSTR_VOICE consonant coda (voxlab): a=consonant id (VC_*), -1 = none
    SR_VOICE_NASAL  = 39,   // INSTR_VOICE nasal color (public voice_nasal): a=amount*1000 → vox_p[7] (35-38 = the pan block)
    SR_INSTR_PAN    = 35,   // a=slot, b=pan*1000 (signed) — per-instrument stereo position (stereo.md)
    SR_NOTE_PAN     = 36,   // a=pan*1000 (signed, live/slewed), e0/e1=handle — live pan on a held note
    SR_ENG_TUNE     = 37,   // EXPERIMENTAL guitar/piano tuning poke: a=slot, b=idx (0 weight·1 attack), c=val*1000
    SR_PAN_LAW      = 38,   // a=law (PAN_LINEAR/PAN_POWER) — master pan law (stereo.md); gated, default LINEAR
    SR_REVERB       = 40,   // a=size*1000, b=damping*1000 — configure THE reverb bus (40-42; 39 = voice_nasal above)
    SR_INSTR_REVERB = 41,   // a=slot, b=send*1000 — per-slot reverb send
    SR_NOTE_REVERB  = 42,   // a=val*1000 (live, slewed), e0/e1=handle — live reverb send on a held note
    SR_CHORUS       = 43,   // a=rate*1000, b=depth*1000, c=mix*1000 — configure THE master chorus (mod-delay buffer)
    SR_FLANGER      = 44,   // a=rate*1000, b=depth*1000, c=feedback*1000 (signed), e0=mix*1000 — THE master flanger
    SR_INSTR_CHORUS = 45,   // a=slot, b=rate*1000, c=depth*1000, e0=mix*1000 — chorus on one instrument (auto-bus)
    SR_INSTR_FLANGER= 46,   // a=slot, b=rate*1000, c=depth*1000, e0=fb*1000 (signed), e1=mix*1000 — flanger on one instrument (auto-bus)
    SR_TAPE         = 47,   // a=wow*1000, b=flutter*1000, c=sat*1000 — THE master tape (bus 0)
    SR_INSTR_TAPE   = 48,   // a=slot, b=wow*1000, c=flutter*1000, e0=sat*1000 — tape on one instrument (auto-bus)
    SR_WAH          = 49,   // a=sens*1000, b=res*1000, c=mix*1000 — THE master auto-wah (bus 0)
    SR_INSTR_WAH    = 50,   // a=slot, b=sens*1000, c=res*1000, e0=mix*1000 — auto-wah on one instrument (auto-bus)
    SR_INSTR_DRIVE_MODE = 51,  // a=slot, b=mode (DRIVE_*) — set a slot's drive waveshaper
    SR_NOTE_DRIVE_MODE  = 52,  // a=mode (DRIVE_*), e0/e1=handle — live waveshaper switch on a held note
    SR_BITCRUSH     = 53,   // a=bits*100, b=rate*100, c=mix*1000 — THE master bitcrush (bus 0)
    SR_INSTR_BITCRUSH = 54, // a=slot, b=bits*100, c=rate*100, e0=mix*1000 — bitcrush on one instrument (auto-bus)
    SR_EQ           = 55,   // a=low_db*1000, b=mid_db*1000, c=high_db*1000 — THE master 3-band EQ (bus 0)
    SR_INSTR_EQ     = 56,   // a=slot, b=low_db*1000, c=mid_db*1000, e0=high_db*1000 — EQ on one instrument (auto-bus)
    SR_WAH_LFO      = 57,   // a=rate*1000, b=res*1000, c=mix*1000 — THE master LFO-wah (bus 0, navkit WAH_MODE_LFO)
    SR_INSTR_WAH_LFO= 58,   // a=slot, b=rate*1000, c=res*1000, e0=mix*1000 — LFO-wah on one instrument (auto-bus)
    SR_TREMOLO      = 59,   // a=rate*1000, b=depth*1000, c=shape — THE master tremolo (bus 0, navkit processTremolo)
    SR_INSTR_TREMOLO= 60,   // a=slot, b=rate*1000, c=depth*1000, e0=shape — tremolo on one instrument (auto-bus)
    SR_PHASER       = 61,   // a=rate*1000, b=depth*1000, c=fb*1000(signed), e0=mix*1000, e1=stages — THE master phaser (bus 0, navkit processPhaser)
    SR_INSTR_PHASER = 62,   // a=slot, b=rate*1000, c=depth*1000, e0=fb*1000(signed), e1=mix*1000, e2=stages — phaser on one instrument (auto-bus)
    SR_FX_ORDER     = 63,   // a=bus, b=packed lo (slots 0..7, 4 bits each, FX_*), c=count, e0=packed hi (slots 8..) — set a bus's insert visit order
    SR_LESLIE       = 64,   // a=speed, b=drive*1000, c=balance*1000, e0=doppler*1000, e1=mix*1000 — THE master Leslie (bus 0, navkit processLeslie)
    SR_INSTR_LESLIE = 65,   // a=slot, b=speed, c=drive*1000, e0=balance*1000, e1=doppler*1000, e2=mix*1000 — Leslie on one instrument (auto-bus)
    SR_REVERB_BUS   = 66,   // a=tank(1..N-1), b=size*1000, c=damp*1000 — configure a reverb send-bus (claims an aux bus, chain = [FX_REVERB])
    SR_INSTR_REVERB_BUS = 67, // a=slot, b=tank, c=mix*1000 — route a slot's reverb send into tank N's bus instead of the master send
    SR_REVERB_BUS_FX = 68,  // a=tank, b=fx (FX_*), c/e0/e1 = params*1000 — add/configure an insert AFTER the reverb on tank N's bus
    SR_REVERB_INSERT = 69,  // a=size*1000, b=damp*1000, c=mix*1000 — reverb as a dry/wet-MIX INSERT on the master bus (in the fx_order chain)
    SR_FORMANT      = 70,   // a=vowel*1000, b=q*1000, c=mix*1000 — THE master formant/vowel filter (bus 0)
    SR_INSTR_FORMANT= 71,   // a=slot, b=vowel*1000, c=q*1000, e0=mix*1000 — formant filter on one instrument (auto-bus)
    SR_SIDECHAIN    = 72,   // a=victim_bus, b=key, c=amount*1000, e0=attack_ms, e1=release_ms — duck a bus on a trigger key
    SR_SIDECHAIN_KEY= 73,   // a=slot, b=key, c=send*1000 — route a slot into a sidechain trigger key
    SR_GLUE         = 74,   // a=victim_bus, b=amount*1000, c=attack_ms, e0=release_ms — bus comp (self-keyed, no trigger)
    SR_FILTER       = 75,   // a=mode, b=cutoff_hz, c=resonance*1000 — THE master resonant filter (DJ filter), bus 0
    SR_AUTOPAN      = 76,   // a=rate*1000, b=depth*1000, c=shape — THE master auto-pan (bus 0, antiphase tremolo)
    SR_INSTR_AUTOPAN= 77,   // a=slot, b=rate*1000, c=depth*1000, e0=shape — auto-pan on one instrument (auto-bus)
    SR_RINGMOD      = 78,   // a=freq_hz, b=mix*1000 — THE master ring modulator (bus 0)
    SR_INSTR_RINGMOD= 79,   // a=slot, b=freq_hz, c=mix*1000 — ring mod on one instrument (auto-bus)
    SR_ECHO_INSERT  = 80,   // a=time_ms, b=fb*1000, c=tone*1000, e0=mix*1000 — echo as a dry/wet INSERT on the master bus (in the fx_order chain)
    SR_GRAINS       = 81,   // a=grain_ms, b=density*100, c=position*1000, e0=scatter*1000, e1=feedback*1000, e2=mix*1000 — THE master granular delay (bus 0)
    SR_INSTR_GRAINS = 82,   // a=slot, b=grain_ms, c=density*100, e0=position*1000, e1=scatter*1000, e2=PACK(feedback*100·*1001 + mix*1000) — granular on one instrument (auto-bus)
    SR_GRAINS_FREEZE       = 83,   // a=on (0/1) — freeze the master granular capture buffer (live toggle, no DSP reconfigure)
    SR_INSTR_GRAINS_FREEZE = 84,   // a=slot, b=on (0/1) — freeze one instrument's granular buffer
    SR_EQ_INST      = 85,   // a=instance, b=low_db*1000, c=mid_db*1000, e0=high_db*1000 — master EQ on a given INSTANCE (Increment F; instance 0 == SR_EQ)
    SR_CRUSH_INST   = 86,   // a=instance, b=bits*100, c=rate*100, e0=mix*1000 — master bitcrush on a given INSTANCE
    SR_TAPE_INST    = 87,   // a=instance, b=wow*1000, c=flut*1000, e0=sat*1000 — master tape on a given INSTANCE
    SR_FILTER_INST  = 88,   // a=instance, b=mode, c=cutoff_hz, e0=res*1000 — master filter on a given INSTANCE
    SR_DRIVE_INSERT = 89,   // a=amount*1000, b=mode (DRIVE_*), c=mix*1000 — mix-bus saturation INSERT on the master bus (FX_DRIVE in the fx_order chain)
    SR_DRIVE_INST   = 90,   // a=instance, b=amount*1000, c=mode, e0=mix*1000 — mix-bus drive on a given INSTANCE (Increment F; instance 0 == SR_DRIVE_INSERT)
    SR_GRAINS_PITCH       = 91,   // a=semitones*100, b=spread*1000, c=reverse(0/1) — transpose the master granular cloud
    SR_INSTR_GRAINS_PITCH = 92,   // a=slot, b=semitones*100, c=spread*1000, e0=reverse(0/1) — transpose one instrument's granular cloud
    SR_UNIVIBE       = 93,   // a=rate*1000, b=depth*1000, c=mix*1000 — THE master univibe (bus 0): the phaser swept by the optical LFO
    SR_INSTR_UNIVIBE = 94,   // a=slot, b=rate*1000, c=depth*1000, e0=mix*1000 — univibe on one instrument (auto-bus)
    SR_DROPOUT       = 95,   // a=amount*1000, b=depth*1000 — THE master tape-failure dropout (random level dips + HF loss)
    SR_SHALLOW       = 96,   // a=rate*1000, b=depth*1000, c=mix*1000 — THE master shallow-water (bus 0): K-field delay + Low Pass Gate
    SR_INSTR_SHALLOW = 97,   // a=slot, b=rate*1000, c=depth*1000, e0=mix*1000 — shallow water on one instrument (auto-bus)
    SR_AMP_NOISE     = 98,   // a=hiss*1000, b=hum*1000, c=mains_hz — THE optional rig-noise floor (hiss + 50/60Hz hum)
    SR_GATE          = 99,   // a=threshold*1000, b=attack_ms, c=release_ms — THE master noise gate (bus 0)
    SR_INSTR_GATE    = 100,  // a=slot, b=threshold*1000, c=attack_ms, e0=release_ms — noise gate on one instrument (auto-bus)
    SR_SHIMMER       = 101,  // a=size*1000, b=damp*1000, c=shimmer*1000, e0=mix*1000 — THE master shimmer reverb (octave-up feedback)
    SR_LISTENER      = 102,  // a=x*1000, b=y*1000 — spatial listener (ears) position (spatial.md)
    SR_LISTENER_VEL  = 103,  // a=vx*1000, b=vy*1000 — listener velocity for Doppler
    SR_SPATIAL_MODEL = 104,  // a=ref*1000, b=max*1000, c=rolloff*1000 — distance-falloff model
    SR_SPATIAL_SPEED = 105,  // a=c*1000 — speed of sound (units/sec); 0 = Doppler off
    SR_NOTE_POS      = 106,  // a=x*1000, b=y*1000, e0/e1=handle — place a held voice in the world
    SR_NOTE_MOTION   = 107,  // a=vx*1000, b=vy*1000, e0/e1=handle — held voice velocity (Doppler)
    SR_HIT_AT        = 108,  // a=midi, b=instr, c=vol, e0=gate_samples, e1=x*1000, e2=y*1000 — positioned one-shot
    SR_INSTR_SHIMMER = 109,  // a=slot, b=size*1000, c=damp*1000, e0=shimmer*1000, e1=mix*1000 — shimmer reverb on one instrument (pooled aux bus)
    SR_VARISPEED     = 110,  // a=speed*1000 — THE master tape varispeed (1.0 = bypass; <1 slow/down, >1 fast/up)
    SR_INSTR_MOTION  = 111,  // a=slot, b=vx*1000, c=vy*1000 — that emitter bus's velocity → bus Doppler
    SR_INSTR_POS     = 112,  // a=slot, b=x*1000, c=y*1000 — position an instrument's whole effected bus (v2 emitter, spatial.md).
                             // WAS 110 — collided with SR_VARISPEED (its handler ran first → instr_pos was shadowed/dead); renumbered 2026-06-15.
    SR_FX_MOD        = 113,  // a=target(FXMOD_*), b=value*1000, c=bus — CV sink: ride a sweep-safe effect param (ADR 0018)
    SR_FX_LFO        = 114,  // a=target(FXMOD_*), b=rate*100, c=bus, e0=depth*1000, e1=center*1000, e2=shape — engine LFO on a target (depth 0 = detach)
    SR_LFO_SHAPE     = 115,  // a=which, b=shape(LFO_SHAPE_*), c=slot (>=0 → instrument) ; e0/e1=handle (c<0 → live held note) — set a voice LFO's waveform
    SR_INSTR_SYNC    = 116,  // a=slot, b=ratio*1000 — oscillator hard-sync slave:master ratio (0 = off)
    SR_NOTE_SYNC     = 117,  // a=ratio*1000 (live, slewed), e0/e1=handle — sweep a held note's hard-sync ratio
    SR_CART_SWITCH   = 118,  // a=context id (0..SOUND_CART_CTX-1) — umbrella-app cart switch: reset + replay that context's config log (de_switch_cart, share-panel.md)
    SR_BPM           = 119,  // a=rate — tempo. Queued like all config so it RECORDS into the cart context; a direct global write raced de_switch_cart (main thread wrote the new cart's bpm before the audio thread snapshotted the old one's — heard as tempo jumps in the bundle)
    SR_INSTR_UNISON        = 120,  // a=slot, b=voices, c=detune*1000 — configure the unison stack (instrument_unison)
    SR_INSTR_UNISON_DETUNE = 121,  // a=slot, b=detune*1000 — ride the unison spread alone (instrument_unison_detune), read LIVE like tune
    SR_INSTR_LEVEL         = 122,  // a=slot, b=level*1000 — per-slot output level/gain (instrument_level), read LIVE at mix like tune_mul
    SR_INSTR_SAMPLE        = 123,  // a=slot, b=sample slot, c=root freq(Hz)*1000 — bind an INSTR_SAMPLE slot to a recorded PCM buffer (instrument_sample); mic-and-sampling.md piece 2
    SR_INSTR_SAMPLE_REGION = 124,  // a=slot, b=start*1e6, c=end*1e6 — the CHOP: play the buffer from start..end (fractions 0..1); instrument_sample_region()
    SR_INSTR_SAMPLE_MODE   = 125,  // a=slot, b=mode — INSTR_SAMPLE playback mode (normal/reverse/loop/pingpong); instrument_sample_mode()
    SR_VOCODER      = 126,  // a=mix*1000 — the master-stage N-band vocoder (carrier = master mix, modulator = voc_mod). vocoder(); docs/design/vocoder.md
    SR_VOCODER_SEND = 127,  // a=slot, b=amount*1000 — route a slot into the vocoder MODULATOR (send-only: its dry is muted). vocoder_send()
    SR_VOCODER_MIC  = 128,  // a=amount*1000 — route the LIVE mic into the vocoder modulator (Phase 2). vocoder_mic()
    SR_VOCODER_UNVOICED = 129,  // a=amount*1000 — v2: how much to noise-substitute the top bands for unvoiced consonants. vocoder_unvoiced()
    SR_AUTOTUNE_MIC = 130,  // a=amount*1000, b=root(0..11), c=scale — LIVE streaming auto-tune of the mic (transparent-autotune.md §live). autotune_mic()
    SR_ECHO_INS_BBD = 131,  // a=amount*1000 — BBD analog voicing on the echo INSERT (echo_insert_bbd): clock wobble on the repeats + longer-delay-darkens
    SR_REVERB_SPRING = 132, // a=amount*1000 — SPRING voicing on the reverb (reverb_spring): dispersion "boing" + mid-band limit
    SR_REVERB_SPRING_TONE = 133, // a=x*1000 — spring dispersion coefficient (reverb_spring_tone): the "boing" character, live
    SR_DRIVE_VOICE = 134,   // a=voice (DRIVE_VOICE_*), b=tone*1000 — famous-pedal shaping on the drive insert (drive_voice)
    SR_INSTR_BANDLIMIT = 135, // a=slot, b=on — PolyBLEP anti-alias the slot's saw (0 = raw naive saw, default)
    SR_INPUT_MONITOR = 136,   // a=gain*1000 — route the LIVE mic through the master fx chain (input_monitor); audio-input-frontier.md ★1
    SR_MULTIBAND     = 137,   // a=low, b=mid, c=high, e0=up, e1=mix (×1000) — THE master multiband squash / OTT box (multiband)
    SR_INSTR_MULTIBAND = 138, // a=slot, b=low, c=mid, e0=high, e1=up, e2=mix (×1000) — multiband squash on one instrument's bus (instrument_multiband)
    SR_HARMONIZE_MIC = 139,   // a=semis*100, b=voices, c=formant*1000 — LIVE fixed-interval mic harmoniser (harmonize_mic); the AM_SHIFT face of the streaming corrector
    SR_INSTR_KEYTRACK = 140,  // a=slot, b=amount*1000 — KEYBOARD TRACKING of the filter cutoff (instrument_keytrack), audit §B2
    SR_NOTE_RETRIG  = 141,    // e0/e1=handle — RE-ARTICULATE a held voice (note_retrig): amp+mod envelopes jump back to
                              // attack and the engine's onset transient re-arms, resonator untouched. Audit §B3/§K6
    SR_NOTE_GLIDE_SCALE = 142,// a=amount*1000, e0/e1=handle — GLIDE SCALE on a held note: 0 = constant time,
                              // 1000 = per octave, ~200 = the analog law. Audit §B1
    SR_INSTR_GLIDE  = 143,    // a=slot, b=ms — PORTAMENTO as a patch property (instrument_glide); a new voice
                              // inherits it, and note_glide still overrides per-voice
    SR_INSTR_GLIDE_SCALE = 144,// a=slot, b=amount*1000 — GLIDE SCALE as a patch property (instrument_glide_scale)
    SR_INSTR_TRIGGER = 145,   // a=slot, b=TRIG_MULTI/TRIG_SINGLE — whether a note started while another key on
                              // this slot is down gets its ONSET TRANSIENT (instrument_trigger). Audit §L4
    // ADDED BY HAND (2026-08-14), like the framebuffer group in studio_ctx.h: reset the ACTIVE cart
    // context and replay its config log, on the audio thread. SR_CART_SWITCH already does exactly
    // this but no-ops when the target context is the active one, and a session restore is always
    // "the context you are already in". An EVENT kind (never recorded into the log it replays).
    // de_load_state, docs/design/engine-instance-seam.md.
    SR_STATE_RESTORE = 146,   // (no payload) — session-state restore: reset + replay ctx_log[ctx_active]
    SR_REVERB_PLATE = 147,    // a=amount*1000 — PLATE voicing on the reverb (reverb_plate): dense + bright + low-cut + decorrelated L/R
    SR_REVERB_PLATE_WIDTH = 148, // a=x*1000 — how far apart the plate's two pickups sit (reverb_plate_width), live
} SoundReqKind;
typedef struct { SoundReqKind kind; int a, b, c; int delay_samples; int dur_samples; int e0, e1, e2; } SoundReq;
#define SOUND_REQ_QUEUE   512   // generous: live held-voice control pushes many setters/frame, and a patch cart's
#define SOUND_DELAYED_MAX 64    // pending delayed notes (strum/schedule/schedule_hit) — fast sfx steps queue several ahead
#define SOUND_CART_CTX 8      // bundle contexts (Tinyjam wants many racks; 8 × 1024 reqs ≈ 300KB BSS)
#define SOUND_CTX_LOG  1024   // config entries per context (a rich patch cart's init() ≈ hundreds)
#define SHIM_PBUF   4096        // pitch-shift delay buffer (~93 ms)
typedef struct { float buf[SHIM_PBUF]; int wpos; float ph; } OctaveUp;
#define SOUND_SHIM_TANKS 2          // master + one instrument bus at once (~92KB; CPU is the real cap — a full reverb + octave-up per active tank)
typedef struct {
    ReverbTank tank;
    OctaveUp   oct;
    float mix, fb, prev, dcx, dcy;  // dcx/dcy = DC-blocker state on the recirculating loop
    bool  used;
} ShimVoice;
#define FXMOD_N 7                                   // active targets: studio.h FXMOD_FILTER_CUT(0)..FXMOD_SHIMMER_MIX(6)
#define VARI_BUF (SOUND_SAMPLE_RATE * 2)   // 2 s — room for a long dive before the read laps the write
#define VOX_NPARAM 19   // 0 vowel·1 size·2 breath·3 openq·4 tilt·5 vibDepth·6 vibRate · 7 nasality·8 openness(F1)·9 frontness(F2) + EXPERIMENTAL 10 buzz·11 jitter·12 shimmer·13 creak·14 nasalAF·15 reduce·16 measBW·17 vow2(diphthong target 0..9)·18 glide(0=primary→1=at vow2)
#define EMIT_DL_LEN  3072      // grain buffer per bus (~70ms @44100), stereo

typedef struct {
    Voice voices[SOUND_VOICES];
    int hn_gen[SOUND_VOICES];
    bool hn_used[SOUND_VOICES];
    int held_voice[SOUND_VOICES];
    float scope_buf[SCOPE_LEN];
    int scope_w;
    bool scope_ever;
    float scope2_bufL[SCOPE_LEN];
    float scope2_bufR[SCOPE_LEN];
    int scope2_w;
    bool scope2_ever;
    SoundSample sound_samples[SOUND_SAMPLE_SLOTS];
    float *rec_ring;
    volatile int rec_w;
    volatile long rec_total;
    volatile bool rec_arm;
    Sfx sfx_bank[SOUND_SFX_SLOTS];
    Instrument instr_bank[SOUND_INSTR_SLOTS];
    float user_wave[SOUND_USER_WAVES][SOUND_WAVE_LEN];
    BowBody bow_bodies[SOUND_BOW_BODIES];
    int bow_body_next;
    int bow_body_overflow;
    float echo_buf[SOUND_ECHO_MAX];
    int echo_widx;
    float echo_time;
    float echo_time_target;
    float echo_fb;
    float echo_tone_coef;
    float echo_lp;
    float echo_dc_x1;
    float echo_dc_y1;
    bool echo_used;
    float echo_ins_buf[SOUND_ECHO_MAX];
    int echo_ins_widx;
    float echo_ins_time;
    float echo_ins_time_target;
    float echo_ins_fb;
    float echo_ins_tone_coef;
    float echo_ins_lp;
    float echo_ins_mix;
    bool echo_ins_used;
    float echo_ins_bbd;
    float echo_ins_tone;
    float echo_ins_wph;
    float echo_ins_fph;
    int g_pan_law;
    float rvb_spring;
    float rvb_spring_disp;
    float rvb_plate;
    float rvb_plate_w;
    ReverbTank rvb_tanks[SOUND_REVERB_TANKS];
    bool reverb_used;
    int fx_next_bus;
    int8_t bus_tank[SOUND_FX_BUSES];
    int tank_bus[SOUND_REVERB_TANKS];
    int rvb_bus_overflow;
    float cho_buf[SOUND_FX_BUSES][CHORUS_BUF_LEN];
    int cho_widx[SOUND_FX_BUSES];
    float cho_phase[SOUND_FX_BUSES];
    float cho_rate[SOUND_FX_BUSES];
    float cho_depth[SOUND_FX_BUSES];
    float cho_mix[SOUND_FX_BUSES];
    bool cho_used[SOUND_FX_BUSES];
    float flg_buf[SOUND_FX_BUSES][FLANGER_BUF_LEN];
    int flg_widx[SOUND_FX_BUSES];
    float flg_phase[SOUND_FX_BUSES];
    float flg_rate[SOUND_FX_BUSES];
    float flg_depth[SOUND_FX_BUSES];
    float flg_fb[SOUND_FX_BUSES];
    float flg_mix[SOUND_FX_BUSES];
    float flg_dc_x1[SOUND_FX_BUSES];
    float flg_dc_y1[SOUND_FX_BUSES];
    bool flg_used[SOUND_FX_BUSES];
    float tape_bufL[SOUND_FX_BUSES][TAPE_INST][TAPE_BUF_LEN];
    float tape_bufR[SOUND_FX_BUSES][TAPE_INST][TAPE_BUF_LEN];
    int tape_widx[SOUND_FX_BUSES][TAPE_INST];
    float tape_wph[SOUND_FX_BUSES][TAPE_INST];
    float tape_fph[SOUND_FX_BUSES][TAPE_INST];
    float tape_lpL[SOUND_FX_BUSES][TAPE_INST];
    float tape_lpR[SOUND_FX_BUSES][TAPE_INST];
    float tape_wow[SOUND_FX_BUSES][TAPE_INST];
    float tape_flut[SOUND_FX_BUSES][TAPE_INST];
    float tape_sat[SOUND_FX_BUSES][TAPE_INST];
    bool tape_used[SOUND_FX_BUSES][TAPE_INST];
    float crush_bits[SOUND_FX_BUSES][CRUSH_INST];
    float crush_rate[SOUND_FX_BUSES][CRUSH_INST];
    float crush_mix[SOUND_FX_BUSES][CRUSH_INST];
    float crush_holdL[SOUND_FX_BUSES][CRUSH_INST];
    float crush_holdR[SOUND_FX_BUSES][CRUSH_INST];
    int crush_cnt[SOUND_FX_BUSES][CRUSH_INST];
    bool crush_used[SOUND_FX_BUSES][CRUSH_INST];
    float drvins_amt[SOUND_FX_BUSES][DRIVE_INST];
    int drvins_mode[SOUND_FX_BUSES][DRIVE_INST];
    float drvins_mix[SOUND_FX_BUSES][DRIVE_INST];
    bool drvins_used[SOUND_FX_BUSES][DRIVE_INST];
    float drvins_dcx[SOUND_FX_BUSES][DRIVE_INST][2];
    float drvins_dcy[SOUND_FX_BUSES][DRIVE_INST][2];
    int drvins_voice;
    float drvins_tone;
    float drvins_lp1[SOUND_FX_BUSES][DRIVE_INST][2];
    float drvins_lp2[SOUND_FX_BUSES][DRIVE_INST][2];
    float wah_env[SOUND_FX_BUSES];
    float wah_ic1[SOUND_FX_BUSES];
    float wah_ic2[SOUND_FX_BUSES];
    float wah_sens[SOUND_FX_BUSES];
    float wah_res[SOUND_FX_BUSES];
    float wah_mix[SOUND_FX_BUSES];
    bool wah_used[SOUND_FX_BUSES];
    float wah_lfo_rate[SOUND_FX_BUSES];
    float wah_lfo_phase[SOUND_FX_BUSES];
    int filt_mode[SOUND_FX_BUSES][FILT_INST];
    float filt_cut[SOUND_FX_BUSES][FILT_INST];
    float filt_res[SOUND_FX_BUSES][FILT_INST];
    float filt_ic1L[SOUND_FX_BUSES][FILT_INST];
    float filt_ic2L[SOUND_FX_BUSES][FILT_INST];
    float filt_ic1R[SOUND_FX_BUSES][FILT_INST];
    float filt_ic2R[SOUND_FX_BUSES][FILT_INST];
    bool filt_used[SOUND_FX_BUSES][FILT_INST];
    float fmt_freq[SOUND_FX_BUSES][4];
    float fmt_k[SOUND_FX_BUSES][4];
    float fmt_amp[SOUND_FX_BUSES][4];
    float fmt_ic1[SOUND_FX_BUSES][4];
    float fmt_ic2[SOUND_FX_BUSES][4];
    float fmt_mix[SOUND_FX_BUSES];
    bool fmt_used[SOUND_FX_BUSES];
    float eq_low_g[SOUND_FX_BUSES][EQ_INST];
    float eq_mid_g[SOUND_FX_BUSES][EQ_INST];
    float eq_high_g[SOUND_FX_BUSES][EQ_INST];
    float eq_loL[SOUND_FX_BUSES][EQ_INST];
    float eq_loR[SOUND_FX_BUSES][EQ_INST];
    float eq_hiL[SOUND_FX_BUSES][EQ_INST];
    float eq_hiR[SOUND_FX_BUSES][EQ_INST];
    bool eq_used[SOUND_FX_BUSES][EQ_INST];
    float trem_rate[SOUND_FX_BUSES];
    float trem_depth[SOUND_FX_BUSES];
    int trem_shape[SOUND_FX_BUSES];
    float trem_phase[SOUND_FX_BUSES];
    ModState trem_md[SOUND_FX_BUSES];
    bool trem_used[SOUND_FX_BUSES];
    float pan_rate[SOUND_FX_BUSES];
    float pan_depth[SOUND_FX_BUSES];
    int pan_shape[SOUND_FX_BUSES];
    float pan_phase[SOUND_FX_BUSES];
    ModState pan_md[SOUND_FX_BUSES];
    bool pan_used[SOUND_FX_BUSES];
    float rm_freq[SOUND_FX_BUSES];
    float rm_mix[SOUND_FX_BUSES];
    float rm_phase[SOUND_FX_BUSES];
    bool rm_used[SOUND_FX_BUSES];
    float phaser_rate[SOUND_FX_BUSES];
    float phaser_depth[SOUND_FX_BUSES];
    float phaser_fb[SOUND_FX_BUSES];
    float phaser_mix[SOUND_FX_BUSES];
    int phaser_stages[SOUND_FX_BUSES];
    float phaser_phase[SOUND_FX_BUSES];
    float phaser_stL[SOUND_FX_BUSES][SOUND_PHASER_STAGES];
    float phaser_pvL[SOUND_FX_BUSES][SOUND_PHASER_STAGES];
    float phaser_stR[SOUND_FX_BUSES][SOUND_PHASER_STAGES];
    float phaser_pvR[SOUND_FX_BUSES][SOUND_PHASER_STAGES];
    float phaser_dcx[SOUND_FX_BUSES][2];
    float phaser_dcy[SOUND_FX_BUSES][2];
    bool phaser_used[SOUND_FX_BUSES];
    bool phaser_optical[SOUND_FX_BUSES];
    int leslie_speed[SOUND_FX_BUSES];
    float leslie_drive[SOUND_FX_BUSES];
    float leslie_bal[SOUND_FX_BUSES];
    float leslie_dopp[SOUND_FX_BUSES];
    float leslie_mix[SOUND_FX_BUSES];
    bool leslie_used[SOUND_FX_BUSES];
    float leslie_hornPh[SOUND_FX_BUSES];
    float leslie_drumPh[SOUND_FX_BUSES];
    float leslie_hornRt[SOUND_FX_BUSES];
    float leslie_drumRt[SOUND_FX_BUSES];
    float leslie_xoL[SOUND_FX_BUSES];
    float leslie_xoR[SOUND_FX_BUSES];
    int leslie_wpos[SOUND_FX_BUSES];
    float leslie_bufL[SOUND_FX_BUSES][LESLIE_BUF];
    float leslie_bufR[SOUND_FX_BUSES][LESLIE_BUF];
    SideChain sc[SOUND_FX_BUSES];
    float sc_key_lvl[N_SC_KEYS];
    bool voc_on;
    float voc_mix;
    float voc_mod;
    float voc_f[VOC_BANDS];
    float voc_q1;
    float voc_mk;
    float voc_c_lp[VOC_BANDS];
    float voc_c_bp[VOC_BANDS];
    float voc_m_lp[VOC_BANDS];
    float voc_m_bp[VOC_BANDS];
    float voc_env[VOC_BANDS];
    float voc_uv_amt;
    float voc_uv;
    int voc_nz;
    float voc_nk;
    float voc_n_lp[VOC_BANDS];
    float voc_n_bp[VOC_BANDS];
    int extin_mon_on;
    float extin_mon_gain;
    float voc_mic_amt;
    float am_inbuf[AM_RING];
    float am_outbuf[AM_RING];
    float am_nrm[AM_RING];
    long am_w;
    float am_T;
    long am_ea;
    long am_eps[8];
    int am_epi;
    int am_pd;
    float am_amt;
    int am_on;
    int am_root;
    int am_scale;
    long am_ts[AM_MAXV];
    int am_mode;
    int am_nv;
    float am_semis;
    float am_gain;
    GrainTank grain_pool[SOUND_GRAIN_TANKS];
    int8_t grain_tank_of[SOUND_FX_BUSES];
    int grain_next;
    int grain_overflow;
    float shw_buf[SOUND_FX_BUSES][SHW_BUF_LEN];
    int shw_widx[SOUND_FX_BUSES];
    ModState shw_mod[SOUND_FX_BUSES];
    float shw_rate[SOUND_FX_BUSES];
    float shw_depth[SOUND_FX_BUSES];
    float shw_mix[SOUND_FX_BUSES];
    float shw_env[SOUND_FX_BUSES];
    float shw_lp[SOUND_FX_BUSES];
    bool shw_used[SOUND_FX_BUSES];
    float gate_thresh[SOUND_FX_BUSES];
    float gate_atk[SOUND_FX_BUSES];
    float gate_rel[SOUND_FX_BUSES];
    float gate_env[SOUND_FX_BUSES];
    float gate_gain[SOUND_FX_BUSES];
    bool gate_used[SOUND_FX_BUSES];
    float sq_down[SOUND_FX_BUSES][3];
    float sq_up[SOUND_FX_BUSES];
    float sq_mix[SOUND_FX_BUSES];
    float sq_mk[SOUND_FX_BUSES];
    float sq_env[SOUND_FX_BUSES][3];
    float sq_loL[SOUND_FX_BUSES];
    float sq_loR[SOUND_FX_BUSES];
    float sq_hiL[SOUND_FX_BUSES];
    float sq_hiR[SOUND_FX_BUSES];
    bool sq_used[SOUND_FX_BUSES];
    int insert_order[SOUND_FX_BUSES][N_INSERTS];
    int insert_order_n[SOUND_FX_BUSES];
    int insert_inst[SOUND_FX_BUSES][N_INSERTS];
    SoundReq req_queue[SOUND_REQ_QUEUE];
    atomic_int req_head;
    atomic_int req_tail;
    SoundReq delayed[SOUND_DELAYED_MAX];
    int delayed_count;
    SoundReq ctx_log[SOUND_CART_CTX][SOUND_CTX_LOG];
    int ctx_log_n[SOUND_CART_CTX];
    int ctx_active;
    int ctx_overflow;
    atomic_int sound_dropped;
    float drop_amount;
    float drop_depth;
    bool drop_used;
    ModState drop_mod;
    float drop_env;
    float drop_prev;
    float drop_lpL;
    float drop_lpR;
    float noise_hiss;
    float noise_hum;
    int noise_mains;
    bool noise_used;
    unsigned int noise_seed;
    /* HAND-ADDED 2026-08-14. Was a FUNCTION-LOCAL static in sound_note_start, which a `#define` alias
     * cannot reach — the declaration itself had to move. Classified CRITICAL, and the reason is that
     * nothing else would have caught it: it is the per-voice seed counter for the stateful LFO shapes
     * (S&H/random), so two instances INTERLEAVING note starts each get a different sequence than they
     * would alone, and every --det replay, ghost and lockstep session silently stops reproducing.
     * refactor-guard sits green through this by construction: one instance cannot observe it. */
    unsigned int lfo_seed_ctr;
    float noise_lpL;
    float noise_lpR;
    float noise_hum_ph;
    ShimVoice shim[SOUND_SHIM_TANKS];
    int8_t shim_bus_of[SOUND_FX_BUSES];
    int shim_next;
    int shim_overflow;
    bool fxmod_any;
    bool fxmod_on[SOUND_FX_BUSES][FXMOD_N];
    bool fxmod_prime[SOUND_FX_BUSES][FXMOD_N];
    float fxmod_cur[SOUND_FX_BUSES][FXMOD_N];
    float fxmod_tgt[SOUND_FX_BUSES][FXMOD_N];
    float fxlfo_rate[SOUND_FX_BUSES][FXMOD_N];
    float fxlfo_depth[SOUND_FX_BUSES][FXMOD_N];
    float fxlfo_ctr[SOUND_FX_BUSES][FXMOD_N];
    float fxlfo_phase[SOUND_FX_BUSES][FXMOD_N];
    int fxlfo_shape[SOUND_FX_BUSES][FXMOD_N];
    ModState fxlfo_mod[SOUND_FX_BUSES][FXMOD_N];
    float vari_bufL[VARI_BUF];
    float vari_bufR[VARI_BUF];
    int vari_wpos;
    float vari_rpos;
    float vari_target;
    float vari_speed;
    bool vari_used;
    bool vari_ever;
    int sound_bpm;
    float beat_accum;
    int beat_now;
    bool beat_just_advanced;
    float steal_tailL;
    float steal_tailR;
    float g_listener_x;
    float g_listener_y;
    float g_listener_vx;
    float g_listener_vy;
    float g_spatial_ref;
    float g_spatial_max;
    float g_spatial_rolloff;
    float g_spatial_c;
    bool emit_on[SOUND_FX_BUSES];
    float emit_x[SOUND_FX_BUSES];
    float emit_y[SOUND_FX_BUSES];
    float emit_vx[SOUND_FX_BUSES];
    float emit_vy[SOUND_FX_BUSES];
    float emit_gain[SOUND_FX_BUSES];
    float emit_gain_t[SOUND_FX_BUSES];
    float emit_pan[SOUND_FX_BUSES];
    float emit_pan_t[SOUND_FX_BUSES];
    float emit_dopp[SOUND_FX_BUSES];
    float emit_dopp_t[SOUND_FX_BUSES];
    float emit_bufL[SOUND_FX_BUSES][EMIT_DL_LEN];
    float emit_bufR[SOUND_FX_BUSES][EMIT_DL_LEN];
    int emit_wpos[SOUND_FX_BUSES];
    float emit_ph[SOUND_FX_BUSES];
    int fx_bus_overflow;
} DeSound;

/* the compile-time defaults — one line per static that carried a non-zero initialiser */
static DeSound de_snd_default = {
    .echo_time = 0.375f * SOUND_SAMPLE_RATE,
    .echo_time_target = 0.375f * SOUND_SAMPLE_RATE,
    .echo_fb = 0.35f,
    .echo_ins_time = 0.375f * SOUND_SAMPLE_RATE,
    .echo_ins_time_target = 0.375f * SOUND_SAMPLE_RATE,
    .echo_ins_fb = 0.35f,
    .echo_ins_tone = 0.55f,
    .g_pan_law = PAN_LINEAR,
    .rvb_spring_disp = SPRING_DISP,
    .rvb_plate_w = PLATE_WIDTH,
    .fx_next_bus = 1,
    .drvins_tone = 0.5f,
    .voc_q1 = 0.2f,
    .voc_mk = 1.2f,
    .voc_nz = 0x1a2b3c4d,
    .voc_nk = 2.6f,
    .am_T = 300.0f,
    .am_scale = 1,
    .am_mode = AM_SNAP,
    .am_nv = 1,
    .am_gain = 1.0f,
    .drop_depth = 0.7f,
    .noise_mains = 60,
    .noise_seed = 0x6D2B79F5u,
    .lfo_seed_ctr = 0x12345u,   // the value its function-local static carried; NOT zero, or every LFO seed shifts
    .shim_next = 1,
    .vari_target = 1.0f,
    .vari_speed = 1.0f,
    .sound_bpm = 120,
    .g_spatial_ref = 24.0f,
    .g_spatial_max = 400.0f,
    .g_spatial_rolloff = 1.0f,
    .g_spatial_c = 340.0f,
};

/* THE POINTER THE MACROS EXPAND THROUGH — thread-local, and defaulted to the template above.
 *
 * Thread-local because a plug-in process runs SEVERAL engines: the seam sets this from the
 * instance on entry and restores it on the way out, so two racks rendering on two threads
 * never see each other. A plain global here would be the UI-thread/audio-thread race the
 * whole refactor exists to remove.
 *
 * The DEFAULT matters as much as the type: a thread that never entered a seam call — the
 * desktop Raylib build, which owns its own main() and never calls de_frame, and raylib's own
 * audio thread calling sound_callback directly — sees the default instance, which IS that
 * host's one engine. That is why the single-engine path is untouched by any of this. */
static _Thread_local DeSound *de_snd = &de_snd_default;

/* the access block: every name the engine already uses, pointed at the context.
 * Step B swaps de_snd for a per-instance pointer; NOTHING below this line changes. */
#define voices               (de_snd->voices)
#define hn_gen               (de_snd->hn_gen)
#define hn_used              (de_snd->hn_used)
#define held_voice           (de_snd->held_voice)
#define scope_buf            (de_snd->scope_buf)
#define scope_w              (de_snd->scope_w)
#define scope_ever           (de_snd->scope_ever)
#define scope2_bufL          (de_snd->scope2_bufL)
#define scope2_bufR          (de_snd->scope2_bufR)
#define scope2_w             (de_snd->scope2_w)
#define scope2_ever          (de_snd->scope2_ever)
#define sound_samples        (de_snd->sound_samples)
#define rec_ring             (de_snd->rec_ring)
#define rec_w                (de_snd->rec_w)
#define rec_total            (de_snd->rec_total)
#define rec_arm              (de_snd->rec_arm)
#define sfx_bank             (de_snd->sfx_bank)
#define instr_bank           (de_snd->instr_bank)
#define user_wave            (de_snd->user_wave)
#define bow_bodies           (de_snd->bow_bodies)
#define bow_body_next        (de_snd->bow_body_next)
#define bow_body_overflow    (de_snd->bow_body_overflow)
#define echo_buf             (de_snd->echo_buf)
#define echo_widx            (de_snd->echo_widx)
#define echo_time            (de_snd->echo_time)
#define echo_time_target     (de_snd->echo_time_target)
#define echo_fb              (de_snd->echo_fb)
#define echo_tone_coef       (de_snd->echo_tone_coef)
#define echo_lp              (de_snd->echo_lp)
#define echo_dc_x1           (de_snd->echo_dc_x1)
#define echo_dc_y1           (de_snd->echo_dc_y1)
#define echo_used            (de_snd->echo_used)
#define echo_ins_buf         (de_snd->echo_ins_buf)
#define echo_ins_widx        (de_snd->echo_ins_widx)
#define echo_ins_time        (de_snd->echo_ins_time)
#define echo_ins_time_target (de_snd->echo_ins_time_target)
#define echo_ins_fb          (de_snd->echo_ins_fb)
#define echo_ins_tone_coef   (de_snd->echo_ins_tone_coef)
#define echo_ins_lp          (de_snd->echo_ins_lp)
#define echo_ins_mix         (de_snd->echo_ins_mix)
#define echo_ins_used        (de_snd->echo_ins_used)
#define echo_ins_bbd         (de_snd->echo_ins_bbd)
#define echo_ins_tone        (de_snd->echo_ins_tone)
#define echo_ins_wph         (de_snd->echo_ins_wph)
#define echo_ins_fph         (de_snd->echo_ins_fph)
#define g_pan_law            (de_snd->g_pan_law)
#define rvb_spring           (de_snd->rvb_spring)
#define rvb_spring_disp      (de_snd->rvb_spring_disp)
#define rvb_plate            (de_snd->rvb_plate)
#define rvb_plate_w          (de_snd->rvb_plate_w)
#define rvb_tanks            (de_snd->rvb_tanks)
#define reverb_used          (de_snd->reverb_used)
#define fx_next_bus          (de_snd->fx_next_bus)
#define bus_tank             (de_snd->bus_tank)
#define tank_bus             (de_snd->tank_bus)
#define rvb_bus_overflow     (de_snd->rvb_bus_overflow)
#define cho_buf              (de_snd->cho_buf)
#define cho_widx             (de_snd->cho_widx)
#define cho_phase            (de_snd->cho_phase)
#define cho_rate             (de_snd->cho_rate)
#define cho_depth            (de_snd->cho_depth)
#define cho_mix              (de_snd->cho_mix)
#define cho_used             (de_snd->cho_used)
#define flg_buf              (de_snd->flg_buf)
#define flg_widx             (de_snd->flg_widx)
#define flg_phase            (de_snd->flg_phase)
#define flg_rate             (de_snd->flg_rate)
#define flg_depth            (de_snd->flg_depth)
#define flg_fb               (de_snd->flg_fb)
#define flg_mix              (de_snd->flg_mix)
#define flg_dc_x1            (de_snd->flg_dc_x1)
#define flg_dc_y1            (de_snd->flg_dc_y1)
#define flg_used             (de_snd->flg_used)
#define tape_bufL            (de_snd->tape_bufL)
#define tape_bufR            (de_snd->tape_bufR)
#define tape_widx            (de_snd->tape_widx)
#define tape_wph             (de_snd->tape_wph)
#define tape_fph             (de_snd->tape_fph)
#define tape_lpL             (de_snd->tape_lpL)
#define tape_lpR             (de_snd->tape_lpR)
#define tape_wow             (de_snd->tape_wow)
#define tape_flut            (de_snd->tape_flut)
#define tape_sat             (de_snd->tape_sat)
#define tape_used            (de_snd->tape_used)
#define crush_bits           (de_snd->crush_bits)
#define crush_rate           (de_snd->crush_rate)
#define crush_mix            (de_snd->crush_mix)
#define crush_holdL          (de_snd->crush_holdL)
#define crush_holdR          (de_snd->crush_holdR)
#define crush_cnt            (de_snd->crush_cnt)
#define crush_used           (de_snd->crush_used)
#define drvins_amt           (de_snd->drvins_amt)
#define drvins_mode          (de_snd->drvins_mode)
#define drvins_mix           (de_snd->drvins_mix)
#define drvins_used          (de_snd->drvins_used)
#define drvins_dcx           (de_snd->drvins_dcx)
#define drvins_dcy           (de_snd->drvins_dcy)
#define drvins_voice         (de_snd->drvins_voice)
#define drvins_tone          (de_snd->drvins_tone)
#define drvins_lp1           (de_snd->drvins_lp1)
#define drvins_lp2           (de_snd->drvins_lp2)
#define wah_env              (de_snd->wah_env)
#define wah_ic1              (de_snd->wah_ic1)
#define wah_ic2              (de_snd->wah_ic2)
#define wah_sens             (de_snd->wah_sens)
#define wah_res              (de_snd->wah_res)
#define wah_mix              (de_snd->wah_mix)
#define wah_used             (de_snd->wah_used)
#define wah_lfo_rate         (de_snd->wah_lfo_rate)
#define wah_lfo_phase        (de_snd->wah_lfo_phase)
#define filt_mode            (de_snd->filt_mode)
#define filt_cut             (de_snd->filt_cut)
#define filt_res             (de_snd->filt_res)
#define filt_ic1L            (de_snd->filt_ic1L)
#define filt_ic2L            (de_snd->filt_ic2L)
#define filt_ic1R            (de_snd->filt_ic1R)
#define filt_ic2R            (de_snd->filt_ic2R)
#define filt_used            (de_snd->filt_used)
#define fmt_freq             (de_snd->fmt_freq)
#define fmt_k                (de_snd->fmt_k)
#define fmt_amp              (de_snd->fmt_amp)
#define fmt_ic1              (de_snd->fmt_ic1)
#define fmt_ic2              (de_snd->fmt_ic2)
#define fmt_mix              (de_snd->fmt_mix)
#define fmt_used             (de_snd->fmt_used)
#define eq_low_g             (de_snd->eq_low_g)
#define eq_mid_g             (de_snd->eq_mid_g)
#define eq_high_g            (de_snd->eq_high_g)
#define eq_loL               (de_snd->eq_loL)
#define eq_loR               (de_snd->eq_loR)
#define eq_hiL               (de_snd->eq_hiL)
#define eq_hiR               (de_snd->eq_hiR)
#define eq_used              (de_snd->eq_used)
#define trem_rate            (de_snd->trem_rate)
#define trem_depth           (de_snd->trem_depth)
#define trem_shape           (de_snd->trem_shape)
#define trem_phase           (de_snd->trem_phase)
#define trem_md              (de_snd->trem_md)
#define trem_used            (de_snd->trem_used)
#define pan_rate             (de_snd->pan_rate)
#define pan_depth            (de_snd->pan_depth)
#define pan_shape            (de_snd->pan_shape)
#define pan_phase            (de_snd->pan_phase)
#define pan_md               (de_snd->pan_md)
#define pan_used             (de_snd->pan_used)
#define rm_freq              (de_snd->rm_freq)
#define rm_mix               (de_snd->rm_mix)
#define rm_phase             (de_snd->rm_phase)
#define rm_used              (de_snd->rm_used)
#define phaser_rate          (de_snd->phaser_rate)
#define phaser_depth         (de_snd->phaser_depth)
#define phaser_fb            (de_snd->phaser_fb)
#define phaser_mix           (de_snd->phaser_mix)
#define phaser_stages        (de_snd->phaser_stages)
#define phaser_phase         (de_snd->phaser_phase)
#define phaser_stL           (de_snd->phaser_stL)
#define phaser_pvL           (de_snd->phaser_pvL)
#define phaser_stR           (de_snd->phaser_stR)
#define phaser_pvR           (de_snd->phaser_pvR)
#define phaser_dcx           (de_snd->phaser_dcx)
#define phaser_dcy           (de_snd->phaser_dcy)
#define phaser_used          (de_snd->phaser_used)
#define phaser_optical       (de_snd->phaser_optical)
#define leslie_speed         (de_snd->leslie_speed)
#define leslie_drive         (de_snd->leslie_drive)
#define leslie_bal           (de_snd->leslie_bal)
#define leslie_dopp          (de_snd->leslie_dopp)
#define leslie_mix           (de_snd->leslie_mix)
#define leslie_used          (de_snd->leslie_used)
#define leslie_hornPh        (de_snd->leslie_hornPh)
#define leslie_drumPh        (de_snd->leslie_drumPh)
#define leslie_hornRt        (de_snd->leslie_hornRt)
#define leslie_drumRt        (de_snd->leslie_drumRt)
#define leslie_xoL           (de_snd->leslie_xoL)
#define leslie_xoR           (de_snd->leslie_xoR)
#define leslie_wpos          (de_snd->leslie_wpos)
#define leslie_bufL          (de_snd->leslie_bufL)
#define leslie_bufR          (de_snd->leslie_bufR)
#define sc                   (de_snd->sc)
#define sc_key_lvl           (de_snd->sc_key_lvl)
#define voc_on               (de_snd->voc_on)
#define voc_mix              (de_snd->voc_mix)
#define voc_mod              (de_snd->voc_mod)
#define voc_f                (de_snd->voc_f)
#define voc_q1               (de_snd->voc_q1)
#define voc_mk               (de_snd->voc_mk)
#define voc_c_lp             (de_snd->voc_c_lp)
#define voc_c_bp             (de_snd->voc_c_bp)
#define voc_m_lp             (de_snd->voc_m_lp)
#define voc_m_bp             (de_snd->voc_m_bp)
#define voc_env              (de_snd->voc_env)
#define voc_uv_amt           (de_snd->voc_uv_amt)
#define voc_uv               (de_snd->voc_uv)
#define voc_nz               (de_snd->voc_nz)
#define voc_nk               (de_snd->voc_nk)
#define voc_n_lp             (de_snd->voc_n_lp)
#define voc_n_bp             (de_snd->voc_n_bp)
#define extin_mon_on         (de_snd->extin_mon_on)
#define extin_mon_gain       (de_snd->extin_mon_gain)
#define voc_mic_amt          (de_snd->voc_mic_amt)
#define am_inbuf             (de_snd->am_inbuf)
#define am_outbuf            (de_snd->am_outbuf)
#define am_nrm               (de_snd->am_nrm)
#define am_w                 (de_snd->am_w)
#define am_T                 (de_snd->am_T)
#define am_ea                (de_snd->am_ea)
#define am_eps               (de_snd->am_eps)
#define am_epi               (de_snd->am_epi)
#define am_pd                (de_snd->am_pd)
#define am_amt               (de_snd->am_amt)
#define am_on                (de_snd->am_on)
#define am_root              (de_snd->am_root)
#define am_scale             (de_snd->am_scale)
#define am_ts                (de_snd->am_ts)
#define am_mode              (de_snd->am_mode)
#define am_nv                (de_snd->am_nv)
#define am_semis             (de_snd->am_semis)
#define am_gain              (de_snd->am_gain)
#define grain_pool           (de_snd->grain_pool)
#define grain_tank_of        (de_snd->grain_tank_of)
#define grain_next           (de_snd->grain_next)
#define grain_overflow       (de_snd->grain_overflow)
#define shw_buf              (de_snd->shw_buf)
#define shw_widx             (de_snd->shw_widx)
#define shw_mod              (de_snd->shw_mod)
#define shw_rate             (de_snd->shw_rate)
#define shw_depth            (de_snd->shw_depth)
#define shw_mix              (de_snd->shw_mix)
#define shw_env              (de_snd->shw_env)
#define shw_lp               (de_snd->shw_lp)
#define shw_used             (de_snd->shw_used)
#define gate_thresh          (de_snd->gate_thresh)
#define gate_atk             (de_snd->gate_atk)
#define gate_rel             (de_snd->gate_rel)
#define gate_env             (de_snd->gate_env)
#define gate_gain            (de_snd->gate_gain)
#define gate_used            (de_snd->gate_used)
#define sq_down              (de_snd->sq_down)
#define sq_up                (de_snd->sq_up)
#define sq_mix               (de_snd->sq_mix)
#define sq_mk                (de_snd->sq_mk)
#define sq_env               (de_snd->sq_env)
#define sq_loL               (de_snd->sq_loL)
#define sq_loR               (de_snd->sq_loR)
#define sq_hiL               (de_snd->sq_hiL)
#define sq_hiR               (de_snd->sq_hiR)
#define sq_used              (de_snd->sq_used)
#define insert_order         (de_snd->insert_order)
#define insert_order_n       (de_snd->insert_order_n)
#define insert_inst          (de_snd->insert_inst)
#define req_queue            (de_snd->req_queue)
#define req_head             (de_snd->req_head)
#define req_tail             (de_snd->req_tail)
#define delayed              (de_snd->delayed)
#define delayed_count        (de_snd->delayed_count)
#define ctx_log              (de_snd->ctx_log)
#define ctx_log_n            (de_snd->ctx_log_n)
#define ctx_active           (de_snd->ctx_active)
#define ctx_overflow         (de_snd->ctx_overflow)
#define sound_dropped        (de_snd->sound_dropped)
#define drop_amount          (de_snd->drop_amount)
#define drop_depth           (de_snd->drop_depth)
#define drop_used            (de_snd->drop_used)
#define drop_mod             (de_snd->drop_mod)
#define drop_env             (de_snd->drop_env)
#define drop_prev            (de_snd->drop_prev)
#define drop_lpL             (de_snd->drop_lpL)
#define drop_lpR             (de_snd->drop_lpR)
#define noise_hiss           (de_snd->noise_hiss)
#define noise_hum            (de_snd->noise_hum)
#define noise_mains          (de_snd->noise_mains)
#define noise_used           (de_snd->noise_used)
#define noise_seed           (de_snd->noise_seed)
#define lfo_seed_ctr         (de_snd->lfo_seed_ctr)
#define noise_lpL            (de_snd->noise_lpL)
#define noise_lpR            (de_snd->noise_lpR)
#define noise_hum_ph         (de_snd->noise_hum_ph)
#define shim                 (de_snd->shim)
#define shim_bus_of          (de_snd->shim_bus_of)
#define shim_next            (de_snd->shim_next)
#define shim_overflow        (de_snd->shim_overflow)
#define fxmod_any            (de_snd->fxmod_any)
#define fxmod_on             (de_snd->fxmod_on)
#define fxmod_prime          (de_snd->fxmod_prime)
#define fxmod_cur            (de_snd->fxmod_cur)
#define fxmod_tgt            (de_snd->fxmod_tgt)
#define fxlfo_rate           (de_snd->fxlfo_rate)
#define fxlfo_depth          (de_snd->fxlfo_depth)
#define fxlfo_ctr            (de_snd->fxlfo_ctr)
#define fxlfo_phase          (de_snd->fxlfo_phase)
#define fxlfo_shape          (de_snd->fxlfo_shape)
#define fxlfo_mod            (de_snd->fxlfo_mod)
#define vari_bufL            (de_snd->vari_bufL)
#define vari_bufR            (de_snd->vari_bufR)
#define vari_wpos            (de_snd->vari_wpos)
#define vari_rpos            (de_snd->vari_rpos)
#define vari_target          (de_snd->vari_target)
#define vari_speed           (de_snd->vari_speed)
#define vari_used            (de_snd->vari_used)
#define vari_ever            (de_snd->vari_ever)
#define sound_bpm            (de_snd->sound_bpm)
#define beat_accum           (de_snd->beat_accum)
#define beat_now             (de_snd->beat_now)
#define beat_just_advanced   (de_snd->beat_just_advanced)
#define steal_tailL          (de_snd->steal_tailL)
#define steal_tailR          (de_snd->steal_tailR)
#define g_listener_x         (de_snd->g_listener_x)
#define g_listener_y         (de_snd->g_listener_y)
#define g_listener_vx        (de_snd->g_listener_vx)
#define g_listener_vy        (de_snd->g_listener_vy)
#define g_spatial_ref        (de_snd->g_spatial_ref)
#define g_spatial_max        (de_snd->g_spatial_max)
#define g_spatial_rolloff    (de_snd->g_spatial_rolloff)
#define g_spatial_c          (de_snd->g_spatial_c)
#define emit_on              (de_snd->emit_on)
#define emit_x               (de_snd->emit_x)
#define emit_y               (de_snd->emit_y)
#define emit_vx              (de_snd->emit_vx)
#define emit_vy              (de_snd->emit_vy)
#define emit_gain            (de_snd->emit_gain)
#define emit_gain_t          (de_snd->emit_gain_t)
#define emit_pan             (de_snd->emit_pan)
#define emit_pan_t           (de_snd->emit_pan_t)
#define emit_dopp            (de_snd->emit_dopp)
#define emit_dopp_t          (de_snd->emit_dopp_t)
#define emit_bufL            (de_snd->emit_bufL)
#define emit_bufR            (de_snd->emit_bufR)
#define emit_wpos            (de_snd->emit_wpos)
#define emit_ph              (de_snd->emit_ph)
#define fx_bus_overflow      (de_snd->fx_bus_overflow)

#endif
