/* studio_ctx.h — GENERATED by tools/ctx-gen.js. Do not edit by hand.
 *
 * The per-instance engine context (docs/design/engine-context.md). An AUv3 puts every plug-in
 * instance in ONE process, so state that lives in file-scope statics is shared by every
 * instance — which is why two DAW tracks fight over one rack. These members used to be those
 * statics; the macro block at the bottom means the engine code reads exactly as it did before.
 *
 * The default instance below is a `static` with DESIGNATED INITIALISERS, so every value is
 * still set at compile time exactly as it was, and the rest is still zeroed static storage.
 * That is what makes this a pure move with no init-order risk: nothing can read a member
 * before it is set, because the linker sets it. A real per-instance context is then created
 * by copying this template, which is exact by construction.
 */
#ifndef DE_STUDIO_CTX_H
#define DE_STUDIO_CTX_H

/* self-contained: the members use these, and depending on where this header lands in
 * sound.h they may not have been pulled in yet. */
#include <stdint.h>
#include <stdbool.h>
#include <stdatomic.h>

/* MOVED here from studio.c: the sizes and constants the members below are written in.
 * They have to precede the struct, and moving a #define earlier is always safe because a
 * macro body is only text until it is expanded. */
#define PALETTE_SIZE 64
#ifndef SCALE
#define SCALE 4
#endif
#ifndef SW_CANVAS_DEFAULT
#define SW_CANVAS_DEFAULT 0
#endif
#define BTN_COUNT 8
#define KEY_CLAIM_MAX 512
#ifndef TOUCH_CONTROLS_DEFAULT
#define TOUCH_CONTROLS_DEFAULT 0
#endif
#define VT_MAX           16
/* fb_w / fb_h / de_sw / de_sh — the canvas dimensions — are per-instance as of 2026-08-14, ADDED
 * BY HAND at the bottom of the struct with the rest of the framebuffer group. The generator still
 * cannot produce them (their siblings sw_dst/sw_world_buf sit inside `#ifdef DE_NO_RAYLIB`, and it
 * reads one configuration), which is why they are not in the generated run above. The warning that
 * used to live here still stands and is repeated where they are declared: moving HALF this group is
 * worse than moving none — per-instance dimensions with a shared destination buffer made cls()
 * write fb_w*fb_h pixels into another instance's smaller canvas. */
typedef struct {
    char name[24];
    char value[40];
    int  age;                    // frames since last touched
} WatchEntry;
#define WATCH_MAX 40

typedef struct {
    GameRect game_rect;
    RenderTexture2D canvas;
    RenderTexture2D canvas_snap;
    int active_font_id;
    DeColor palette[PALETTE_SIZE];
    DeColor base_palette[PALETTE_SIZE];
    RenderTexture2D blend_snap;
    bool pal_active;
    float cur_pal_rgb[PALETTE_SIZE * 3];
    bool cur_pal_dirty;
    int blend_mode;
    unsigned char blend_lut[5][PALETTE_SIZE][PALETTE_SIZE];
    bool blend_lut_ready;
    bool sw_colorkey_on;
    DeColor sw_colorkey_rgb;
    RenderTexture2D smooth_rt;
    bool smooth_on;
    bool smooth_rt_ok;
    bool smooth_capturing;
    float smooth_zoom_amt;
    float fade_amt;
    float shake_amt;
    float frame_dt;
    double last_time;
    char text_buf[32];
    char paste_buf[256];
    bool fp_on;
    int fp_global;
    int fp_hole;
    int fp_anc_x;
    int fp_anc_y;
    bool sw_canvas_active;
    bool sw_force_gpu;
    uint32_t *sw_cbuf;
    int safe_l;
    int safe_t;
    int safe_r;
    int safe_b;
    int safe_ref_w;
    int safe_ref_h;
    float de_backing;
    bool btn_curr[2][BTN_COUNT];
    bool btn_prev[2][BTN_COUNT];
    uint8_t map_data[MAP_W * MAP_H];
    int map_scale_factor;
    int frame_count;
    bool pause_active;
    int pause_sel;
    bool key_claimed[KEY_CLAIM_MAX];
    bool show_touch_ui;
    int touch_move_mode;
    int touch_n_buttons;
    float ctrl_scale;
    float ctrl_scale_btn;
    int place_mode;
    int tband_x;
    int tband_y;
    int tband_w;
    int tband_h;
    bool touch_debug_on;
    bool net_debug_on;
    int stick_touch_id;
    float stick_base_x;
    float stick_base_y;
    float stick_knob_x;
    float stick_knob_y;
    float stick_home_x;
    float stick_home_y;
    int sgz_x;
    int sgz_y;
    int sgz_w;
    int sgz_h;
    int btn_cx[4];
    int btn_cy[4];
    int dpad_touch_id;
    bool dpad_up;
    bool dpad_down;
    bool dpad_left;
    bool dpad_right;
    int dpad_sector;
    int vt_count;
    Vector2 vt_pos[VT_MAX];
    int vt_id[VT_MAX];
    int vt_prev_count;
    int vt_prev_id[VT_MAX];
    Vector2 vt_prev_pos[VT_MAX];
    int vt_ended_count;
    int vt_ended_id[VT_MAX];
    Vector2 vt_ended_pos[VT_MAX];
    Camera2D cam;
    bool cam_active;
    bool clip_active;
    int clip_cx;
    int clip_cy;
    int clip_cw;
    int clip_ch;
    Image pget_snapshot;
    bool pget_snapshot_valid;
    bool pget_enabled;
    bool pget_warned;
    WatchEntry watches[WATCH_MAX];
    int watch_count;
    bool watch_show;
    char save_dir_[512];   // renamed: host-thread code needs `v->save_dir_`, which the macro below would otherwise rewrite
    int last_cls_color;
    double timer_base;
    int sav_data[64];
    bool sav_loaded;
    unsigned char *de_state_mem;
    int de_state_cap;
    int kv_count;
    bool kv_loaded;

    /* ══ HAND-ADDED (2026-08-14): THE FRAMEBUFFER + PRESENT GROUP ═══════════════════════════════
     * Not from the generator, and it could not be: `sw_dst`/`sw_world_buf` live inside
     * `#ifdef DE_NO_RAYLIB`, and ctx-gen reads ONE configuration and refuses anything conditional.
     * It also refuses to re-run on studio.c at all (it would rebuild the context from the handful
     * of statics that remain), so this header is now partly hand-maintained. Add here, not there.
     *
     * ⚠ THIS GROUP MOVES TOGETHER OR NOT AT ALL. `sw_cbuf` went per-instance in an earlier batch
     * while the dimensions that SIZE it stayed shared, and `cls()` promptly wrote fb_w*fb_h pixels
     * into another instance's smaller canvas. Every member below is either a canvas dimension, a
     * buffer sized by one, or a snapshot of one.
     *
     * WHY IT MATTERS: this is what made two open plug-in panels flicker. Both views pushed their
     * own size into the ONE `de_pend_*` slot (last writer won, every frame), and both blitted the
     * ONE `de_pres_*` buffer, which alternated between the two engines' renders. */
    int fb_w, fb_h;              // the ALLOCATED framebuffer (>= the active canvas)
    int de_sw, de_sh;            // the ACTIVE canvas — screen_w()/screen_h()
    uint32_t *sw_dst;            // → sw_cbuf, or sw_world_buf while a rotated camera_ex is open
    uint32_t *sw_world_buf;      // the rotation world layer, sized alongside sw_cbuf

    /* the published frame (a seqlock — see de_publish_frame). Grow-only; the old allocation is
     * deliberately leaked because a reader on another thread may be mid-copy out of it. */
    uint32_t * _Atomic pres_buf;
    size_t     pres_cap;      // in pixels; engine thread only
    atomic_int pres_seq;      // odd = a publish is in progress
    atomic_int pres_w, pres_h;

    /* the host→engine deferred requests. Written from the HOST's layout thread, applied at the top
     * of de_frame. Idempotent state rather than events, so last-writer-wins is correct — but only
     * WITHIN one instance, which is exactly what was broken. */
    atomic_int pend;                                    // bit 0 = canvas, 1 = safe area, 2 = backing scale
    atomic_int pend_w, pend_h;
    atomic_int pend_sl, pend_st, pend_sr, pend_sb;
    atomic_int pend_bs;                                 // backing scale × 256 (an int keeps it lock-free everywhere)
} DeVideo;

/* the compile-time defaults — one line per static that carried a non-zero initialiser */
static DeVideo de_vid_default = {
    .game_rect = { 0.0f, 0.0f, (float)SCALE },
    .active_font_id = FONT_NORMAL,
    .cur_pal_dirty = true,
    .blend_mode = BLEND_NONE,
    .smooth_zoom_amt = 1.0f,
    .fp_hole = -1,
    .sw_canvas_active = SW_CANVAS_DEFAULT,
    .de_backing = 2.0f,
    .map_scale_factor = 1,
    .show_touch_ui = TOUCH_CONTROLS_DEFAULT,
    .touch_move_mode = TOUCH_ANALOG,
    .touch_n_buttons = 2,
    .ctrl_scale = 1.0f,
    .ctrl_scale_btn = 1.0f,
    .place_mode = PLACE_OVERLAY,
    .stick_touch_id = -1,
    .dpad_touch_id = -1,
    .dpad_sector = -1,
    .cam = {                                   .offset   = { SCREEN_W / 2.0f, SCREEN_H / 2.0f },     .target   = { SCREEN_W / 2.0f, SCREEN_H / 2.0f },     .rotation = 0.0f,     .zoom     = 1.0f, },
    .pget_snapshot = (Image){0},
    .watch_show = true,
    .save_dir_ = ".",
    // the hand-added framebuffer group: the canvas boots at the compiled-in size, as it always did
    .fb_w = SCREEN_W, .fb_h = SCREEN_H,
    .de_sw = SCREEN_W, .de_sh = SCREEN_H,
};

/* THE POINTER THE MACROS EXPAND THROUGH — thread-local, and defaulted to the template above.
 *
 * Thread-local because a plug-in process runs SEVERAL engines: the seam sets this from the
 * instance on entry and restores it on the way out, so two racks rendering on two threads
 * never see each other. A plain global here would be the UI-thread/audio-thread race the
 * whole refactor exists to remove.
 *
 * The DEFAULT matters as much as the type: a thread that never entered a seam call — the
 * desktop Raylib build, which owns its own main() and never calls de_frame, and raylib's own
 * audio thread calling sound_callback directly — sees the default instance, which IS that
 * host's one engine. That is why the single-engine path is untouched by any of this. */
static _Thread_local DeVideo *de_vid = &de_vid_default;

/* the access block: every name the engine already uses, pointed at the context.
 * Step B swaps de_vid for a per-instance pointer; NOTHING below this line changes. */
#define game_rect           (de_vid->game_rect)
#define canvas              (de_vid->canvas)
#define canvas_snap         (de_vid->canvas_snap)
#define active_font_id      (de_vid->active_font_id)
#define palette             (de_vid->palette)
#define base_palette        (de_vid->base_palette)
#define blend_snap          (de_vid->blend_snap)
#define pal_active          (de_vid->pal_active)
#define cur_pal_rgb         (de_vid->cur_pal_rgb)
#define cur_pal_dirty       (de_vid->cur_pal_dirty)
#define blend_mode          (de_vid->blend_mode)
#define blend_lut           (de_vid->blend_lut)
#define blend_lut_ready     (de_vid->blend_lut_ready)
#define sw_colorkey_on      (de_vid->sw_colorkey_on)
#define sw_colorkey_rgb     (de_vid->sw_colorkey_rgb)
#define smooth_rt           (de_vid->smooth_rt)
#define smooth_on           (de_vid->smooth_on)
#define smooth_rt_ok        (de_vid->smooth_rt_ok)
#define smooth_capturing    (de_vid->smooth_capturing)
#define smooth_zoom_amt     (de_vid->smooth_zoom_amt)
#define fade_amt            (de_vid->fade_amt)
#define shake_amt           (de_vid->shake_amt)
#define frame_dt            (de_vid->frame_dt)
#define last_time           (de_vid->last_time)
#define text_buf            (de_vid->text_buf)
#define paste_buf           (de_vid->paste_buf)
#define fp_on               (de_vid->fp_on)
#define fp_global           (de_vid->fp_global)
#define fp_hole             (de_vid->fp_hole)
#define fp_anc_x            (de_vid->fp_anc_x)
#define fp_anc_y            (de_vid->fp_anc_y)
#define sw_canvas_active    (de_vid->sw_canvas_active)
#define sw_force_gpu        (de_vid->sw_force_gpu)
#define sw_cbuf             (de_vid->sw_cbuf)
#define safe_l              (de_vid->safe_l)
#define safe_t              (de_vid->safe_t)
#define safe_r              (de_vid->safe_r)
#define safe_b              (de_vid->safe_b)
#define safe_ref_w          (de_vid->safe_ref_w)
#define safe_ref_h          (de_vid->safe_ref_h)
#define de_backing          (de_vid->de_backing)
#define btn_curr            (de_vid->btn_curr)
#define btn_prev            (de_vid->btn_prev)
#define map_data            (de_vid->map_data)
#define map_scale_factor    (de_vid->map_scale_factor)
#define frame_count         (de_vid->frame_count)
#define pause_active        (de_vid->pause_active)
#define pause_sel           (de_vid->pause_sel)
#define key_claimed         (de_vid->key_claimed)
#define show_touch_ui       (de_vid->show_touch_ui)
#define touch_move_mode     (de_vid->touch_move_mode)
#define touch_n_buttons     (de_vid->touch_n_buttons)
#define ctrl_scale          (de_vid->ctrl_scale)
#define ctrl_scale_btn      (de_vid->ctrl_scale_btn)
#define place_mode          (de_vid->place_mode)
#define tband_x             (de_vid->tband_x)
#define tband_y             (de_vid->tband_y)
#define tband_w             (de_vid->tband_w)
#define tband_h             (de_vid->tband_h)
#define touch_debug_on      (de_vid->touch_debug_on)
#define net_debug_on        (de_vid->net_debug_on)
#define stick_touch_id      (de_vid->stick_touch_id)
#define stick_base_x        (de_vid->stick_base_x)
#define stick_base_y        (de_vid->stick_base_y)
#define stick_knob_x        (de_vid->stick_knob_x)
#define stick_knob_y        (de_vid->stick_knob_y)
#define stick_home_x        (de_vid->stick_home_x)
#define stick_home_y        (de_vid->stick_home_y)
#define sgz_x               (de_vid->sgz_x)
#define sgz_y               (de_vid->sgz_y)
#define sgz_w               (de_vid->sgz_w)
#define sgz_h               (de_vid->sgz_h)
#define btn_cx              (de_vid->btn_cx)
#define btn_cy              (de_vid->btn_cy)
#define dpad_touch_id       (de_vid->dpad_touch_id)
#define dpad_up             (de_vid->dpad_up)
#define dpad_down           (de_vid->dpad_down)
#define dpad_left           (de_vid->dpad_left)
#define dpad_right          (de_vid->dpad_right)
#define dpad_sector         (de_vid->dpad_sector)
#define vt_count            (de_vid->vt_count)
#define vt_pos              (de_vid->vt_pos)
#define vt_id               (de_vid->vt_id)
#define vt_prev_count       (de_vid->vt_prev_count)
#define vt_prev_id          (de_vid->vt_prev_id)
#define vt_prev_pos         (de_vid->vt_prev_pos)
#define vt_ended_count      (de_vid->vt_ended_count)
#define vt_ended_id         (de_vid->vt_ended_id)
#define vt_ended_pos        (de_vid->vt_ended_pos)
#define cam                 (de_vid->cam)
#define cam_active          (de_vid->cam_active)
#define clip_active         (de_vid->clip_active)
#define clip_cx             (de_vid->clip_cx)
#define clip_cy             (de_vid->clip_cy)
#define clip_cw             (de_vid->clip_cw)
#define clip_ch             (de_vid->clip_ch)
#define pget_snapshot       (de_vid->pget_snapshot)
#define pget_snapshot_valid (de_vid->pget_snapshot_valid)
#define pget_enabled        (de_vid->pget_enabled)
#define pget_warned         (de_vid->pget_warned)
#define watches             (de_vid->watches)
#define watch_count         (de_vid->watch_count)
#define watch_show          (de_vid->watch_show)
#define save_dir            (de_vid->save_dir_)
#define last_cls_color      (de_vid->last_cls_color)
#define timer_base          (de_vid->timer_base)
#define sav_data            (de_vid->sav_data)
#define sav_loaded          (de_vid->sav_loaded)
#define de_state_mem        (de_vid->de_state_mem)
#define de_state_cap        (de_vid->de_state_cap)
#define kv_count            (de_vid->kv_count)
#define kv_loaded           (de_vid->kv_loaded)

/* the hand-added framebuffer + present group. `sw_dst` is NOT here: it forks on the renderer
 * (a real pointer under DE_NO_RAYLIB, a plain alias for sw_cbuf otherwise), so its definition
 * stays in studio.c beside the fork it belongs to. */
#define fb_w                (de_vid->fb_w)
#define fb_h                (de_vid->fb_h)
#define de_sw               (de_vid->de_sw)
#define de_sh               (de_vid->de_sh)
#define sw_world_buf        (de_vid->sw_world_buf)
#define de_pres_buf         (de_vid->pres_buf)
#define de_pres_cap         (de_vid->pres_cap)
#define de_pres_seq         (de_vid->pres_seq)
#define de_pres_w           (de_vid->pres_w)
#define de_pres_h           (de_vid->pres_h)
#define de_pend             (de_vid->pend)
#define de_pend_w           (de_vid->pend_w)
#define de_pend_h           (de_vid->pend_h)
#define de_pend_sl          (de_vid->pend_sl)
#define de_pend_st          (de_vid->pend_st)
#define de_pend_sr          (de_vid->pend_sr)
#define de_pend_sb          (de_vid->pend_sb)
#define de_pend_bs          (de_vid->pend_bs)

#endif
