/* sync_ctx.h — GENERATED by tools/ctx-gen.js. Do not edit by hand.
 *
 * The per-instance engine context (docs/design/engine-context.md). An AUv3 puts every plug-in
 * instance in ONE process, so state that lives in file-scope statics is shared by every
 * instance — which is why two DAW tracks fight over one rack. These members used to be those
 * statics; the macro block at the bottom means the engine code reads exactly as it did before.
 *
 * The default instance below is a `static` with DESIGNATED INITIALISERS, so every value is
 * still set at compile time exactly as it was, and the rest is still zeroed static storage.
 * That is what makes this a pure move with no init-order risk: nothing can read a member
 * before it is set, because the linker sets it. A real per-instance context is then created
 * by copying this template, which is exact by construction.
 */
#ifndef DE_SYNC_CTX_H
#define DE_SYNC_CTX_H

/* self-contained: the members use these, and depending on where this header lands in
 * sound.h they may not have been pulled in yet. */
#include <stdint.h>
#include <stdbool.h>
#include <stdatomic.h>

/* MOVED here from sync.h: the sizes and constants the members below are written in.
 * They have to precede the struct, and moving a #define earlier is always safe because a
 * macro body is only text until it is expanded. */
#define SYNC_TIMEOUT 2.0f    // seconds of silence before we call the clock gone

typedef struct {
    volatile uint32_t sync_p_ticks;
    volatile uint32_t sync_p_msgs;
    volatile int sync_p_run;
    volatile int sync_p_tseen;
    volatile int sync_p_abs;
    volatile double sync_p_beats;
    volatile double sync_p_bpm;
    double sync_c_beats;
    double sync_c_bpm;
    bool sync_c_active;
    bool sync_c_playing;
    bool sync_c_tseen;
    uint32_t sync_c_last_msgs;
    uint32_t sync_c_last_ticks;
    float sync_c_quiet;
    double sync_c_win_t;
    double sync_c_win_n;
    double sync_c_pend;
    float sync_synth_bpm;
    double sync_synth_acc;
    uint32_t sync_synth_ticks;
} DeSync;

/* the compile-time defaults — one line per static that carried a non-zero initialiser */
static DeSync de_sync_default = {
    .sync_c_quiet = SYNC_TIMEOUT * 2,
};

/* THE POINTER THE MACROS EXPAND THROUGH — thread-local, and defaulted to the template above.
 *
 * Thread-local because a plug-in process runs SEVERAL engines: the seam sets this from the
 * instance on entry and restores it on the way out, so two racks rendering on two threads
 * never see each other. A plain global here would be the UI-thread/audio-thread race the
 * whole refactor exists to remove.
 *
 * The DEFAULT matters as much as the type: a thread that never entered a seam call — the
 * desktop Raylib build, which owns its own main() and never calls de_frame, and raylib's own
 * audio thread calling sound_callback directly — sees the default instance, which IS that
 * host's one engine. That is why the single-engine path is untouched by any of this. */
static _Thread_local DeSync *de_sync = &de_sync_default;

/* the access block: every name the engine already uses, pointed at the context.
 * Step B swaps de_sync for a per-instance pointer; NOTHING below this line changes. */
#define sync_p_ticks      (de_sync->sync_p_ticks)
#define sync_p_msgs       (de_sync->sync_p_msgs)
#define sync_p_run        (de_sync->sync_p_run)
#define sync_p_tseen      (de_sync->sync_p_tseen)
#define sync_p_abs        (de_sync->sync_p_abs)
#define sync_p_beats      (de_sync->sync_p_beats)
#define sync_p_bpm        (de_sync->sync_p_bpm)
#define sync_c_beats      (de_sync->sync_c_beats)
#define sync_c_bpm        (de_sync->sync_c_bpm)
#define sync_c_active     (de_sync->sync_c_active)
#define sync_c_playing    (de_sync->sync_c_playing)
#define sync_c_tseen      (de_sync->sync_c_tseen)
#define sync_c_last_msgs  (de_sync->sync_c_last_msgs)
#define sync_c_last_ticks (de_sync->sync_c_last_ticks)
#define sync_c_quiet      (de_sync->sync_c_quiet)
#define sync_c_win_t      (de_sync->sync_c_win_t)
#define sync_c_win_n      (de_sync->sync_c_win_n)
#define sync_c_pend       (de_sync->sync_c_pend)
#define sync_synth_bpm    (de_sync->sync_synth_bpm)
#define sync_synth_acc    (de_sync->sync_synth_acc)
#define sync_synth_ticks  (de_sync->sync_synth_ticks)

#endif
