export const studioDocs = {
  update:     { sig: 'void update()',                                                  doc: 'Called every frame. Move things, read input. Optional.' },
  draw:       { sig: 'void draw()',                                                    doc: 'Called every frame after update. Draw things.' },
  btn:        { sig: 'bool btn(int player, int button)',                               doc: 'Returns true while the button is held.\nplayer: 0 (WASD+ZX) or 1 (Arrows+,.)' },
  cls:        { sig: 'void cls(int color)',                                            doc: 'Clear the screen to a palette color index (0–31).' },
  spr:        { sig: 'void spr(int index, int x, int y)',                             doc: 'Draw a sprite by its index at position (x, y).' },
  print:      { sig: 'void print(const char *text, int x, int y, int color)',         doc: 'Draw text at (x, y) in the given palette color.' },
  rect:       { sig: 'void rect(int x, int y, int w, int h, int color)',              doc: 'Draw a rectangle border.' },
  rectfill:   { sig: 'void rectfill(int x, int y, int w, int h, int color)',          doc: 'Draw a filled rectangle.' },
  circle:     { sig: 'void circle(int x, int y, int radius, int color)',              doc: 'Draw a circle border.' },
  circlefill: { sig: 'void circlefill(int x, int y, int radius, int color)',          doc: 'Draw a filled circle.' },
  line:       { sig: 'void line(int x1, int y1, int x2, int y2, int color)',          doc: 'Draw a line from (x1, y1) to (x2, y2).' },
  pixel:      { sig: 'void pixel(int x, int y, int color)',                           doc: 'Draw a single pixel at (x, y).' },
  BTN_UP:     { sig: '#define BTN_UP 0',                                              doc: 'Up button.' },
  BTN_DOWN:   { sig: '#define BTN_DOWN 1',                                            doc: 'Down button.' },
  BTN_LEFT:   { sig: '#define BTN_LEFT 2',                                            doc: 'Left button.' },
  BTN_RIGHT:  { sig: '#define BTN_RIGHT 3',                                           doc: 'Right button.' },
  BTN_A:      { sig: '#define BTN_A 4',                                               doc: 'A button. Player 0: Z  Player 1: ,' },
  BTN_B:      { sig: '#define BTN_B 5',                                               doc: 'B button. Player 0: X  Player 1: .' },
  SCREEN_W:   { sig: '#define SCREEN_W 320',                                          doc: 'Width of the screen in pixels. Configurable in settings.' },
  SCREEN_H:   { sig: '#define SCREEN_H 200',                                          doc: 'Height of the screen in pixels. Configurable in settings.' },
  CLR_BLACK:  { sig: '#define CLR_BLACK 0',                                           doc: 'Palette index for black.' },
  CLR_WHITE:  { sig: '#define CLR_WHITE 1',                                           doc: 'Palette index for white.' },
  CLR_RED:    { sig: '#define CLR_RED 2',                                             doc: 'Palette index for red.' },
  CLR_GREEN:  { sig: '#define CLR_GREEN 3',                                           doc: 'Palette index for green.' },
  CLR_BLUE:   { sig: '#define CLR_BLUE 4',                                            doc: 'Palette index for blue.' },
}
