// GENERATED by tools/voxel-bake.js — do not hand-edit.
// Regenerate: node tools/voxel-bake.js <models.js> --tw 4 --zh 2 --emit-c runtime/tenement/atlas.h
// Baked rotation cells for an isometric room. See docs/design/iso-rooms.md.
#pragma once

#define ISO_SIG      "7f388815"   // guard: the .cart.js re-derives this
#define ISO_ATLAS_W  128
#define ISO_ATLAS_H  302
#define ISO_TW       4    // diagonal tile width, px per voxel unit
#define ISO_TH       2
#define ISO_CW       4    // cardinal tile width (== ISO_TW keeps the footprint equal)
#define ISO_ZH       2    // px per voxel of height
#define ISO_ROTS     4

// One baked cell: where it is in the sheet, and where the model's floor origin
// (voxel 0,0,0's projected corner) sits inside it, so placing a cell is a subtraction.
typedef struct { short x, y, w, h, ox, oy; } IsoCell;

typedef enum {
    ISO_SOFA = 0,
    ISO_BED = 1,
    ISO_TOILET = 2,
    ISO_FRIDGE = 3,
    ISO_COUNTER = 4,
    ISO_WALL_LOW_NS = 5,
    ISO_WALL_LOW_EW = 6,
    ISO_WALL_FULL_NS = 7,
    ISO_WALL_FULL_EW = 8,
    ISO_LOOM = 9,
    ISO_WARDROBE = 10,
    ISO_PERSON_LIE = 11,
    ISO_PERSON_WORK = 12,
    ISO_PERSON_SIT = 13,
    ISO_PERSON_HAUL = 14,
    ISO_PERSON = 15,
    ISO_MODEL_COUNT = 16
} IsoModel;

static const char *ISO_NAMES[ISO_MODEL_COUNT] = { "sofa", "bed", "toilet", "fridge", "counter", "wall_low_ns", "wall_low_ew", "wall_full_ns", "wall_full_ew", "loom", "wardrobe", "person_lie", "person_work", "person_sit", "person_haul", "person" };

// [model][rotation]. Rotation is 0..7; EVEN = cardinal, ODD = diagonal.
static const IsoCell ISO_CELLS[ISO_MODEL_COUNT][ISO_ROTS] = {
    /* sofa       */ { {64,70,36,30,12,12}, {0,132,36,29,36,17}, {36,132,36,29,24,29}, {0,102,36,30,0,24} },
    /* bed        */ { {24,189,36,26,24,8}, {72,217,36,24,36,18}, {0,243,36,24,12,24}, {60,189,36,26,0,14} },
    /* toilet     */ { {68,243,16,20,6,11}, {16,267,16,18,18,13}, {32,267,16,18,10,19}, {84,243,16,20,-2,17} },
    /* fridge     */ { {0,0,24,36,12,24}, {24,0,24,36,24,30}, {48,0,24,36,12,36}, {72,0,24,36,0,30} },
    /* counter    */ { {96,189,24,26,12,14}, {0,217,24,26,24,20}, {24,217,24,26,12,26}, {48,217,24,26,0,20} },
    /* wall_low_ns */ { {48,267,16,16,4,8}, {64,267,16,16,16,10}, {80,267,16,16,12,16}, {96,267,16,16,0,14} },
    /* wall_low_ew */ { {112,267,16,16,12,8}, {0,286,16,16,16,14}, {16,286,16,16,4,16}, {32,286,16,16,0,10} },
    /* wall_full_ns */ { {60,36,16,32,4,24}, {76,36,16,32,16,26}, {92,36,16,32,12,32}, {108,36,16,32,0,30} },
    /* wall_full_ew */ { {0,70,16,32,12,24}, {16,70,16,32,16,30}, {32,70,16,32,4,32}, {48,70,16,32,0,26} },
    /* loom       */ { {96,0,20,34,8,24}, {0,36,20,34,20,28}, {20,36,20,34,12,34}, {40,36,20,34,0,30} },
    /* wardrobe   */ { {36,102,20,30,8,20}, {56,102,20,30,20,24}, {76,102,20,30,12,30}, {96,102,20,30,0,26} },
    /* person_lie */ { {48,286,20,14,16,3}, {88,286,20,12,22,10}, {108,286,20,12,4,13}, {68,286,20,14,-2,6} },
    /* person_work */ { {96,132,18,28,8,23}, {0,161,18,28,18,24}, {18,161,18,28,10,29}, {36,161,18,28,0,28} },
    /* person_sit */ { {36,243,16,23,10,13}, {100,243,16,19,20,19}, {0,267,16,19,6,24}, {52,243,16,23,-4,18} },
    /* person_haul */ { {54,161,16,28,6,23}, {70,161,16,28,16,24}, {86,161,16,28,10,29}, {102,161,16,28,0,28} },
    /* person     */ { {0,189,12,28,2,23}, {72,132,12,29,12,25}, {84,132,12,29,10,30}, {12,189,12,28,0,28} },
};

// Voxel footprint per model, in voxel units (8 voxels = one floor tile).
static const short ISO_FOOTPRINT[ISO_MODEL_COUNT][3] = {
    /* sofa       */ {12,6,6},
    /* bed        */ {6,12,4},
    /* toilet     */ {6,6,6},
    /* fridge     */ {6,6,12},
    /* counter    */ {6,6,7},
    /* wall_low_ns */ {6,2,4},
    /* wall_low_ew */ {2,6,4},
    /* wall_full_ns */ {6,2,12},
    /* wall_full_ew */ {2,6,12},
    /* loom       */ {6,4,12},
    /* wardrobe   */ {6,4,10},
    /* person_lie */ {3,8,2},
    /* person_work */ {5,4,12},
    /* person_sit */ {5,6,8},
    /* person_haul */ {5,4,12},
    /* person     */ {5,3,12},
};
