// GENERATED by tools/voxel-bake.js — do not hand-edit.
// Regenerate: node tools/voxel-bake.js <models.js> --tw 4 --zh 2 --emit-c runtime/isoroom/atlas.h
// Baked rotation cells for an isometric room. See docs/design/iso-rooms.md.
#pragma once

#define ISO_SIG      "8fb96d59"   // guard: the .cart.js re-derives this
#define ISO_ATLAS_W  128
#define ISO_ATLAS_H  77
#define ISO_TW       4    // diagonal tile width, px per voxel unit
#define ISO_TH       2
#define ISO_CW       4    // cardinal tile width (== ISO_TW keeps the footprint equal)
#define ISO_ZH       2    // px per voxel of height
#define ISO_ROTS     4

// One baked cell: where it is in the sheet, and where the model's floor origin
// (voxel 0,0,0's projected corner) sits inside it, so placing a cell is a subtraction.
typedef struct { short x, y, w, h, ox, oy; } IsoCell;

typedef enum {
    ISO_SOFA = 0,
    ISO_BED = 1,
    ISO_TOILET = 2,
    ISO_FRIDGE = 3,
    ISO_COUNTER = 4,
    ISO_WALL_LOW = 5,
    ISO_WALL_FULL = 6,
    ISO_PERSON = 7,
    ISO_MODEL_COUNT = 8
} IsoModel;

static const char *ISO_NAMES[ISO_MODEL_COUNT] = { "sofa", "bed", "toilet", "fridge", "counter", "wall_low", "wall_full", "person" };

// [model][rotation]. Rotation is 0..7; EVEN = cardinal, ODD = diagonal.
static const IsoCell ISO_CELLS[ISO_MODEL_COUNT][ISO_ROTS] = {
    /* sofa       */ { {104,0,24,20,8,8}, {104,24,24,17,24,9}, {0,44,24,17,16,17}, {0,24,24,20,0,16} },
    /* bed        */ { {56,24,24,18,16,6}, {24,44,24,16,24,12}, {48,44,24,16,8,16}, {80,24,24,18,0,10} },
    /* toilet     */ { {16,61,8,12,2,7}, {72,61,8,11,10,8}, {80,61,8,11,6,12}, {24,61,8,12,-2,11} },
    /* fridge     */ { {0,0,16,24,8,16}, {16,0,16,24,16,20}, {32,0,16,24,8,24}, {48,0,16,24,0,20} },
    /* counter    */ { {72,44,16,16,8,8}, {88,44,16,16,16,12}, {104,44,16,16,8,16}, {0,61,16,16,0,12} },
    /* wall_low   */ { {32,61,10,11,2,6}, {42,61,10,11,10,7}, {52,61,10,11,8,11}, {62,61,10,11,0,10} },
    /* wall_full  */ { {64,0,10,21,2,16}, {74,0,10,21,10,17}, {84,0,10,21,8,21}, {94,0,10,21,0,20} },
    /* person     */ { {24,24,8,19,2,15}, {32,24,8,19,8,16}, {40,24,8,19,6,19}, {48,24,8,19,0,18} },
};

// Voxel footprint per model, in voxel units (8 voxels = one floor tile).
static const short ISO_FOOTPRINT[ISO_MODEL_COUNT][3] = {
    /* sofa       */ {8,4,4},
    /* bed        */ {4,8,3},
    /* toilet     */ {4,4,4},
    /* fridge     */ {4,4,8},
    /* counter    */ {4,4,4},
    /* wall_low   */ {4,1,3},
    /* wall_full  */ {4,1,8},
    /* person     */ {3,2,8},
};
