// GENERATED by tools/voxel-bake.js — do not hand-edit.
// Regenerate: node tools/voxel-bake.js <models.js> --tw 4 --zh 2 --emit-c runtime/isoroom/atlas.h
// Baked rotation cells for an isometric room. See docs/design/iso-rooms.md.
#pragma once

#define ISO_SIG      "69e7398b"   // guard: the .cart.js re-derives this
#define ISO_ATLAS_W  256
#define ISO_ATLAS_H  294
#define ISO_TW       4    // diagonal tile width, px per voxel unit
#define ISO_TH       2
#define ISO_CW       4    // cardinal tile width (== ISO_TW keeps the footprint equal)
#define ISO_ZH       2    // px per voxel of height
#define ISO_ROTS     8

// One baked cell: where it is in the sheet, and where the model's floor origin
// (voxel 0,0,0's projected corner) sits inside it, so placing a cell is a subtraction.
typedef struct { short x, y, w, h, ox, oy; } IsoCell;

typedef enum {
    ISO_SOFA = 0,
    ISO_BED = 1,
    ISO_TOILET = 2,
    ISO_FRIDGE = 3,
    ISO_COUNTER = 4,
    ISO_WALL_LOW = 5,
    ISO_WALL_FULL = 6,
    ISO_PERSON = 7,
    ISO_MODEL_COUNT = 8
} IsoModel;

static const char *ISO_NAMES[ISO_MODEL_COUNT] = { "sofa", "bed", "toilet", "fridge", "counter", "wall_low", "wall_full", "person" };

// [model][rotation]. Rotation is 0..7; EVEN = cardinal, ODD = diagonal.
static const IsoCell ISO_CELLS[ISO_MODEL_COUNT][ISO_ROTS] = {
    /* sofa       */ { {0,206,64,32,0,16}, {192,48,48,40,16,16}, {0,0,32,48,32,16}, {80,96,48,39,48,23}, {160,206,64,30,64,30}, {128,96,48,39,32,39}, {32,0,32,48,0,48}, {0,96,48,40,0,32} },
    /* bed        */ { {80,48,32,42,0,10}, {100,136,48,34,32,10}, {128,238,64,26,64,10}, {64,206,48,32,48,24}, {48,96,32,40,32,40}, {112,206,48,32,16,32}, {192,238,64,26,0,26}, {148,136,48,34,0,18} },
    /* toilet     */ { {80,238,32,28,0,18}, {24,238,28,29,12,18}, {224,206,24,30,24,18}, {0,268,28,26,28,20}, {56,268,32,22,32,22}, {28,268,28,26,16,28}, {0,238,24,30,0,34}, {52,238,28,29,0,26} },
    /* fridge     */ { {64,0,32,48,0,32}, {96,0,32,48,16,32}, {128,0,32,48,32,32}, {160,0,32,48,32,40}, {192,0,32,48,32,48}, {224,0,32,48,16,48}, {0,48,32,48,0,48}, {32,48,32,48,0,40} },
    /* counter    */ { {196,136,32,34,0,18}, {0,172,32,34,16,18}, {32,172,32,34,32,18}, {64,172,32,34,32,26}, {96,172,32,34,32,34}, {128,172,32,34,16,34}, {160,172,32,34,0,34}, {192,172,32,34,0,26} },
    /* wall_low   */ { {168,268,32,16,0,12}, {88,268,20,22,4,12}, {112,238,8,28,8,12}, {108,268,20,22,20,14}, {200,268,32,16,32,16}, {128,268,20,22,16,22}, {120,238,8,28,0,28}, {148,268,20,22,0,20} },
    /* wall_full  */ { {220,96,32,36,0,32}, {112,48,20,42,4,32}, {64,48,8,48,8,32}, {132,48,20,42,20,34}, {0,136,32,36,32,36}, {152,48,20,42,16,42}, {72,48,8,48,0,48}, {172,48,20,42,0,40} },
    /* person     */ { {32,136,16,36,0,32}, {48,136,14,36,6,31}, {76,136,12,36,12,30}, {192,96,14,37,14,34}, {176,96,16,38,16,38}, {206,96,14,37,8,38}, {88,136,12,36,0,38}, {62,136,14,36,0,35} },
};

// Voxel footprint per model, in voxel units (8 voxels = one floor tile).
static const short ISO_FOOTPRINT[ISO_MODEL_COUNT][3] = {
    /* sofa       */ {16,8,8},
    /* bed        */ {8,16,5},
    /* toilet     */ {8,8,9},
    /* fridge     */ {8,8,16},
    /* counter    */ {8,8,9},
    /* wall_low   */ {8,2,6},
    /* wall_full  */ {8,2,16},
    /* person     */ {4,4,16},
};
