/* de:meta
{
  "slug": "carlos",
  "title": "carlos radio",
  "status": "active",
  "created": "2026-06-09",
  "kind": [
    "toy",
    "instrument"
  ],
  "teaches": [
    "generative-melody",
    "chord-voicing",
    "analog-voice-modeling"
  ],
  "lineage": "Homage to Wendy Carlos's Switched-On Bach; first dreamengine station built on Fux species counterpoint (no chord-progression table) — the contrary-motion rules and canon knob are what's novel over every prior radio station.",
  "homage": "Wendy Carlos / Switched-On Bach (Moog counterpoint)",
  "description": "Switched-On Bach: Wendy Carlos's Moog playing generated two-voice counterpoint - station #18, and the first to prove CHORD BRAIN #7, TWO-VOICE SPECIES COUNTERPOINT. Every other station writes a chord progression first, then drapes melody over it; this inverts it - there is NO progression table. Two independent melodic lines are generated by Fux's species rules (~1725) and the harmony is just whatever the two lines SPELL: consonance required on the strong beats, dissonance only passing on weak beats approached by step, contrary/oblique motion preferred over similar, and NO parallel perfect 5ths or octaves (they fuse two voices into one). The only given harmony is THE GROUND BASS - a seeded chaconne loop (a repeating chord-root cycle, the vamp brain's classical ancestor) the lower voice walks and both voices land on at the cadence. THE FEEL KNOB IS THE TECHNIQUE: LEFT = strict canon (the upper voice is a literal canon of the lower, one bar behind, up an octave - pure imitation), RIGHT = free counterpoint (the upper line generated fresh by the rules), the middle mixing canon bars with free bars - the texture of a real two-part invention. Both voices are the fat Minimoog signal path on loan from moog.c (INSTR_SAW through a resonant lowpass with a per-note filter envelope - the 'wow' - and a little DRIVE), with a quiet sustained tonic pedal behind them. One seeded key lift mid-piece (Bach's tonal journey), and the piece ENDS on a real V-i cadence with the voices converging to the tonic. The window is the contrary-motion LATTICE - the two lines on a pitch grid scrolling left, so you watch one rise as the other falls and see the canon's upper line trace the lower's shape a bar later. SPACE next piece, R same piece, [ ] history, LEFT/RIGHT feel (canon/invent/loose/free), UP/DOWN tempo, T tone, M power, H help."
}
de:meta */
#include "studio.h"
#include "radio.h"   // the shared station chassis (PRNG, clock, history, chrome)
#include <stdio.h>
#include <math.h>

// ── CARLOS RADIO ──────────────────────────────────────────────────────────────
// Switched-On Bach: Wendy Carlos's Moog playing generated two-voice counterpoint.
// Station #18, and the first to prove a new HARMONY brain that isn't a chord
// progression at all:
//
//   • CHORD BRAIN #7 — TWO-VOICE SPECIES COUNTERPOINT. Every station so far
//     generates a chord progression first, then drapes melody/bass over it.
//     This inverts it: there is NO progression table. Two independent melodic
//     lines are generated by Fux's species rules (~1725), and the harmony is
//     just whatever the two lines SPELL at each instant:
//       - consonance required on strong beats (unison/3rd/5th/6th/octave);
//         dissonance only passing, on weak beats, approached by step;
//       - contrary/oblique motion preferred over similar (keeps the lines
//         sounding independent);
//       - NO parallel perfect 5ths or octaves (they fuse two voices into one).
//     The only "given" harmony is THE GROUND BASS — a seeded chaconne loop
//     (a repeating chord-root cycle, the vamp brain's classical ancestor) that
//     the lower voice walks and both voices land on at the cadence.
//
//   • THE FEEL KNOB IS THE TECHNIQUE — strict canon ↔ free counterpoint.
//     LEFT (canon): the upper voice is a literal CANON of the lower, one bar
//     behind, up an octave — maximally imitative, pure Bach. RIGHT (free): the
//     upper voice is generated fresh by the species rules, a fully independent
//     line. The middle settings mix canon bars with free bars — the texture of
//     a real two-part invention (state the subject, then loosen). The knob
//     literally loosens the imitation as you turn it right.
//
//   • THE FAT MOOG — both voices are INSTR_SAW through a resonant lowpass with
//     a per-note filter envelope (the Minimoog "wow") and a little DRIVE: the
//     exact moog.c signal path, driven by the counterpoint generator instead of
//     a keyboard. A quiet sustained tonic PEDAL fills the wall behind them.
//
//   • THE MODULATION EVENT — one seeded key lift mid-piece (to the dominant or
//     relative), Bach's tonal journey; the lattice horizon flares when it lands.
//     The piece ENDS on a real V–i cadence (the voices converge to the tonic).
//
// The contrary-motion LATTICE in the window is the brain made visible: two lines
// on a pitch grid scrolling left — you watch one rise as the other falls, and
// see the canon's upper line trace the lower line's shape a bar later.
//
//   SPACE next piece   R play it again   [ ] history   M radio on/off
//   LEFT/RIGHT feel (canon → free)   UP/DOWN tempo   T tone   H or ? help
//
// Seed pins the COMPOSITION (key, mode, chaconne, subject, the modulation, the
// title). The counterpoint is regenerated from the seed too, so R replays the
// exact piece — turning the feel knob is the only thing that rewrites it live.

#define CARLOS_SEED 0   // pin a favourite piece here (0 = free-roaming radio)

// ── instrument slots ──────────────────────────────────────────────────────
#define I_UP    5   // upper Moog voice — brighter saw
#define I_LO    6   // lower Moog voice — rounder, fatter saw
#define I_PED   7   // sustained tonic pedal — the Switched-On wall

// ── the two scales (minor = harmonic, for the leading-tone cadence) ─────────
static const int MODE[2][7] = {
    { 0, 2, 4, 5, 7, 9, 11 },   // major   (Ionian)
    { 0, 2, 3, 5, 7, 8, 11 },   // minor   (harmonic — raised 7th = leading tone)
};
static const char *MODENAME[2] = { "major", "minor" };
static const char *PCNAME[12]  = { "C","Db","D","Eb","E","F","Gb","G","Ab","A","Bb","B" };

// ── the chaconne / ground-bass templates (scale-degree roots, 4-bar loops) ──
#define CHLEN 4
static const int CHACONNE[4][CHLEN] = {
    { 0, 5, 3, 4 },   // i – VI – iv – V   (the andalusian-ish ground)
    { 0, 6, 5, 4 },   // i – VII – VI – V  (the lament bass)
    { 0, 3, 4, 0 },   // i – iv – V – i    (plain functional)
    { 0, 4, 5, 4 },   // i – V – VI – V    (the deceptive turn)
};

#define ANCHOR 36     // the scale ladder's low C (C2); degree 0 of curKey sits at +curKey

// ── the generated piece ───────────────────────────────────────────────────
typedef struct {
    int   keyPc, mode;
    int   chac;                   // which chaconne template
    int   pieceLenBars;           // 24..40 bars
    double modAt;                 // 0.45..0.66 — where the key lifts
    int   modIv;                  // +3/+4/+5/+7 semitones
    int   resU, resL;             // rolled filter resonance per voice (mellow vs zappy)
    float drvU, drvL;             // rolled overdrive per voice
    int   catNo;                  // a fake BWV-style catalogue number for the display
    char  title[28];
    float freq;
    unsigned seed;
} Piece;

static Piece      pc;
static RadioSeed  rs;                       // composition PRNG + history (radio.h)
static RadioClock clk = { -1, 0, 96.0 };    // schedule-ahead step clock (radio.h)
#define stepMs    (clk.stepMs)
#define songBase  (clk.songBase)
#define scheduled (clk.scheduled)
#define srnd(n)    rad_srnd(&rs, (n))

static int    tempo     = 96;
static int    intensity = 1;     // THE FEEL KNOB: 0 canon … 3 free
static bool   radioOn   = true;
static bool   showHelp  = false;
static int    toneSel   = 2;
static int    pieceCount = 0;
static float  vu        = 0;

// ── runtime form state ──────────────────────────────────────────────────────
static double prog    = 0;       // 0..1 over the whole piece
static bool   modDone = false;
static int    curKey  = 0;       // keyPc + the modulation, once it lands

// ── the generator's per-bar output + carry-over state ───────────────────────
static int  loDeg[16], upDeg[16];   // sounding scale-DEGREE per 16th step (absDeg), -1 = silent
static bool loHit[16], upHit[16];   // a note STARTS at this step
static long genBar = -1;            // which bar loDeg/upDeg currently hold
static bool curCanon = false;       // is the current bar a canon bar (display)
static int  prevLoAd = 8, prevUpAd = 16;   // last absDeg each voice committed to
static int  prevIv   = 7;           // last vertical interval (for the parallel-perfect rule)

// the lower voice's onset history, indexed by absolute 16th-step, for the canon
#define HIST 256
static int  histAd[HIST];           // absDeg of a lower onset at this abs step, -1 = none

// the pedal (held)
static int  pedH = -1; static bool pedLive = false;

// the lattice trail (one sample per played step)
#define TRAIL 104
static int  trLo[TRAIL], trUp[TRAIL]; static int trHead = 0;

static int iabs(int v) { return v < 0 ? -v : v; }
static int fdiv(int a, int b) { int q = a / b; if ((a % b) && ((a < 0) != (b < 0))) q--; return q; }

// ── scale-ladder helpers — everything lives in absolute scale-DEGREE space ──
// midi of absDeg ad: octave = floor(ad/7), degree = ad mod 7
static int midiOfDeg(int ad) {
    int o = fdiv(ad, 7), d = ad - 7 * o;
    return ANCHOR + curKey + 12 * o + MODE[pc.mode][d];
}
static int degClass(int ad) { int d = ad % 7; return d < 0 ? d + 7 : d; }
static int nearestDeg(int midi) {              // absDeg whose midi is closest
    int best = 0, bd = 9999;
    for (int ad = 0; ad < 36; ad++) { int dm = iabs(midiOfDeg(ad) - midi); if (dm < bd) { bd = dm; best = ad; } }
    return best;
}
// chord = diatonic triad on the bar's chaconne root: degree-classes {r, r+2, r+4}
static int chordRoot = 0;   // scale-degree class of the current bar's chord root
static bool isChordTone(int ad) {
    int d = degClass(ad);
    return d == chordRoot || d == (chordRoot + 2) % 7 || d == (chordRoot + 4) % 7;
}
// nearest absDeg of a given degree-class to a center
static int nearestClass(int cls, int center) {
    cls = ((cls % 7) + 7) % 7;
    for (int r = 0; r < 8; r++) {
        if (degClass(center - r) == cls) return center - r;
        if (degClass(center + r) == cls) return center + r;
    }
    return center;
}
static int clampAd(int ad, int lo, int hi) { return ad < lo ? lo : ad > hi ? hi : ad; }

// consonant vertical interval? (unison/m3/M3/P5/m6/M6/oct — P4 counts as dissonant)
static bool consonant(int mu, int ml) {
    int iv = iabs(mu - ml) % 12;
    return iv == 0 || iv == 3 || iv == 4 || iv == 7 || iv == 8 || iv == 9;
}
static bool perfect(int mu, int ml) { int iv = iabs(mu - ml) % 12; return iv == 0 || iv == 7; }

// the lower-voice register (absDeg) and the upper-voice register
#define LO_LO 6
#define LO_HI 14
#define UP_LO 13
#define UP_HI 23

// ── THE COUNTERPOINT GENERATOR — one bar at a time ──────────────────────────
static void generate_bar(long bar, long base) {
    int len = pc.pieceLenBars;
    // a forced V–i cadence closes the piece
    int croot = (bar == len - 1) ? 0 : (bar == len - 2) ? 4 : CHACONNE[pc.chac][bar % CHLEN];
    chordRoot = croot;
    bool finalBar = (bar >= len - 1);

    for (int s = 0; s < 16; s++) { loHit[s] = upHit[s] = false; loDeg[s] = upDeg[s] = -1; }

    // ── LOWER VOICE — the chaconne walked: chord tones on the beats, passing 8ths ──
    int strongAd[4];   // pitches landed at steps 0,4,8,12
    // beat 1: the chord ROOT, nearest to where we left off
    strongAd[0] = clampAd(nearestClass(croot, prevLoAd), LO_LO, LO_HI);
    // beat 2: any chord tone near beat 1
    strongAd[1] = clampAd(isChordTone(strongAd[0] + 2) ? strongAd[0] + 2
                          : nearestClass(croot + 2, strongAd[0]), LO_LO, LO_HI);
    // beat 3: the FIFTH (croot+4), the chaconne's other pillar
    strongAd[2] = clampAd(nearestClass(croot + 4, strongAd[1]), LO_LO, LO_HI);
    // beat 4: a chord tone leaning toward the next bar's root
    strongAd[3] = clampAd(nearestClass(croot, strongAd[2] - 1), LO_LO, LO_HI);
    if (finalBar) { strongAd[2] = strongAd[3] = clampAd(nearestClass(0, prevLoAd), LO_LO, LO_HI); }

    int beatStep[4] = { 0, 4, 8, 12 };
    for (int b = 0; b < 4; b++) { loHit[beatStep[b]] = true; loDeg[beatStep[b]] = strongAd[b]; }
    // passing 8ths between the beats — a single scale step toward the next pillar
    int pass[4] = { 2, 6, 10, 14 };
    for (int b = 0; b < 4; b++) {
        if (finalBar) break;                       // the cadence bar walks in quarters only
        if (srnd(100) < 42) {                      // seeded: some bars walk, some hold
            int from = strongAd[b], to = (b < 3) ? strongAd[b + 1] : strongAd[3] + 1;
            int p = clampAd(from + sgn(to - from), LO_LO, LO_HI);
            loHit[pass[b]] = true; loDeg[pass[b]] = p;
        }
    }
    // fill the sounding ladder forward + log the onset history for the canon
    int held = strongAd[0];
    for (int s = 0; s < 16; s++) {
        if (loHit[s]) held = loDeg[s];
        loDeg[s] = held;
        histAd[(base + s) % HIST] = loHit[s] ? loDeg[s] : -1;
    }
    prevLoAd = held;

    // ── UPPER VOICE — canon or free, per the feel knob ──────────────────────
    if (bar == 0) { for (int s = 0; s < 16; s++) upDeg[s] = -1; curCanon = false; return; }

    float canonStrength = (3 - intensity) / 3.0f;       // 1.0 strict … 0.0 free
    bool canonBar = (bar == 1) || (srnd(100) < (int)(canonStrength * 100));
    curCanon = canonBar;

    if (canonBar) {
        // the upper voice = the lower voice from ONE BAR AGO, up an octave (+7 degrees)
        int held2 = -1;
        for (int s = 0; s < 16; s++) {
            int h = histAd[(base + s - 16 + HIST) % HIST];
            if (h >= 0) {                                // an onset a bar ago → an onset now
                int u = clampAd(h + 7, UP_LO, UP_HI);
                upHit[s] = true; upDeg[s] = u; held2 = u; prevUpAd = u;
            } else upDeg[s] = held2;
        }
        if (held2 < 0) canonBar = false;                 // nothing to imitate yet → fall through
        else { int e = held2; for (int s = 15; s >= 0 && upDeg[s] < 0; s--) upDeg[s] = e; }
    }
    if (!canonBar) {
        // FREE: an 8th-note line scored by the species rules against the lower voice
        int held2 = prevUpAd;
        for (int s = 0; s < 16; s += 2) {
            int l = loDeg[s], ml = midiOfDeg(l);
            bool strong = (s == 0 || s == 8);
            int bestAd = prevUpAd, bestScore = -9999;
            for (int off = -3; off <= 3; off++) {
                int cand = clampAd(prevUpAd + off, UP_LO, UP_HI);
                int mu = midiOfDeg(cand);
                bool cons = consonant(mu, ml);
                if (strong && !cons) continue;                       // strong beats must be consonant
                if (!strong && !cons && iabs(cand - prevUpAd) > 1) continue;  // dissonance only as a step (passing)
                int upMove = mu - midiOfDeg(prevUpAd);
                int loMove = ml - midiOfDeg(held2 == prevUpAd ? prevUpAd : prevUpAd); // (lower's move read below)
                (void)loMove;
                int loStepMove = ml - midiOfDeg(s >= 2 ? loDeg[s - 2] : l);
                // forbid parallel perfect 5ths/octaves (perfect → similar motion → perfect)
                if (perfect(midiOfDeg(prevUpAd), midiOfDeg(s >= 2 ? loDeg[s - 2] : l))
                    && perfect(mu, ml) && sgn(upMove) == sgn(loStepMove) && sgn(upMove) != 0) continue;
                int score = 0;
                int dir = sgn(upMove), ld = sgn(loStepMove);
                if (dir != 0 && ld != 0 && dir != ld) score += 4;    // contrary motion — best
                else if (dir == 0 || ld == 0)         score += 2;    // oblique
                score += 3 - (iabs(off) > 3 ? 3 : iabs(off));        // prefer small steps
                if (strong && isChordTone(cand)) score += 3;         // land on the chord on the beat
                if (!strong && cand == prevUpAd)  score -= 2;        // keep it moving on weak beats
                score += srnd(2);                                    // a little seeded variety
                if (score > bestScore) { bestScore = score; bestAd = cand; }
            }
            if (finalBar && s >= 8) bestAd = clampAd(nearestClass(0, prevUpAd), UP_LO, UP_HI); // resolve to tonic
            upHit[s] = true; upDeg[s] = bestAd;
            prevUpAd = bestAd; prevIv = iabs(midiOfDeg(bestAd) - ml) % 12; held2 = bestAd;
        }
        int e = prevUpAd; for (int s = 0; s < 16; s++) if (upDeg[s] < 0) upDeg[s] = (s ? upDeg[s - 1] : e);
    }
}

// ── instruments — the fat Moog (moog.c's signal path), rolled per piece ─────
static void apply_voicing(void) {                 // T cycles tone → re-aim the filters
    float m = RAD_TONEMUL[toneSel];
    instrument_filter(I_UP,  FILTER_LOW, (int)(2200 * m), pc.resU);
    instrument_filter(I_LO,  FILTER_LOW, (int)(1450 * m), pc.resL);
    instrument_filter(I_PED, FILTER_LOW, (int)(820  * m), 1);
}
static void apply_band(void) {                    // the per-piece timbre roll
    instrument(I_UP, INSTR_SAW, 5, 220, 3, 170);
    instrument_drive(I_UP, pc.drvU);
    instrument_env(I_UP, 0, ENV_CUTOFF, 0, 110, 1300);     // the Minimoog filter "wow" per note

    instrument(I_LO, INSTR_SAW, 6, 300, 3, 220);
    instrument_drive(I_LO, pc.drvL);
    instrument_env(I_LO, 0, ENV_CUTOFF, 0, 150, 1000);

    instrument(I_PED, INSTR_SAW, 400, 600, 5, 1200);       // slow sustained pedal — the wall
    instrument_lfo(I_PED, 0, LFO_PITCH, 0.16f, 0.04f);     // a hair of analog drift
}

static void start_pedal(void) {
    pedH = note_on(midiOfDeg(0), I_PED, 2);                // tonic, low octave
    note_glide(pedH, 300);
    pedLive = true;
}
static void stop_pedal(void) { if (pedH >= 0) note_off(pedH); pedH = -1; pedLive = false; }

// ── piece generation ───────────────────────────────────────────────────────
static const char *TW[] = { "Invention", "Sinfonia", "Prelude", "Fugue", "Chaconne",
    "Ground", "Ricercar", "Canon", "Toccata", "Passacaglia", "Aria", "Contrapunctus" };

static void new_piece(double pos, unsigned seed) {
    pc.seed = rad_seed_begin(&rs, seed);

    pc.keyPc        = srnd(12);
    pc.mode         = srnd(2);
    pc.chac         = srnd(4);
    pc.pieceLenBars = 24 + srnd(17);          // 24..40 bars

    pc.modAt = 0.45 + srnd(22) * 0.01;        // 0.45..0.66
    static const int IV[4] = { 3, 4, 5, 7 };
    pc.modIv = IV[srnd(4)];

    pc.resU = 3 + srnd(5);                    // 3..7
    pc.resL = 2 + srnd(4);                    // 2..5
    pc.drvU = 0.18f + srnd(16) * 0.01f;       // 0.18..0.33
    pc.drvL = 0.24f + srnd(14) * 0.01f;       // 0.24..0.37

    pc.catNo = 772 + srnd(30);                // a BWV-ish catalogue number
    if (srnd(100) < 50) snprintf(pc.title, sizeof pc.title, "%s No.%d", TW[srnd(12)], 1 + srnd(15));
    else                snprintf(pc.title, sizeof pc.title, "%s", TW[srnd(12)]);
    pc.freq = 88.0f + srnd(200) * 0.1f;

    tempo = 78 + srnd(35);                     // 78..112
    bpm(tempo);

    songBase = (long)pos + 8;
    modDone  = false;
    curKey   = pc.keyPc;
    genBar   = -1;
    prevLoAd = nearestClass(0, 10);
    prevUpAd = nearestClass(0, 18);
    prevIv   = 7;
    for (int i = 0; i < HIST; i++) histAd[i] = -1;
    for (int i = 0; i < TRAIL; i++) trLo[i] = trUp[i] = -1;
    trHead = 0;
    stop_pedal();
    apply_band();
    apply_voicing();
    pieceCount++;
}
static void fresh_piece(double pos) { new_piece(pos, 0); rad_hist_log(&rs); }

// ── the step player ─────────────────────────────────────────────────────────
static void play_step(long abs, double pos) {
    long s = abs - songBase;
    if (s < 0) return;
    int  dly  = rad_step_dly(&clk, abs, pos);
    int  step = (int)(s % 16);
    long bar  = s / 16;
    if (bar >= pc.pieceLenBars) return;

    if (step == 0 && bar != genBar) { generate_bar(bar, songBase + bar * 16); genBar = bar; }

    // LOWER voice
    if (loHit[step]) {
        int dur = step % 4 == 0 ? (int)(stepMs * 3.6) : (int)(stepMs * 1.8);
        schedule_hit(dly, midiOfDeg(loDeg[step]), I_LO, 5, dur);
        vu += 1.4f;
    }
    // UPPER voice
    if (upHit[step]) {
        schedule_hit(dly, midiOfDeg(upDeg[step]), I_UP, 4, (int)(stepMs * 1.8));
        vu += 1.2f;
    }

    // the lattice trail — one sample per 16th
    trLo[trHead % TRAIL] = loDeg[step] >= 0 ? midiOfDeg(loDeg[step]) : -1;
    trUp[trHead % TRAIL] = upDeg[step] >= 0 ? midiOfDeg(upDeg[step]) : -1;
    trHead++;
}

// ── update ────────────────────────────────────────────────────────────────
void update(void) {
    static bool booted = false;
    double pos = (double)beat() * 4.0 + beat_pos() * 4.0;
    stepMs = 60000.0 / (tempo * 4);

    if (!booted) {
        if (CARLOS_SEED) { new_piece(pos, CARLOS_SEED); rad_hist_log(&rs); }
        else fresh_piece(pos);
        scheduled = (long)pos;
        booted = true;
    }

    int ev = rad_input(&tempo, 60, 132, 3, &intensity, &toneSel, 4, &radioOn, &showHelp);
    if (ev & RAD_EV_NEW)    fresh_piece(pos);
    if (ev & RAD_EV_REPLAY) new_piece(pos, pc.seed);
    if (ev & RAD_EV_BACK)   { unsigned x = rad_hist_back(&rs); if (x) new_piece(pos, x); }
    if (ev & RAD_EV_FWD)    { unsigned x = rad_hist_fwd(&rs);  if (x) new_piece(pos, x); }
    if (ev & RAD_EV_TONE)   apply_voicing();
    if (ev & RAD_EV_POWER)  { if (!radioOn) { note_off_all(); stop_pedal(); } else scheduled = (long)pos; }

    if (radioOn) {
        long songStep = scheduled - songBase;
        prog = songStep > 0 ? (double)songStep / (pc.pieceLenBars * 16) : 0;
        if (prog > 1) prog = 1;

        // THE MODULATION EVENT — the key lifts once, mid-piece
        if (!modDone && prog >= pc.modAt) {
            modDone = true;
            curKey  = (curKey + pc.modIv) % 12;
            if (pedLive) note_pitch(pedH, midiOfDeg(0));
        }

        // the pedal fills the wall once the piece is underway
        bool pW = prog > 0.18 && prog < 0.97;
        if (pW && !pedLive) start_pedal(); else if (!pW && pedLive) stop_pedal();

        long st;
        while (rad_clock_step(&clk, pos, &st)) play_step(st, pos);

        if (songStep >= (long)pc.pieceLenBars * 16) fresh_piece(pos);
    }

    vu *= 0.88f; if (vu > 12) vu = 12;

#ifdef DE_TRACE
    watch("piece", "%d", pieceCount);
    watch("prog", "%.3f", prog);
    watch("bar", "%ld", genBar);
    watch("canon", "%d", curCanon);
    watch("key", "%d", curKey);
    watch("modDone", "%d", modDone);
    // the live vertical interval between the voices (the harmony being spelled)
    { int i = (trHead - 1 + TRAIL) % TRAIL;
      int iv = (trLo[i] >= 0 && trUp[i] >= 0) ? iabs(trUp[i] - trLo[i]) % 12 : -1;
      watch("ivl", "%d", iv); }
    watch("tempo", "%d", tempo);
#endif
}

// ── draw — the Moog panel + the contrary-motion lattice ─────────────────────
static int latY(int midi, int wy, int wh) {       // map midi → window y (high pitch = top)
    int lo = 40, hi = 84;
    if (midi < lo) midi = lo; if (midi > hi) midi = hi;
    return wy + wh - 2 - (midi - lo) * (wh - 4) / (hi - lo);
}

void draw(void) {
    cls(CLR_BROWNISH_BLACK);
    ui_begin();

    rad_body(CLR_DARK_BROWN, CLR_PEACH);           // walnut Moog cabinet, cream accent
    rad_dial(pc.freq, CLR_PEACH);

    // ── the window: the contrary-motion lattice ───────────────────────────
    int wx = 34, wy = 52, ww = 102, wh = 116;
    rectfill(wx, wy, ww, wh, CLR_BLACK);
    // octave gridlines (faint) — a reference grid behind the lines
    for (int m = 48; m <= 84; m += 12) {
        int gy = latY(m, wy, wh);
        for (int x = wx + 1; x < wx + ww - 1; x += 3) pset(x, gy, CLR_DARKER_GREY);
    }
    if (modDone) rectfill(wx, wy, ww, 3, CLR_DARK_ORANGE);   // the horizon flares at the key lift

    if (radioOn) {
        int vis = TRAIL < ww ? TRAIL : ww;
        int px_lo = -1, py_lo = 0, px_up = -1, py_up = 0;
        for (int i = 0; i < vis; i++) {
            int idx = (trHead - vis + i + TRAIL * 2) % TRAIL;
            int x   = wx + 1 + i * (ww - 2) / vis;
            int ml = trLo[idx], mu = trUp[idx];
            if (ml >= 0) {
                int y = latY(ml, wy, wh);
                if (px_lo >= 0) line(px_lo, py_lo, x, y, CLR_DARK_ORANGE);
                px_lo = x; py_lo = y;
            } else px_lo = -1;
            if (mu >= 0) {
                int y = latY(mu, wy, wh);
                if (px_up >= 0) line(px_up, py_up, x, y, CLR_LIGHT_PEACH);
                px_up = x; py_up = y;
            } else px_up = -1;
        }
        // the "now" head — a bright pip on each voice's latest pitch
        int last = (trHead - 1 + TRAIL) % TRAIL;
        if (trLo[last] >= 0) { int y = latY(trLo[last], wy, wh); rectfill(wx + ww - 4, y - 1, 3, 3, CLR_ORANGE); }
        if (trUp[last] >= 0) { int y = latY(trUp[last], wy, wh); rectfill(wx + ww - 4, y - 1, 3, 3, CLR_WHITE); }
    }
    rect(wx, wy, ww, wh, CLR_DARK_GREY);

    // ── the display ────────────────────────────────────────────────────────
    rectfill(148, 52, 142, 44, CLR_BLACK);
    rect(148, 52, 142, 44, CLR_PEACH);
    if (radioOn) {
        print(pc.title, 154, 58, CLR_PEACH);
        char l2[36];
        snprintf(l2, 36, "%.1f FM  BWV-%d", pc.freq, pc.catNo);
        print(l2, 154, 70, CLR_LIGHT_YELLOW);
        snprintf(l2, 36, "%d bpm #%08X", tempo, pc.seed);
        print(l2, 154, 82, CLR_LIGHT_YELLOW);
        rectfill(154, 91, 130, 2, CLR_DARKER_GREY);
        rectfill(154, 91, (int)(prog * 130), 2, CLR_PEACH);
    } else print("- radio off -", 170, 70, CLR_DARK_GREY);

    // texture readout: which voices, canon vs free, the live interval, the key
    if (radioOn) {
        print("LO", 152, 104, CLR_ORANGE);
        print("UP", 176, 104, genBar >= 1 ? CLR_LIGHT_PEACH : CLR_DARKER_GREY);
        print(curCanon ? "canon" : "free", 204, 104, curCanon ? CLR_WHITE : CLR_PEACH);
        char kl[24];
        const char *mm = pc.mode ? "min" : "maj";
        if (modDone) snprintf(kl, 24, "key %s %s +%d", PCNAME[curKey % 12], mm, pc.modIv);
        else         snprintf(kl, 24, "key %s %s", PCNAME[curKey % 12], mm);
        print(kl, 152, 116, modDone ? CLR_DARK_ORANGE : CLR_DARK_GREY);
    }

    // ── knobs + power LED ───────────────────────────────────────────────────
    static const char *FEEL[4] = { "canon", "invent", "loose", "free" };
    rad_knob_sel(&intensity, 4, 168, 148, 9, FEEL[intensity], CLR_PEACH);
    if (rad_knob_int(&tempo, 60, 132, 3, 218, 148, 9, "tempo", CLR_PEACH)) bpm(tempo);
    if (rad_knob_sel(&toneSel, 4, 262, 148, 11, RAD_TONENAME[toneSel], CLR_PEACH)) apply_voicing();
    rad_power_led(radioOn, CLR_PEACH, CLR_DARK_RED);

    rad_help_button(CLR_PEACH);
    if (showHelp) {
        static const char *HELP[8][2] = {
            { "SPACE",      "next piece (rolls a new seed)" },
            { "R",          "same piece again" },
            { "[ / ]",      "back / forward through history" },
            { "LEFT/RIGHT", "feel - canon to free counterpoint" },
            { "UP/DOWN",    "tempo" },
            { "T",          "tone - mellow/warm/clear/bright" },
            { "M",          "radio power on / off" },
            { "H or ?",     "show / hide this help" },
        };
        static const char *NOTES[3] = {
            "no chord chart - two voices spell the harmony",
            "left = strict canon, right = free counterpoint",
            "pin it: #define CARLOS_SEED 0x...",
        };
        rad_help_panel("CARLOS RADIO", HELP, 8, NOTES, 3, CLR_PEACH);
    }

    ui_end();
}
