/* de:meta
{
  "title": "sprite foundry",
  "status": "active",
  "kind": [
    "tutorial",
    "tech-demo"
  ],
  "teaches": [
    "algorithm-visualization"
  ],
  "lineage": "Self-documents the sprite-draw.js toolkit by replaying each drawing op as a time-lapse; the cart IS the test-suite and the tutorial for the JS sprite-drawing library.",
  "description": "Watch the code draw. Every sprite in this cart was generated by tools/sprite-draw.js, and the sheet holds each subject's time-lapse: foundry.cart.js snapshots the canvas into the next slot after every drawing step, and the cart plays the construction back with the line of code that produced each frame. Three subjects, three money shots: a dragon lit by the new shade() ramps, a mirror()ed ship spun through 8 rotations() headings, and a boss that gets noise() warts, a replace() recolor and a scale2x() upscale into a 2x2 slot block. LEFT/RIGHT step, Z autoplay, UP/DOWN switch subject."
}
de:meta */
// SPRITE FOUNDRY - watch the code draw.
//
// Every sprite in this cart was generated by tools/sprite-draw.js, and the
// sheet holds each subject's own time-lapse: foundry.cart.js snapshots the
// canvas into the next slot after every drawing step. This cart is just the
// player - it flips through the slots and shows the line of code that
// produced each step.
//
// Three subjects, three toolkit money shots:
//   DRAGON  shade() rolls light over flat fills, then outlined()
//   SHIP    mirror() symmetry, then rotations(g,8) - 8 baked headings
//   BOSS    noise() warts + replace() recolor, then scale2x() to 32x32
//
// LEFT/RIGHT step through, Z toggles autoplay, UP/DOWN switch subject.
//
// KEEP IN SYNC with foundry.cart.js: slot layout + one label per snapshot.

#include "studio.h"

#define FIN_NONE 0
#define FIN_SPIN 1   // last step animates 8 heading slots
#define FIN_BIG  2   // last step is a 32x32 spread over a 2x2 slot block

typedef struct { const char *code; const char *note; } Step;

typedef struct {
    const char *name;
    int base;            // first snapshot slot
    int fin, fslot;      // final-step kind + its slot (spin: first heading; big: TL)
    int nsteps;          // total steps shown (incl. the final one)
    const Step *steps;
} Subject;

static const Step DRAGON_STEPS[] = {
    { "ovalfill(g, 8,10, 5,3.2, GRN)",  "the body - a flat green oval" },
    { "trifill(g, 0,6, 3,12, 7,12)",    "tail" },
    { "circlefill(g, 12,5, 2.6)",       "head" },
    { "rectfill(g, 14,4, 15,6)",        "snout" },
    { "rectfill(g, ...) x2",            "legs" },
    { "ovalfill(g, 8,11.5, 3,1.6, LIME)", "belly patch" },
    { "trifill(g, ...) x2",             "back spikes" },
    { "pixel(g, ...) x3",               "eye + nostril" },
    { "g = shade(g)",                   "auto light from the top-left" },
    { "g = outlined(g)",                "1px border traced around it" },
};

static const Step SHIP_STEPS[] = {
    { "polyfill(g, [...], GREY)",       "hull - the LEFT half only" },
    { "trifill(g, 6,7, 1,13, 6,12)",    "wing - left only" },
    { "mirror(g)",                      "left half copied to the right" },
    { "ovalfill + pixel x2",            "canopy + engine flame" },
    { "rotations(g, 8) -> outlined()",  "8 baked headings, one drawing" },
};

static const Step BOSS_STEPS[] = {
    { "rrectfill(g, 2,2, 12,10, 3)",    "skull" },
    { "rrectfill(g, 1,9, 14,6, 2)",     "jaw" },
    { "trifill(g, ...) x2",             "horns" },
    { "rectfill + pixel - eyes",        "angry eyes" },
    { "rectfill + pixel - teeth",       "mouth" },
    { "noise(x,y,7)==0 -> dark",        "warts - stable speckle, no RNG" },
    { "replace(g, GRN, MAUVE)",         "bake-time recolor" },
    { "g = outlined(g)",                "border" },
    { "scale2x(g) -> split()",          "16x16 sketch -> 32x32 boss" },
};

static const Subject SUBJECTS[] = {
    { "DRAGON", 0,  FIN_NONE, 0,  10, DRAGON_STEPS },
    { "SHIP",   10, FIN_SPIN, 14, 5,  SHIP_STEPS },
    { "BOSS",   22, FIN_BIG,  40, 9,  BOSS_STEPS },
};
#define NSUBJ 3

static int   subj, step;
static int   autoplay = 1;
static int   t;            // autoplay clock

// canvas placement (16x16 shown at 8x)
#define CX 16
#define CY 38
#define CS 128

static int is_final(void) {
    const Subject *S = &SUBJECTS[subj];
    return S->fin != FIN_NONE && step == S->nsteps - 1;
}

static void goto_step(int s) {
    step = s;
    t = 0;
    if (is_final()) strum(57, CHORD_MAJ, 6, 5, 30);
    else            hit(62 + step * 2, 5, 3, 35);
}

static void next_subject(int dir) {
    subj = (subj + NSUBJ + dir) % NSUBJ;
    step = 0;
    t = 0;
    hit(70, 5, 4, 45);
}

void init(void) {
    colorkey(CLR_BLACK);
    instrument(5, INSTR_SQUARE, 2, 60, 3, 80);
    instrument_duty(5, 0.25f);
}

void update(void) {
    const Subject *S = &SUBJECTS[subj];

    if (btnp(0, BTN_RIGHT)) { autoplay = 0; goto_step((step + 1) % S->nsteps); }
    if (btnp(0, BTN_LEFT))  { autoplay = 0; goto_step((step + S->nsteps - 1) % S->nsteps); }
    if (btnp(0, BTN_DOWN))  next_subject(+1);
    if (btnp(0, BTN_UP))    next_subject(-1);
    if (btnp(0, BTN_A))     autoplay = !autoplay;

    if (autoplay) {
        t++;
        int hold = is_final() ? 150 : 45;      // linger on the money shot
        if (t >= hold) {
            if (step == S->nsteps - 1) { next_subject(+1); }
            else                       goto_step(step + 1);
        }
    }
}

// draw one slot's 16x16 stretched into a square
static void slot16(int s, int dx, int dy, int size) {
    sspr((s % 8) * 16, (s / 8) * 16, 16, 16, dx, dy, size, size);
}

static void draw_canvas(void) {
    const Subject *S = &SUBJECTS[subj];

    // transparency checkerboard behind the canvas
    for (int cy = 0; cy < 8; cy++)
        for (int cx = 0; cx < 8; cx++)
            rectfill(CX + cx * 16, CY + cy * 16, 16, 16,
                     ((cx + cy) & 1) ? CLR_DARKER_GREY : CLR_BROWNISH_BLACK);
    rect(CX - 2, CY - 2, CS + 4, CS + 4, CLR_MEDIUM_GREY);

    if (!is_final()) {
        slot16(S->base + step, CX, CY, CS);
    } else if (S->fin == FIN_SPIN) {
        slot16(S->fslot + anim(8, 6, 0.0f), CX, CY, CS);
    } else {  // FIN_BIG: 32x32 living in a 2x2 slot block
        sspr((S->fslot % 8) * 16, (S->fslot / 8) * 16, 32, 32, CX, CY, CS, CS);
    }
}

static void draw_panel(void) {
    const Subject *S = &SUBJECTS[subj];
    int px = 156;

    font(FONT_SMALL);
    print(str("SUBJECT %d/%d", subj + 1, NSUBJ), px, 38, CLR_MEDIUM_GREY);
    font(FONT_NORMAL);
    print(S->name, px, 47, CLR_WHITE);

    print(str("step %d/%d", step + 1, S->nsteps), px, 64, CLR_LIGHT_GREY);
    bar(px, 74, 150, 4, (step + 1) / (float)S->nsteps, CLR_BLUE, CLR_BROWNISH_BLACK);

    // the line of code that produced this frame
    font(FONT_SMALL);
    print(S->steps[step].code, px, 88, CLR_YELLOW);
    print(S->steps[step].note, px, 98, CLR_MEDIUM_GREY);

    print(autoplay ? "Z pause   < > step by hand" : "Z play    < > step by hand",
          px, 118, CLR_DARK_GREY);
    print("U/D switch subject", px, 126, CLR_DARK_GREY);
    font(FONT_NORMAL);
}

static void draw_filmstrip(void) {
    const Subject *S = &SUBJECTS[subj];
    int y = 174;
    for (int i = 0; i < S->nsteps; i++) {
        int x = CX + i * 20;
        rectfill(x - 1, y - 1, 18, 18, i == step ? CLR_MEDIUM_GREY : CLR_DARKER_GREY);
        int last = (S->fin != FIN_NONE && i == S->nsteps - 1);
        if (!last)                    slot16(S->base + i, x, y, 16);
        else if (S->fin == FIN_SPIN)  slot16(S->fslot + anim(8, 6, 0.0f), x, y, 16);
        else  sspr((S->fslot % 8) * 16, (S->fslot / 8) * 16, 32, 32, x, y, 16, 16);
    }
}

void draw(void) {
    cls(CLR_DARKER_BLUE);

    print_scaled("SPRITE FOUNDRY", CX, 8, CLR_YELLOW, 2);
    font(FONT_TINY);
    print("EVERY SPRITE HERE IS CODE - READ FOUNDRY.CART.JS", CX, 26, CLR_DARK_GREY);
    font(FONT_NORMAL);

    draw_canvas();
    draw_panel();
    draw_filmstrip();

#ifdef DE_TRACE
    watch("subj", "%d", subj);
    watch("step", "%d", step);
    watch("auto", "%d", autoplay);
#endif
}
