/* de:meta
{
  "title": "tinyjam menu",
  "status": "active",
  "created": "2026-07-03",
  "kind": ["tech-demo"],
  "teaches": [],
  "lineage": "The umbrella-app launcher — build-ladder rung 3 of docs/design/share-panel.md. Inside a bundle (tools/build-app.js compiles it with -DAPP_BUNDLE) the roster comes from a generated app_roster.h fed by each rack's own de:meta, and picking an entry calls the dispatcher shim's app_launch(); standalone it carries a demo roster so the menu stays a runnable, bakeable cart on its own.",
  "description": {
    "summary": "The launcher screen for multi-cart apps: a humble program picker whose entries come from each cart's own de:meta.",
    "detail": "In an app bundle this is the boot screen — every rack in the manifest shows up as an entry (title from its de:meta, summary in the footer) and picking one switches cart. Standalone it runs against a built-in demo roster.",
    "controls": "up/down, hover: choose - click, tap, enter or Z: open - in a bundle, TAB comes back here"
  }
}
de:meta */

// tinyjam menu — the launcher cart for umbrella apps
//
// A multi-cart app (apps/<name>/app.json → tools/build-app.js) needs a menu screen:
// this cart is it. The whole trick is that the menu stays in cart-land — no native
// chrome — and its data comes from the racks themselves: build-app.js generates
// app_roster.h from each cart's de:meta (title + summary), so ADDING A RACK TO THE
// MANIFEST AUTO-ADDS ITS MENU ENTRY. Picking an entry calls app_launch(i), a
// dispatcher-shim function that flips both the draw/update dispatch and the sound
// context (de_switch_cart — ADR-0027). TAB in a rack returns to this overview.
//
// Standalone (no APP_BUNDLE) the same cart runs against the demo roster below, so it
// can be played, baked, and iterated like any other cart; "opening" an entry just
// marks it as the current one.

#include "studio.h"
#include "ui.h"
#include <stdio.h>
#include <stdbool.h>

#ifdef APP_BUNDLE
#include "app_roster.h" // GENERATED by build-app.js: APP_NAME, APP_ROSTER[], app_launch(), app_current()
#else
// standalone preview: a stand-in roster so the menu runs (and bakes) outside a bundle
#define APP_NAME "tinyjam"
#define APP_MASTERPASS_ID ""       // no store standalone → no "unlock all" row
#define APP_MASTERPASS_PRICE ""
typedef struct { const char *slug; const char *title; const char *desc; const char *product; const char *price; } AppRosterEntry;
#define APP_ROSTER_COUNT 3
static const AppRosterEntry APP_ROSTER[APP_ROSTER_COUNT] = {   // standalone: product/price "" = all free (no store)
    { "acidrack",  "acid rack",    "Two 303s and a 909 racked into one generative acid machine - patterns, banks, a chain row.", "", "" },
    { "yachtrack", "session desk", "The chord-first yacht-rock session desk: chart is truth, the band interprets.", "", "" },
    { "demorack",  "third rack",   "Standalone stand-in entry so the picker's shape shows without a bundle.", "", "" },
};
static int demo_current = -1;
static void app_launch(int i) { demo_current = i; }        // bundle: the shim switches carts
static int  app_current(void) { return demo_current; }     // bundle: rack we came from (-1 = none)
#endif

#define ROW_H   22
#define ROW_GAP 4
#define LIST_X  14
#define FOOT_H  34                       // footer strip for the picked entry's summary

static int sel = 0;

// IAP gate — the Store bridge from Store.swift (@_cdecl, StoreKit 2). Declared here as WEAK
// DEFINITIONS (stub bodies) so a standalone/Mac build LINKS (every rack free, no testing UI);
// inside an iOS bundle Store.swift's strong symbols override them. (A weak undefined
// *reference* / weak_import does NOT link on the current Darwin ld — a weak definition does.)
// Store_TestingAvailable is DEBUG-iOS-only → it gates the reset button so it can never ship
// in a release build.
__attribute__((weak)) bool Store_IsModuleUnlocked(const char *id) { (void)id; return true; }
__attribute__((weak)) void Store_Purchase(const char *id)         { (void)id; }
__attribute__((weak)) void Store_ResetPurchases(void)             { }
__attribute__((weak)) bool Store_TestingAvailable(void)           { return false; }

static int rack_owned(const AppRosterEntry *e) {
    return !e->product[0] || Store_IsModuleUnlocked(e->product);   // free, or entitled
}
static void pick(int i) {                           // owned/free → open; locked → buy
    const AppRosterEntry *e = &APP_ROSTER[i];
    if (!rack_owned(e)) { Store_Purchase(e->product); return; }
    app_launch(i);
}

// print `s` word-wrapped inside width w; stops at y_max, returns y after the last line
static int wrap_print(const char *s, int x, int y, int w, int y_max, int col) {
    char cur[160] = "";
    while (*s && y < y_max) {
        const char *word = s;
        while (*s && *s != ' ') s++;
        int wl = (int)(s - word);
        while (*s == ' ') s++;

        char probe[224];
        if (cur[0]) snprintf(probe, sizeof probe, "%s %.*s", cur, wl, word);
        else        snprintf(probe, sizeof probe, "%.*s", wl, word);
        if (cur[0] && text_width(probe) > w) {          // word doesn't fit: flush the line
            print(cur, x, y, col);
            y += 8;
            snprintf(probe, sizeof probe, "%.*s", wl, word);
        }
        snprintf(cur, sizeof cur, "%s", probe);
    }
    if (cur[0] && y < y_max) { print(cur, x, y, col); y += 8; }
    return y;
}

void update(void) {
    if (keyp(KEY_UP)    || btnp(0, BTN_UP))   sel = (sel + APP_ROSTER_COUNT - 1) % APP_ROSTER_COUNT;
    if (keyp(KEY_DOWN)  || btnp(0, BTN_DOWN)) sel = (sel + 1) % APP_ROSTER_COUNT;
    if (keyp(KEY_ENTER) || btnp(0, BTN_A))    pick(sel);
}

void draw(void) {
    cls(CLR_BLACK);
    ui_begin();

    // header
    font(FONT_COMIC);
    print(APP_NAME, LIST_X, 4, CLR_WHITE);
    font(FONT_NORMAL);
    if (Store_TestingAvailable())                        // DEBUG iOS only: wipe test purchases → all locked again
        if (ui_button(SCREEN_W - 46, 6, 40, 15, "reset")) Store_ResetPurchases();
    line(LIST_X, 28, SCREEN_W - LIST_X, 28, CLR_DARKER_GREY);

    int y0 = 36, w = SCREEN_W - 2 * LIST_X;
    // "unlock all" master-pass offer row sits between the list and the footer (bundle only,
    // hidden once owned). Reserve its height so the rack list doesn't run under it.
    int mp_on = APP_MASTERPASS_ID[0] && !Store_IsModuleUnlocked(APP_MASTERPASS_ID);
    int list_bot = SCREEN_H - FOOT_H - (mp_on ? (ROW_H + ROW_GAP) : 0);
    int rows_fit = (list_bot - y0) / (ROW_H + ROW_GAP);
    if (rows_fit < 1) rows_fit = 1;
    int top = sel - rows_fit + 1;               // scroll just enough to keep sel visible
    if (top < 0) top = 0;

    int cur = app_current();
    for (int r = 0; r < rows_fit && top + r < APP_ROSTER_COUNT; r++) {
        int i = top + r, y = y0 + r * (ROW_H + ROW_GAP), cy = y + (ROW_H - 6) / 2 + 1;
        int locked = !rack_owned(&APP_ROSTER[i]);
        if (ui_hover(LIST_X, y, w, ROW_H)) sel = i;
        if (ui_button(LIST_X, y, w, ROW_H, APP_ROSTER[i].title)) { sel = i; pick(i); }
        if (i == sel) print(">", LIST_X - 10, cy, CLR_YELLOW);
        if (locked) {                                   // paid + not owned → price, right-aligned
            char pr[16]; snprintf(pr, sizeof pr, "$%s", APP_ROSTER[i].price);
            print(pr, LIST_X + w - text_width(pr) - 6, cy, CLR_YELLOW);
        } else if (i == cur) print("*", LIST_X + w + 4, cy, CLR_GREEN);
    }
    if (top > 0)                                print("^", SCREEN_W - LIST_X - 6, y0 - 8, CLR_LIGHT_GREY);
    if (top + rows_fit < APP_ROSTER_COUNT)      print("v", SCREEN_W - LIST_X - 6, list_bot - 6, CLR_LIGHT_GREY);

    if (mp_on) {                                        // the "unlock all" offer
        int my = list_bot + 2;
        char lbl[40]; snprintf(lbl, sizeof lbl, "unlock all - $%s", APP_MASTERPASS_PRICE);
        if (ui_button(LIST_X, my, w, ROW_H, lbl)) Store_Purchase(APP_MASTERPASS_ID);
    }

    // footer: the picked entry's summary (the price/lock already shows on the row)
    int fy = SCREEN_H - FOOT_H;
    line(LIST_X, fy, SCREEN_W - LIST_X, fy, CLR_DARKER_GREY);
    font(FONT_SMALL);
    wrap_print(APP_ROSTER[sel].desc, LIST_X, fy + 5, w, SCREEN_H - 4, CLR_LIGHT_GREY);
    font(FONT_NORMAL);

    ui_end();
}
