const { contextBridge, ipcRenderer, webUtils } = require('electron')

contextBridge.exposeInMainWorld('studio', {
  run:          (code, cfg) => ipcRenderer.invoke('studio:run', code, cfg),
  liveWrite:    (code)      => ipcRenderer.invoke('studio:live-write', code),
  profile:      (code, cfg) => ipcRenderer.invoke('studio:profile', code, cfg),
  saveSprites:  (dataUrl) => ipcRenderer.invoke('studio:save-sprites', dataUrl),
  saveMap:      (bytes)   => ipcRenderer.invoke('studio:save-map', bytes),
  onLog:        (cb) => ipcRenderer.on('cart:log',  (_, s)    => cb(s)),
  onExit:       (cb) => ipcRenderer.on('cart:exit', (_, info) => cb(info)),
  saveCart:     (payload)  => ipcRenderer.invoke('cart:save', payload),
  loadCart:     ()         => ipcRenderer.invoke('cart:load'),
  loadCartBuffer: (bytes)   => ipcRenderer.invoke('cart:load-buffer', bytes),
  loadCartFile:   (filePath) => ipcRenderer.invoke('cart:load-file', filePath),
  getFilePath:  (file)     => webUtils.getPathForFile(file),
  buildWeb:     (code, cfg) => ipcRenderer.invoke('studio:build-web', code, cfg),
  exportWin:    (code, cfg) => ipcRenderer.invoke('studio:export-win', code, cfg),
  exportMac:    (code, cfg) => ipcRenderer.invoke('studio:export-mac', code, cfg),
  deployIos:    (code, cfg) => ipcRenderer.invoke('studio:deploy-ios', code, cfg),
  publish:      (code, cfg) => ipcRenderer.invoke('studio:publish', code, cfg),
  openExternal: (url)       => ipcRenderer.invoke('studio:open-external', url),
  openPath:     (p)         => ipcRenderer.invoke('studio:open-path', p),
  setCartName:  (name)     => ipcRenderer.send('cart:set-name', name),
  // Apps view
  listApps:     ()               => ipcRenderer.invoke('studio:list-apps'),
  asoResearch:  (terms, country) => ipcRenderer.invoke('studio:aso-research', terms, country),
  asoLint:      (fields)         => ipcRenderer.invoke('studio:aso-lint', fields),
  asoCompose:   (fields)         => ipcRenderer.invoke('studio:aso-compose', fields),
  onAsoLog:     (cb)             => ipcRenderer.on('aso:log', (_, s) => cb(s)),
  buildApp:     (name, target)   => ipcRenderer.invoke('studio:build-app', name, target),
  pressKit:     (name)           => ipcRenderer.invoke('studio:press-kit', name),
  asoApp:       (name, tool)     => ipcRenderer.invoke('studio:aso-app', name, tool),
  appShots:     (name)           => ipcRenderer.invoke('studio:app-shots', name),
  appSeeds:     (name)           => ipcRenderer.invoke('studio:app-seeds', name),
})
