const { contextBridge, ipcRenderer, webUtils } = require('electron')

contextBridge.exposeInMainWorld('studio', {
  run:          (code, cfg) => ipcRenderer.invoke('studio:run', code, cfg),
  record:       (code, cfg) => ipcRenderer.invoke('studio:record', code, cfg),
  replay:       (code, cfg, recPath) => ipcRenderer.invoke('studio:replay', code, cfg, recPath),
  onRecorded:   (cb) => ipcRenderer.on('cart:recorded', (_, info) => cb(info)),
  liveWrite:    (code)      => ipcRenderer.invoke('studio:live-write', code),
  profile:      (code, cfg) => ipcRenderer.invoke('studio:profile', code, cfg),
  saveSprites:  (dataUrl) => ipcRenderer.invoke('studio:save-sprites', dataUrl),
  saveMap:      (bytes)   => ipcRenderer.invoke('studio:save-map', bytes),
  onLog:        (cb) => ipcRenderer.on('cart:log',  (_, s)    => cb(s)),
  onExit:       (cb) => ipcRenderer.on('cart:exit', (_, info) => cb(info)),
  saveCart:     (payload)  => ipcRenderer.invoke('cart:save', payload),
  loadCart:     ()         => ipcRenderer.invoke('cart:load'),
  loadCartBuffer: (bytes)   => ipcRenderer.invoke('cart:load-buffer', bytes),
  loadCartFile:   (filePath) => ipcRenderer.invoke('cart:load-file', filePath),
  getFilePath:  (file)     => webUtils.getPathForFile(file),
  buildWeb:     (code, cfg) => ipcRenderer.invoke('studio:build-web', code, cfg),
  exportWin:    (code, cfg) => ipcRenderer.invoke('studio:export-win', code, cfg),
  exportMac:    (code, cfg) => ipcRenderer.invoke('studio:export-mac', code, cfg),
  deployIos:    (code, cfg) => ipcRenderer.invoke('studio:deploy-ios', code, cfg),
  publish:      (code, cfg) => ipcRenderer.invoke('studio:publish', code, cfg),
  openExternal: (url)       => ipcRenderer.invoke('studio:open-external', url),
  openPath:     (p)         => ipcRenderer.invoke('studio:open-path', p),
  revealPath:   (p)         => ipcRenderer.invoke('studio:reveal-path', p),
  setCartName:  (name)     => ipcRenderer.send('cart:set-name', name),
  // Apps view
  listApps:     ()               => ipcRenderer.invoke('studio:list-apps'),
  asoResearch:  (terms, country) => ipcRenderer.invoke('studio:aso-research', terms, country),
  asoSuggest:   (terms, country) => ipcRenderer.invoke('studio:aso-suggest', terms, country),
  asoBrief:     (name)           => ipcRenderer.invoke('studio:aso-brief', name),
  asoCoverage:  (name)           => ipcRenderer.invoke('studio:aso-coverage', name),
  asoScore:     (name)           => ipcRenderer.invoke('studio:aso-score', name),
  appClips:     (name)           => ipcRenderer.invoke('studio:app-clips', name),
  buildReel:    (name, rows, loop) => ipcRenderer.invoke('studio:build-reel', name, rows, loop),
  asoLint:      (fields)         => ipcRenderer.invoke('studio:aso-lint', fields),
  asoCompose:   (fields)         => ipcRenderer.invoke('studio:aso-compose', fields),
  onAsoLog:     (cb)             => ipcRenderer.on('aso:log', (_, s) => cb(s)),
  buildApp:     (name, target)   => ipcRenderer.invoke('studio:build-app', name, target),
  pressKit:     (name)           => ipcRenderer.invoke('studio:press-kit', name),
  asoApp:       (name, tool)     => ipcRenderer.invoke('studio:aso-app', name, tool),
  appShots:     (name)           => ipcRenderer.invoke('studio:app-shots', name),
  appSeeds:     (name, source)   => ipcRenderer.invoke('studio:app-seeds', name, source),
  leads:        (name)           => ipcRenderer.invoke('studio:leads', name),
  cartLeads:    (cart)           => ipcRenderer.invoke('studio:cart-leads', cart),
  cartClips:    (cart)           => ipcRenderer.invoke('studio:cart-clips', cart),
  // App Store metadata: dry-run returns a structured PLAN; { push:[fields] } PATCHes only those live
  ascMetadata:  (name, opts)     => ipcRenderer.invoke('studio:asc-metadata', name, opts),
})
