module.exports = {
  sprites: {
    // 4-frame walk cycle, slots 1-4
    // W=skin, Y=yellow hair, B=dark blue body, b=bright blue legs, .=transparent

    1: `
................
.....YYYYY......
....YWWWWWY.....
....WWWWWWW.....
....WWWWWWW.....
.....YYYYY......
....BBBBBBB.....
....BBBBBBB.....
....BBBBBBB.....
.....BBBBB......
......bBb.......
......bBb.......
......bBb.......
.....bBBBb......
.....B...B......
................
`,
    2: `
................
.....YYYYY......
....YWWWWWY.....
....WWWWWWW.....
....WWWWWWW.....
.....YYYYY......
....BBBBBBB.....
....BBBBBBB.....
....BBBBBBB.....
.....BBBBB......
....bB...Bb.....
...bB.....Bb....
..bB.......bB...
.bB.........B...
BB...........B..
................
`,
    3: `
................
.....YYYYY......
....YWWWWWY.....
....WWWWWWW.....
....WWWWWWW.....
.....YYYYY......
....BBBBBBB.....
....BBBBBBB.....
....BBBBBBB.....
.....BBBBB......
.....bBBBb......
....bBBBBBb.....
....B.....B.....
...B.......B....
...B.......B....
................
`,
    4: `
................
.....YYYYY......
....YWWWWWY.....
....WWWWWWW.....
....WWWWWWW.....
.....YYYYY......
....BBBBBBB.....
....BBBBBBB.....
....BBBBBBB.....
.....BBBBB......
....bB...Bb.....
...bB.....Bb....
..bB.......bB...
..B.........bB..
..B..........BB.
................
`,
  },
}
