// bake-fonts.c — bake the engine's fixed ROM bitmap fonts into runtime/fonts_baked.h.
//
// WHY: studio.c builds each font with Raylib's LoadFontFromImage (which scans the
// keyed atlas to compute glyph rects/offsets/advances) and then reads the atlas
// back off the GPU for the software-canvas text path (sw_print). Neither works on
// a non-Raylib backend (iOS/Switch). Since these fonts are FIXED ROM assets, we
// run Raylib's real LoadFontFromImage ONCE here, at build time, and emit the keyed
// RGBA atlas pixels + the exact glyph table it produced. The DE_NO_RAYLIB sw_print
// path then reads this baked data — identical layout to Raylib's, no GPU, no
// runtime font-atlas scan.
//
// BUILD + RUN (from repo root):
//   clang tools/bake-fonts.c -I runtime -I /usr/local/include /usr/local/lib/libraylib.a \
//     -framework OpenGL -framework Cocoa -framework IOKit -framework CoreVideo \
//     -framework CoreFoundation -framework CoreMIDI -o build/bake-fonts && build/bake-fonts
// Output: runtime/fonts_baked.h  (regenerate only when a ROM font changes).

#include "raylib.h"
#include <stdio.h>
#include <stdint.h>

#include "dos_8x8_font.h"
#include "font4x6_data.h"
#include "font3x5_data.h"
#include "fontcomic10x20_data.h"
#include "fontthin8x8_data.h"

typedef struct { const char *name; const unsigned char *data; int len; int firstChar; } Spec;

int main(void) {
    SetTraceLogLevel(LOG_WARNING);
    SetConfigFlags(FLAG_WINDOW_HIDDEN);          // GL context (for LoadFontFromImage + readback) without a visible window
    InitWindow(64, 64, "bake-fonts");

    // order + firstChar mirror studio.c's font init exactly
    Spec specs[] = {
        { "game_font",  DOS_8X8_FONT,        DOS_8X8_FONT_LEN,        0  },
        { "font_small", FONT4X6_DATA,        FONT4X6_DATA_LEN,        32 },
        { "font_tiny",  FONT3X5_DATA,        FONT3X5_DATA_LEN,        32 },
        { "font_comic", FONTCOMIC10X20_DATA, FONTCOMIC10X20_DATA_LEN, 0  },
        { "font_thin",  FONTTHIN8X8_DATA,    FONTTHIN8X8_DATA_LEN,    0  },
    };
    int nfonts = (int)(sizeof specs / sizeof specs[0]);
    int aw[8], ah[8], bs[8], gc[8];              // per-font dims/counts, captured for the summary table

    FILE *f = fopen("runtime/fonts_baked.h", "w");
    if (!f) { fprintf(stderr, "cannot open runtime/fonts_baked.h\n"); return 1; }

    fprintf(f,
        "// AUTO-GENERATED by tools/bake-fonts.c — DO NOT EDIT.\n"
        "// Baked ROM fonts for the DE_NO_RAYLIB (software / iOS / Switch) text path:\n"
        "// keyed RGBA8888 atlas pixels + the glyph table Raylib's LoadFontFromImage produced.\n"
        "// Regenerate with tools/bake-fonts.c when a ROM font changes.\n"
        "#ifndef DE_FONTS_BAKED_H\n"
        "#define DE_FONTS_BAKED_H\n"
        "#include <stdint.h>\n\n"
        "typedef struct { int value; float x, y, w, h; int offX, offY, advX; } DeBakedGlyph;\n"
        "typedef struct {\n"
        "    const char *name;\n"
        "    int atlasW, atlasH;\n"
        "    const uint32_t *atlas;     // RGBA8888, atlasW*atlasH, top-left origin\n"
        "    int baseSize, glyphCount;\n"
        "    const DeBakedGlyph *glyphs;\n"
        "} DeBakedFont;\n\n");

    for (int i = 0; i < nfonts; i++) {
        Image img = LoadImageFromMemory(".png", specs[i].data, specs[i].len);
        Font fnt  = LoadFontFromImage(img, (Color){ 255, 255, 0, 255 }, specs[i].firstChar);
        Image atlas = LoadImageFromTexture(fnt.texture);
        ImageFormat(&atlas, PIXELFORMAT_UNCOMPRESSED_R8G8B8A8);
        uint32_t *px = (uint32_t*)atlas.data;
        int npx = atlas.width * atlas.height;
        aw[i] = atlas.width; ah[i] = atlas.height; bs[i] = fnt.baseSize; gc[i] = fnt.glyphCount;

        fprintf(f, "// ---- %s : %dx%d atlas, %d glyphs, baseSize %d ----\n",
                specs[i].name, atlas.width, atlas.height, fnt.glyphCount, fnt.baseSize);
        fprintf(f, "static const uint32_t %s_atlas[%d] = {", specs[i].name, npx);
        for (int p = 0; p < npx; p++) {
            if (p % 12 == 0) fprintf(f, "\n  ");
            fprintf(f, "0x%08x,", px[p]);
        }
        fprintf(f, "\n};\n");

        fprintf(f, "static const DeBakedGlyph %s_glyphs[%d] = {\n", specs[i].name, fnt.glyphCount);
        for (int g = 0; g < fnt.glyphCount; g++) {
            Rectangle r = fnt.recs[g];
            fprintf(f, "  { %d, %g, %g, %g, %g, %d, %d, %d },\n",
                    fnt.glyphs[g].value, r.x, r.y, r.width, r.height,
                    fnt.glyphs[g].offsetX, fnt.glyphs[g].offsetY, fnt.glyphs[g].advanceX);
        }
        fprintf(f, "};\n\n");

        UnloadImage(atlas);
        UnloadFont(fnt);
        UnloadImage(img);
    }

    fprintf(f, "enum { DE_FONT_GAME, DE_FONT_SMALL, DE_FONT_TINY, DE_FONT_COMIC, DE_FONT_THIN, DE_FONT_COUNT };\n");
    fprintf(f, "static const DeBakedFont DE_BAKED_FONTS[%d] = {\n", nfonts);
    for (int i = 0; i < nfonts; i++)
        fprintf(f, "  { \"%s\", %d, %d, %s_atlas, %d, %d, %s_glyphs },\n",
                specs[i].name, aw[i], ah[i], specs[i].name, bs[i], gc[i], specs[i].name);
    fprintf(f, "};\n\n#endif // DE_FONTS_BAKED_H\n");

    fclose(f);
    CloseWindow();
    printf("baked %d fonts -> runtime/fonts_baked.h\n", nfonts);
    return 0;
}
