module.exports = {
  sprites: {
    // slot 1: a little rocket pointing UP (asymmetric so rotation reads clearly)
    // W=white body, b=bright blue window, R=red fins, O=orange, Y=yellow flame, .=transparent
    1: `
.......WW.......
.......WW.......
......WWWW......
......WbbW......
......WbbW......
.....WWWWWW.....
.....WWWWWW.....
.....WWWWWW.....
....RWWWWWWR....
...RRWWWWWWRR...
...RR.WWWW.RR...
......WWWW......
......OOOO......
......YOOY......
.......YY.......
................
`,
  },
}
