#!/usr/bin/env node
// gen-drumpat.js — GENERATE runtime/drumpat.h from tools/drum-patterns.json.
//
//   node tools/gen-drumpat.js                 # write runtime/drumpat.h
//   node tools/gen-drumpat.js --check         # exit nonzero if the header is stale (repo-doctor)
//   node tools/gen-drumpat.js --selfcheck     # round-trip every row + known answers
//   node tools/gen-drumpat.js --import <x.lua>  # re-parse the maker's own Lua file into the JSON
//
// WHERE THE DATA COMES FROM. The maker keeps a hand-built pattern library in a love2d
// project (drum-patterns.lua), whose own header cites "Drum Machine - 260 Patterns"
// (archive.org item 260DrumMachinePatterns) for its core set. That file lives OUTSIDE this
// repo, so the parsed form is committed here as the in-repo source of truth and --import
// refreshes it. Group provenance is UNVERIFIED PER GROUP: the CR78 and the classic-genre
// groups match the cited book, the later ones (EDM, dubstep, boombap…) carry no citation.
//
// NOT the same thing as runtime/rhythmbox.h. That one is 76 rhythms read off manufacturer
// service manuals, on the machines' own clocks (24 or 32 counts, gates, skipped states).
// THIS one is 16 steps of sixteenths: a step-sequencer grid, a big modern vocabulary, and
// structurally unable to express what those machines did. Keep them apart on purpose.
const fs = require('fs'), path = require('path');
const JSONF = path.join(__dirname, 'drum-patterns.json');
const OUT   = path.join(__dirname, '..', 'runtime', 'drumpat.h');

// voices first, ACCENT last: it is a velocity lane, not a drum
const ROLES = ['BD','SD','LT','MT','HT','CH','OH','CY','RS','CB','CPS','TB','AC'];
const DOC = { BD:'bass drum', SD:'snare', LT:'low tom', MT:'mid tom', HT:'high tom',
  CH:'closed hi-hat', OH:'open hi-hat', CY:'cymbal', RS:'rim shot', CB:'cowbell',
  CPS:'claps', TB:'tambourine', AC:'accent (a velocity lane, NOT a voice)' };

// ── the Lua importer (only used by --import) ──────────────────────────────
// A minimal reader for the restricted table syntax that file uses. Blocks the author had
// COMMENTED OUT are counted and skipped: they are his disabled non-16-step patterns, and
// dropping them silently would misreport the library's size.
function importLua(file) {
  const src = fs.readFileSync(file, 'utf8');
  let disabled = 0;
  const noBlock = src.replace(/--\[\[[\s\S]*?--?\]\]/g, m => { if (/grid\s*=/.test(m)) disabled++; return ''; });
  const clean = noBlock.replace(/^\s*--.*$/gm, '');
  let i = clean.indexOf('{', clean.indexOf('local patterns'));
  const ws = () => { while (i < clean.length && /\s/.test(clean[i])) i++; };
  function value() {
    ws();
    if (clean[i] === '{') return table();
    if (clean[i] === '"') { let j = ++i, s = ''; while (clean[j] !== '"') s += clean[j++]; i = j + 1; return s; }
    let j = i; while (!/[,}\s]/.test(clean[j])) j++;
    const t = clean.slice(i, j); i = j; return isNaN(+t) ? t : +t;
  }
  function table() {
    i++; const arr = [], obj = {}; let isObj = false;
    for (;;) {
      ws();
      if (clean[i] === '}') { i++; break; }
      const m = /^([A-Za-z_][A-Za-z0-9_]*)\s*=/.exec(clean.slice(i, i + 40));
      if (m) { i += m[0].length; isObj = true; obj[m[1]] = value(); } else arr.push(value());
      ws(); if (clean[i] === ',') i++;
    }
    return isObj ? obj : arr;
  }
  const machines = table();
  fs.writeFileSync(JSONF, JSON.stringify({ disabledBlocks: disabled, machines }, null, 1));
  const n = machines.reduce((a, m) => a + (m.sections || []).length, 0);
  console.log(`imported ${machines.length} groups, ${n} patterns, skipped ${disabled} disabled blocks`);
}

// ── emit ──────────────────────────────────────────────────────────────────
const mask = (s, ch) => { let m = 0; for (let k = 0; k < 16; k++) if (s[k] === ch) m |= 1 << k; return m; };
function build() {
  const { machines, disabledBlocks } = JSON.parse(fs.readFileSync(JSONF, 'utf8'));
  const pats = [], groups = [];
  for (const g of machines) {
    const first = pats.length;
    for (const s of (g.sections || [])) {
      const hit  = ROLES.map(r => { const w = s.grid[r]; return w ? (mask(w, 'x') | mask(w, 'f')) : 0; });
      const flam = ROLES.map(r => { const w = s.grid[r]; return w ? mask(w, 'f') : 0; });
      pats.push({ name: s.name, hit, flam, anyFlam: flam.some(v => v) });
    }
    groups.push({ name: g.name, first, count: pats.length - first });
  }
  return { pats, groups, disabledBlocks };
}
function emit({ pats, groups, disabledBlocks }) {
  const hex = v => '0x' + v.toString(16).padStart(4, '0');
  const L = [];
  L.push('// drumpat.h — GENERATED by tools/gen-drumpat.js from tools/drum-patterns.json.');
  L.push('// DO NOT HAND-EDIT: edit the JSON (or re-run --import) and regenerate.');
  L.push('//');
  L.push(`// ${pats.length} patterns in ${groups.length} named groups, bit-packed: one uint16 per role per`);
  L.push(`// pattern, bit i = step i. The whole library is ${(pats.length * ROLES.length * 2 / 1024).toFixed(1)} KB of rodata, not a wall of strings.`);
  L.push('//');
  L.push('// WHAT THIS IS NOT: a machine. Every pattern here is 16 steps of SIXTEENTHS, which is a');
  L.push('// step-sequencer grid. It structurally CANNOT express what the real organ-era rhythm');
  L.push('// boxes did — 24 counts per bar, six per beat, held gates, skipped states, two-bar');
  L.push('// claves — so for period-correct hardware patterns use runtime/rhythmbox.h instead');
  L.push('// (76 rhythms off manufacturer service manuals). Reach for THIS one when you want a big');
  L.push('// vocabulary of modern grooves and a plain 16-step grid is the right shape.');
  L.push('//');
  L.push('// PROVENANCE, and it is uneven: converted from the maker\'s own drum-patterns.lua, whose');
  L.push('// header cites "Drum Machine - 260 Patterns" (archive.org 260DrumMachinePatterns) for its');
  L.push('// core set. The CR78 and classic-genre groups match that citation; the later groups (EDM,');
  L.push('// dubstep, boombap and friends) carry none, so treat group provenance as UNVERIFIED PER');
  L.push(`// GROUP. The ${disabledBlocks} non-16-step patterns the original had commented out are NOT here.`);
  L.push('//');
  L.push('// ACCENT is a lane, not a voice: DP_AC marks steps that play LOUDER. Read it with');
  L.push('// dp_accent() and scale velocity; never fire a drum for it.');
  L.push('// FLAM: some steps are marked \'f\' rather than \'x\' in the original. They are hits AND');
  L.push('// flams, so dp_hit() sees them and dp_flam() tells you to double the stroke.');
  L.push('#ifndef DRUMPAT_H');
  L.push('#define DRUMPAT_H');
  L.push('');
  L.push('#define DP_STEPS 16');
  L.push('');
  ROLES.forEach((r, i) => L.push(`#define DP_${r}${' '.repeat(4 - r.length)} ${i}   // ${DOC[r]}`));
  L.push(`#define DP_NROLES ${ROLES.length}`);
  L.push('');
  L.push('typedef struct { const char *name; unsigned short hit[DP_NROLES], flam[DP_NROLES]; } DrumPat;');
  L.push('typedef struct { const char *name; short first, count; } DrumPatGroup;');
  L.push('');
  L.push(`static const DrumPat DP_PAT[${pats.length}] = {`);
  for (const p of pats)
    L.push(`    { "${p.name}", {${p.hit.map(hex).join(',')}}, {${p.anyFlam ? p.flam.map(hex).join(',') : '0'}} },`);
  L.push('};');
  L.push(`#define DP_NPAT ${pats.length}`);
  L.push('');
  L.push(`static const DrumPatGroup DP_GROUP[${groups.length}] = {`);
  for (const g of groups) L.push(`    { "${g.name}", ${g.first}, ${g.count} },`);
  L.push('};');
  L.push(`#define DP_NGROUP ${groups.length}`);
  L.push('');
  L.push('static inline int dp_hit(int pat, int role, int step)  { return (DP_PAT[pat].hit[role]  >> (step & 15)) & 1; }');
  L.push('static inline int dp_flam(int pat, int role, int step) { return (DP_PAT[pat].flam[role] >> (step & 15)) & 1; }');
  L.push('static inline int dp_accent(int pat, int step)         { return dp_hit(pat, DP_AC, step); }');
  L.push('static inline int dp_role_used(int pat, int role)      { return DP_PAT[pat].hit[role] != 0; }');
  L.push('');
  L.push('#endif // DRUMPAT_H');
  return L.join('\n') + '\n';
}

const argv = process.argv.slice(2);
const imp = argv.indexOf('--import');
if (imp >= 0) { importLua(argv[imp + 1]); process.exit(0); }

const model = build();
const text = emit(model);

if (argv.includes('--selfcheck')) {
  // rebuild every row string FROM THE EMITTED TEXT and diff against the JSON, so the
  // check tests what ships rather than what is in memory
  const rows = [...text.matchAll(/^    \{ "((?:[^"\\]|\\.)*)", \{([^}]*)\}, \{([^}]*)\} \},$/gm)];
  const { machines } = JSON.parse(fs.readFileSync(JSONF, 'utf8'));
  const flat = []; for (const g of machines) for (const s of (g.sections || [])) flat.push(s);
  const un = (m, f) => { let s = ''; for (let k = 0; k < 16; k++) s += ((f >> k) & 1) ? 'f' : (((m >> k) & 1) ? 'x' : '.'); return s; };
  let bad = 0, cells = 0;
  if (rows.length !== flat.length) { console.error(`row count ${rows.length} != ${flat.length}`); process.exit(1); }
  rows.forEach((r, i) => {
    const hit = r[2].split(',').map(v => parseInt(v, 16)), flam = r[3].split(',').map(v => parseInt(v, 16));
    if (r[1] !== flat[i].name) { console.error(`name mismatch at ${i}`); bad++; }
    ROLES.forEach((role, ri) => {
      const want = flat[i].grid[role] || null, got = un(hit[ri] || 0, flam[ri] || 0);
      cells++;
      if (want === null) { if (hit[ri]) { console.error(`phantom ${i} ${role}`); bad++; } }
      else if (want !== got) { console.error(`row diff ${i} ${role}\n  want ${want}\n  got  ${got}`); bad++; }
    });
  });
  // known answers: the packing convention itself, and the two lanes that are not drums
  const P = model.pats;
  const step0 = P.findIndex(p => (p.hit[0] & 1) === 1);
  if (step0 < 0) { console.error('no pattern has a bass drum on step 0 — packing is suspect'); bad++; }
  const flams = P.reduce((n, p) => n + p.flam.reduce((m, v) => m + (v ? 1 : 0), 0), 0);
  if (flams === 0) { console.error('no flams survived the conversion'); bad++; }
  console.log(bad ? `FAIL: ${bad} problems` : `PASS: ${rows.length} patterns, ${cells} role slots round-trip exactly, flams present`);
  process.exit(bad ? 1 : 0);
}
if (argv.includes('--check')) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (cur !== text) { console.error('runtime/drumpat.h is STALE — run: node tools/gen-drumpat.js'); process.exit(1); }
  console.log('runtime/drumpat.h is up to date'); process.exit(0);
}
fs.writeFileSync(OUT, text);
console.log(`wrote runtime/drumpat.h — ${model.pats.length} patterns, ${model.groups.length} groups`);
