// config for gorillas.c
// slot 1 = gorilla (front-facing, 16×16)

module.exports = {
  sprites: {

    // slot 1 — gorilla
    // N=brown(4)  p=peach(15)  L=light-grey(6)  S=dark-grey(5)  .=transparent
    1: `
................
....NNNNNNNN....
...NppppppppN...
...NpSSppSSpN...
...NpppppppN....
...NNpppppNN....
....NNpppNN.....
...NLLLLLLLN....
..NNLLLLLLLNN...
.NNN.LLLLL.NNN..
.Np..LLLLL..pN..
...NNLLLLLNN....
....NNNNNNN.....
....NN...NN.....
....NN...NN.....
....pp...pp.....
`,

  },
}
