#!/usr/bin/env node
// One-shot: merge faceted tags (kind[] + genre) into editor/public/carts/index.json.
// Validates every value against the controlled vocabulary below, enforces
// "genre present iff kind includes 'game'", and requires 100% coverage.
const fs = require("fs");
const path = require("path");

const KINDS  = ["tutorial", "game", "tech-demo", "instrument", "toy", "tool"];
const GENRES = ["arcade", "shooter", "platformer", "fighting", "puzzle", "racing",
                "sports", "strategy", "rpg", "adventure", "simulation", "sandbox", "tabletop"];

// file -> { kind:[...], genre?, homage? }
const TAGS = {
  "zoo.cart.png":            { kind: ["toy", "tech-demo"] },
  "01-hello.cart.png":       { kind: ["tutorial"] },
  "02-shapes.cart.png":      { kind: ["tutorial"] },
  "03-move.cart.png":        { kind: ["tutorial"] },
  "04-buttons.cart.png":     { kind: ["tutorial"] },
  "05-sprite.cart.png":      { kind: ["tutorial"] },
  "05b-colorkey.cart.png":   { kind: ["tutorial"] },
  "06-sound.cart.png":       { kind: ["tutorial"] },
  "07-score.cart.png":       { kind: ["tutorial"] },
  "08-catchstar.cart.png":   { kind: ["tutorial"] },
  "09-enemies.cart.png":     { kind: ["tutorial"] },
  "10-world.cart.png":       { kind: ["tutorial"] },
  "11-noise.cart.png":       { kind: ["tutorial"] },
  "12-hiscore.cart.png":     { kind: ["tutorial"] },
  "13-easing.cart.png":      { kind: ["tutorial"] },
  "14-hud.cart.png":         { kind: ["tutorial"] },
  "15-anim.cart.png":        { kind: ["tutorial"] },
  "16-spirograph.cart.png":  { kind: ["tutorial"] },
  "17-hypotrochoid.cart.png":{ kind: ["tutorial"] },
  "particles.cart.png":      { kind: ["tutorial"] },
  "juice.cart.png":          { kind: ["tutorial"] },
  "effects.cart.png":        { kind: ["tutorial"] },
  "typesave.cart.png":       { kind: ["tutorial"] },
  "patterns.cart.png":       { kind: ["tutorial"] },
  "holes.cart.png":          { kind: ["tutorial"] },
  "fillp_anchor.cart.png":   { kind: ["tutorial"] },
  "raycaster.cart.png":      { kind: ["tech-demo"] },
  "drummachine.cart.png":    { kind: ["instrument"] },
  "18-invaders.cart.png":    { kind: ["game"], genre: "shooter",    homage: "Space Invaders (1978)" },
  "19-breakout.cart.png":    { kind: ["game"], genre: "arcade",     homage: "Breakout (1976)" },
  "20-instruments.cart.png": { kind: ["tutorial"] },
  "21-lfo.cart.png":         { kind: ["tutorial"] },
  "22-filter.cart.png":      { kind: ["tutorial"] },
  "moog.cart.png":           { kind: ["instrument"] },
  "modrack.cart.png":        { kind: ["instrument"] },
  "heldnotes.cart.png":      { kind: ["instrument"] },
  "otamatone.cart.png":      { kind: ["instrument"] },
  "glassharmonica.cart.png": { kind: ["instrument"] },
  "hurdygurdy.cart.png":     { kind: ["instrument"] },
  "musicalsaw.cart.png":     { kind: ["instrument"] },
  "stylophone.cart.png":     { kind: ["instrument"] },
  "pong.cart.png":           { kind: ["game"], genre: "sports",     homage: "Pong (1972)" },
  "asteroids.cart.png":      { kind: ["game"], genre: "shooter",    homage: "Asteroids (1979)" },
  "snake.cart.png":          { kind: ["game"], genre: "arcade" },
  "robotron.cart.png":       { kind: ["game"], genre: "shooter",    homage: "Robotron: 2084 (1982)" },
  "platform.cart.png":       { kind: ["game"], genre: "platformer" },
  "lander.cart.png":         { kind: ["game"], genre: "arcade",     homage: "Lunar Lander (1979)" },
  "gta.cart.png":            { kind: ["game"], genre: "sandbox",    homage: "Grand Theft Auto (1997)" },
  "frogger.cart.png":        { kind: ["game"], genre: "arcade",     homage: "Frogger (1981)" },
  "paratrooper.cart.png":    { kind: ["game"], genre: "shooter",    homage: "Paratrooper (1982)" },
  "gorillas.cart.png":       { kind: ["game"], genre: "strategy",   homage: "Gorillas (QBasic, 1991)" },
  "racer.cart.png":          { kind: ["game"], genre: "racing" },
  "rocketleague.cart.png":   { kind: ["game"], genre: "sports",     homage: "Rocket League (2015)" },
  "garden.cart.png":         { kind: ["toy"] },
  "splatoon.cart.png":       { kind: ["game", "tech-demo"], genre: "sandbox", homage: "Splatoon (2015)" },
  "alleycat.cart.png":       { kind: ["game"], genre: "platformer", homage: "Alley Cat (1984)" },
  "sopwith.cart.png":        { kind: ["game"], genre: "shooter",    homage: "Sopwith (1984)" },
  "paperio.cart.png":        { kind: ["game"], genre: "sandbox",    homage: "Paper.io (2016)" },
  "geometrydash.cart.png":   { kind: ["game"], genre: "platformer", homage: "Geometry Dash (2013)" },
  "binaryhand.cart.png":     { kind: ["tech-demo"] },
  "burgertime.cart.png":     { kind: ["game"], genre: "arcade",     homage: "BurgerTime (1982)" },
  "fartsynth.cart.png":      { kind: ["instrument"] },
  "city.cart.png":           { kind: ["game"], genre: "simulation", homage: "SimCity (1989)" },
  "katamari.cart.png":       { kind: ["game"], genre: "sandbox",    homage: "Katamari Damacy (2004)" },
  "pacman.cart.png":         { kind: ["game"], genre: "arcade",     homage: "Pac-Man (1980)" },
  "vampire.cart.png":        { kind: ["game"], genre: "shooter",    homage: "Vampire Survivors (2022)" },
  "fighter.cart.png":        { kind: ["game"], genre: "fighting" },
  "fire.cart.png":           { kind: ["game"], genre: "arcade",     homage: "Fire! (Game & Watch, 1980)" },
  "poker.cart.png":          { kind: ["game"], genre: "tabletop" },
  "mode7.cart.png":          { kind: ["game", "tech-demo"], genre: "racing" },
  "tetris.cart.png":         { kind: ["game"], genre: "puzzle",     homage: "Tetris (1984)" },
  "lsystem.cart.png":        { kind: ["tech-demo"] },
  "adventure.cart.png":      { kind: ["game"], genre: "adventure" },
  "rogue.cart.png":          { kind: ["game"], genre: "rpg",        homage: "Rogue (1980)" },
  "pet.cart.png":            { kind: ["toy"] },
  "sokoban.cart.png":        { kind: ["game"], genre: "puzzle",     homage: "Sokoban (1981)" },
  "pathfinding.cart.png":    { kind: ["tech-demo"] },
  "pitfall.cart.png":        { kind: ["game"], genre: "platformer", homage: "Pitfall! (1982)" },
  "towerdefense.cart.png":   { kind: ["game"], genre: "strategy" },
  "sort.cart.png":           { kind: ["tech-demo"] },
  "doomfire.cart.png":       { kind: ["tech-demo"] },
  "pendulum.cart.png":       { kind: ["tech-demo"] },
  "cube3d.cart.png":         { kind: ["tech-demo"] },
  "solid3d.cart.png":        { kind: ["tech-demo"] },
  "textured3d.cart.png":     { kind: ["tech-demo"] },
  "insult.cart.png":         { kind: ["tech-demo"] },
  "slots.cart.png":          { kind: ["game"], genre: "tabletop" },
  "sims.cart.png":           { kind: ["game"], genre: "simulation", homage: "The Sims (2000)" },
  "pang.cart.png":           { kind: ["game"], genre: "arcade",     homage: "Pang (1989)" },
  "bomberman.cart.png":      { kind: ["game"], genre: "arcade",     homage: "Bomberman (1983)" },
  "bubblebobble.cart.png":   { kind: ["game"], genre: "platformer", homage: "Bubble Bobble (1986)" },
  "maze.cart.png":           { kind: ["tech-demo"] },
  "astar.cart.png":          { kind: ["tech-demo"] },
  "ripple.cart.png":         { kind: ["tech-demo"] },
  "rope.cart.png":           { kind: ["tech-demo"] },
  "boids.cart.png":          { kind: ["tech-demo"] },
  "zelda.cart.png":          { kind: ["game"], genre: "rpg",        homage: "The Legend of Zelda (1986)" },
  "sand.cart.png":           { kind: ["tech-demo"] },
  "papers.cart.png":         { kind: ["game"], genre: "simulation", homage: "Papers, Please (2013)" },
  "joust.cart.png":          { kind: ["game"], genre: "arcade",     homage: "Joust (1982)" },
  "xevious.cart.png":        { kind: ["game"], genre: "shooter",    homage: "Xevious (1983)" },
  "elite.cart.png":          { kind: ["game", "tech-demo"], genre: "shooter", homage: "Elite (1984)" },
  "mule.cart.png":           { kind: ["game"], genre: "strategy",   homage: "M.U.L.E. (1983)" },
  "galaga.cart.png":         { kind: ["game"], genre: "shooter",    homage: "Galaga (1981)" },
  "orion.cart.png":          { kind: ["game"], genre: "strategy",   homage: "Master of Orion (1993)" },
  "fourx.cart.png":          { kind: ["game"], genre: "strategy" },
  "omnichord.cart.png":      { kind: ["instrument"] },
  "classic-starter.cart.png":{ kind: ["tech-demo"] },
  "crowd.cart.png":          { kind: ["tech-demo"] },
  "sensi.cart.png":          { kind: ["game"], genre: "sports",     homage: "Sensible Soccer (1992)" },
  "druglord.cart.png":       { kind: ["game"], genre: "simulation", homage: "Drug Wars (1984)" },
  "neonrain.cart.png":       { kind: ["game"], genre: "adventure" },
  "turfwar.cart.png":        { kind: ["game"], genre: "sandbox" },
  "finalfight.cart.png":     { kind: ["game"], genre: "fighting",   homage: "Final Fight (1989)" },
  "rivercity.cart.png":      { kind: ["game"], genre: "fighting",   homage: "River City Ransom (1989)" },
  "doom.cart.png":           { kind: ["game", "tech-demo"], genre: "shooter", homage: "Doom (1993)" },
  "xcom.cart.png":           { kind: ["game"], genre: "strategy",   homage: "X-COM: UFO Defense (1994)" },
  "pizzatycoon.cart.png":    { kind: ["game"], genre: "simulation", homage: "Pizza Tycoon (1994)" },
  "dune.cart.png":           { kind: ["game"], genre: "strategy",   homage: "Dune II (1992)" },
  "cannonfodder.cart.png":   { kind: ["game"], genre: "strategy",   homage: "Cannon Fodder (1993)" },
  "tradewinds.cart.png":     { kind: ["game"], genre: "simulation" },
  "outrun.cart.png":         { kind: ["game"], genre: "racing",     homage: "OutRun (1986)" },
  "opwolf.cart.png":         { kind: ["game"], genre: "shooter",    homage: "Operation Wolf (1987)" },
  "podracer.cart.png":       { kind: ["game", "tech-demo"], genre: "racing", homage: "Star Wars Episode I: Racer (1999)" },
  "trifill_stress.cart.png": { kind: ["tech-demo"] },
  "excitebike.cart.png":     { kind: ["game"], genre: "racing",     homage: "Excitebike (1984)" },
  "advancewars.cart.png":    { kind: ["game"], genre: "strategy",   homage: "Advance Wars (2001)" },
  "masseffect.cart.png":     { kind: ["game"], genre: "rpg",        homage: "Mass Effect (2007)" },
  "mariopaint.cart.png":     { kind: ["tool", "instrument"], homage: "Mario Paint (1992)" },
  "hotline.cart.png":        { kind: ["game"], genre: "shooter",    homage: "Hotline Miami (2012)" },
  "dungeonkeeper.cart.png":  { kind: ["game"], genre: "strategy",   homage: "Dungeon Keeper (1997)" },
  "dpaint.cart.png":         { kind: ["tool"], homage: "Deluxe Paint (1985)" },
  "heroes.cart.png":         { kind: ["game"], genre: "strategy",   homage: "Heroes of Might and Magic (1995)" },
  "worldpointer.cart.png":   { kind: ["tech-demo"] },
  "skystrike.cart.png":      { kind: ["game"], genre: "shooter",    homage: "Raiden (1990)" },
  "pinball.cart.png":        { kind: ["game"], genre: "tabletop" },
  "smooch.cart.png":         { kind: ["game"], genre: "arcade" },
  "bones.cart.png":          { kind: ["tool"] },
  "arcs.cart.png":           { kind: ["tech-demo"] },
  "flyover.cart.png":        { kind: ["tech-demo", "toy"] },
  "soccermgr.cart.png":      { kind: ["game"], genre: "sports",     homage: "Football Manager (1982)" },
  "infiniminer.cart.png":    { kind: ["game", "tech-demo"], genre: "sandbox", homage: "Infiniminer (2009)" },
  "jumpstar.cart.png":       { kind: ["game"], genre: "platformer", homage: "Doodle Jump (2009)" },
  "dwarffort.cart.png":      { kind: ["game"], genre: "simulation", homage: "Dwarf Fortress (2006)" },
  "civ.cart.png":            { kind: ["game"], genre: "strategy",   homage: "Civilization (1991)" },
  "strippoker.cart.png":     { kind: ["game"], genre: "tabletop" },
  "zak.cart.png":            { kind: ["game"], genre: "adventure",  homage: "Zak McKracken (1988)" },
  "wintergames.cart.png":    { kind: ["game"], genre: "sports",     homage: "Winter Games (1985)" },
  "summergames.cart.png":    { kind: ["game"], genre: "sports",     homage: "Summer Games (1984)" },
  "calgames.cart.png":       { kind: ["game"], genre: "sports",     homage: "California Games (1987)" },
  "transport.cart.png":      { kind: ["game"], genre: "simulation", homage: "Transport Tycoon (1994)" },
  "incmachine.cart.png":     { kind: ["game"], genre: "puzzle",     homage: "The Incredible Machine (1993)" },
  "lemmings.cart.png":       { kind: ["game"], genre: "puzzle",     homage: "Lemmings (1991)" },
  "larry.cart.png":          { kind: ["game"], genre: "adventure",  homage: "Leisure Suit Larry (1987)" },
  "monkey.cart.png":         { kind: ["game"], genre: "adventure",  homage: "The Secret of Monkey Island (1990)" },
  "worms.cart.png":          { kind: ["game"], genre: "strategy",   homage: "Worms (1995)" },
  "chess.cart.png":          { kind: ["game"], genre: "tabletop" },
  "othello.cart.png":        { kind: ["game"], genre: "tabletop" },
  "connect4.cart.png":       { kind: ["game"], genre: "tabletop" },
  "battleship.cart.png":     { kind: ["game"], genre: "tabletop" },
  "bejeweled.cart.png":      { kind: ["game"], genre: "puzzle",     homage: "Bejeweled (2001)" },
  "drmario.cart.png":        { kind: ["game"], genre: "puzzle",     homage: "Dr. Mario (1990)" },
  "puyo.cart.png":           { kind: ["game"], genre: "puzzle",     homage: "Puyo Puyo (1991)" },
  "columns.cart.png":        { kind: ["game"], genre: "puzzle",     homage: "Columns (1990)" },
  "solitaire.cart.png":      { kind: ["game"], genre: "tabletop" },
  "blackjack.cart.png":      { kind: ["game"], genre: "tabletop" },
  "wordle.cart.png":         { kind: ["game"], genre: "puzzle",     homage: "Wordle (2021)" },
  "hangman.cart.png":        { kind: ["game"], genre: "puzzle" },
  "boggle.cart.png":         { kind: ["game"], genre: "puzzle" },
  "minesweeper.cart.png":    { kind: ["game"], genre: "puzzle",     homage: "Minesweeper (1990)" },
  "missilecmd.cart.png":     { kind: ["game"], genre: "shooter",    homage: "Missile Command (1980)" },
  "centipede.cart.png":      { kind: ["game"], genre: "shooter",    homage: "Centipede (1981)" },
  "defender.cart.png":       { kind: ["game"], genre: "shooter",    homage: "Defender (1981)" },
  "digdug.cart.png":         { kind: ["game"], genre: "arcade",     homage: "Dig Dug (1982)" },
  "boulderdash.cart.png":    { kind: ["game"], genre: "arcade",     homage: "Boulder Dash (1984)" },
  "loderunner.cart.png":     { kind: ["game"], genre: "platformer", homage: "Lode Runner (1983)" },
  "donkeykong.cart.png":     { kind: ["game"], genre: "platformer", homage: "Donkey Kong (1981)" },
  "qbert.cart.png":          { kind: ["game"], genre: "arcade",     homage: "Q*bert (1982)" },
  "marble.cart.png":         { kind: ["game"], genre: "arcade",     homage: "Marble Madness (1984)" },
  "pool.cart.png":           { kind: ["game"], genre: "sports" },
  "streetfighter.cart.png":  { kind: ["game"], genre: "fighting",   homage: "Street Fighter II (1991)" },
  "deckbuilder.cart.png":    { kind: ["game"], genre: "rpg",        homage: "Slay the Spire (2017)" },
  "farm.cart.png":           { kind: ["game"], genre: "simulation", homage: "Harvest Moon (1996)" },
  "beatcrypt.cart.png":      { kind: ["game"], genre: "rpg",        homage: "Crypt of the NecroDancer (2015)" },
  "rollswarm.cart.png":      { kind: ["game"], genre: "sandbox" },
  "sandburrow.cart.png":     { kind: ["game"], genre: "arcade" },
  "swarmturf.cart.png":      { kind: ["game"], genre: "sandbox" },
  "merchant.cart.png":       { kind: ["game"], genre: "simulation", homage: "Taipan! (1982)" },
  "wildfire.cart.png":       { kind: ["game"], genre: "arcade" },
  "bloom.cart.png":          { kind: ["toy", "tech-demo"] },
  "shapes.cart.png":         { kind: ["tech-demo"] },
  "fonts.cart.png":          { kind: ["tech-demo"] },
  "ragdoll.cart.png":        { kind: ["tech-demo"] },
  "dreamcad.cart.png":       { kind: ["tool"], homage: "picoCAD (2020)" },
  "physics.cart.png":        { kind: ["tech-demo"] },
  "dinorun.cart.png":        { kind: ["game"], genre: "platformer", homage: "Chrome Dino (2014)" },
  "mazegen.cart.png":        { kind: ["tech-demo"] },
  "raster_test.cart.png":    { kind: ["tech-demo"] },
};

// ---- validate ----
const errors = [];
for (const [file, t] of Object.entries(TAGS)) {
  if (!Array.isArray(t.kind) || t.kind.length < 1 || t.kind.length > 2)
    errors.push(`${file}: kind must be an array of 1-2`);
  for (const k of t.kind || []) if (!KINDS.includes(k)) errors.push(`${file}: bad kind '${k}'`);
  const isGame = (t.kind || []).includes("game");
  if (isGame && !t.genre) errors.push(`${file}: game needs a genre`);
  if (!isGame && t.genre) errors.push(`${file}: genre '${t.genre}' on non-game`);
  if (t.genre && !GENRES.includes(t.genre)) errors.push(`${file}: bad genre '${t.genre}'`);
}

const idxPath = path.join(__dirname, "..", "editor", "public", "carts", "index.json");
const index = JSON.parse(fs.readFileSync(idxPath, "utf8"));
const idxFiles = new Set(index.map(e => e.file));
const tagFiles = new Set(Object.keys(TAGS));
for (const f of idxFiles) if (!tagFiles.has(f)) errors.push(`index has '${f}' but TAGS does not`);
for (const f of tagFiles) if (!idxFiles.has(f)) errors.push(`TAGS has '${f}' but index does not`);

if (errors.length) { console.error("VALIDATION FAILED:\n" + errors.join("\n")); process.exit(1); }

// ---- merge (preserve key order: title, description, file, kind, genre, homage) ----
const merged = index.map(e => {
  const t = TAGS[e.file];
  const out = { title: e.title, description: e.description, file: e.file, kind: t.kind };
  if (t.genre)  out.genre  = t.genre;
  if (t.homage) out.homage = t.homage;
  return out;
});
fs.writeFileSync(idxPath, JSON.stringify(merged, null, 2) + "\n");
console.log(`OK — tagged ${merged.length} carts.`);
