#!/usr/bin/env node
// fml-sprites.js — embed baked furniture sprites (build/.fml-assets/manifest.json)
// into floorwalker.c, keyed to the cart's lv_refs[] order.
//
//   node fmltools/fml-sprites.js [--manifest build/.fml-assets/manifest.json]
//                             [--out tools/carts/floorwalker.c]
//
// Reads the lv_refs[] array already in the cart (written by fml2cart.js), looks up
// each refid's baked sprite, and splices a sprite-data block between the sentinels
//   /* >>>FML_SPRITES */ ... /* <<<FML_SPRITES */
// Emits: lv_spr[] = {w,h,off} per refid (w=0 if no sprite) + lv_pool[] palette
// indices (255 = transparent). Run after fml2cart.js and the bake.

const fs = require('fs');
const path = require('path');

const argv = process.argv.slice(2);
const opt = { manifest: 'build/.fml-assets/manifest.json', out: 'tools/carts/floorwalker.c', json: null };
for (let i = 0; i < argv.length; i++) {
  if (argv[i] === '--manifest') opt.manifest = argv[++i];
  else if (argv[i] === '--out') opt.out = argv[++i];
  else if (argv[i] === '--json') opt.json = argv[++i];   // fill sprites[] in a fml2cart --json data file (instead of splicing C)
  else { console.error('unknown arg', argv[i]); process.exit(1); }
}

const manifest = JSON.parse(fs.readFileSync(opt.manifest, 'utf8'));

// --json mode: write the baked sprites into a runtime data file's sprites[] (aligned
// to its refs[]), so the dynamic `floorplan` cart can blit them. Mirrors the C path's
// pool building exactly (255 = transparent), just JSON instead of a spliced array.
if (opt.json) {
  const dpath = path.resolve(opt.json);
  const data = JSON.parse(fs.readFileSync(dpath, 'utf8'));
  let withSprite = 0, px = 0;
  data.sprites = (data.refs || []).map((refid) => {
    const it = manifest.items[refid];
    if (!it || it.error || !it.w) return { w: 0, h: 0, px: [] };
    withSprite++; px += it.idx.length;
    return { w: it.w, h: it.h, px: it.idx.map(v => (v < 0 || v > 31 ? 255 : v)) };
  });
  fs.writeFileSync(dpath, JSON.stringify(data));
  console.log(`fml-sprites: ${withSprite}/${(data.refs || []).length} refids have sprites, ${px} px (${(px / 1024).toFixed(0)}KB)\n  -> wrote ${opt.json}`);
  process.exit(0);
}
const cartPath = path.resolve(opt.out);
let src = fs.readFileSync(cartPath, 'utf8');

// extract lv_refs[] (the refid order furniture indexes into)
const m = src.match(/static const char\* lv_refs\[\] = \{([^}]*)\}/);
if (!m) { console.error('lv_refs[] not found in', opt.out, '— run fml2cart.js first'); process.exit(1); }
const refs = m[1].trim() ? m[1].split(',').map(s => s.replace(/[?"\s]/g, '')) : [];

// build pool + per-ref sprite records in refs order
const pool = [];
const spr = [];
let withSprite = 0;
for (const refid of refs) {
  const it = manifest.items[refid];
  if (!it || it.error || !it.w) { spr.push({ w: 0, h: 0, off: 0 }); continue; }
  const off = pool.length;
  for (const v of it.idx) pool.push(v < 0 || v > 31 ? 255 : v); // -1/out-of-range -> transparent sentinel
  spr.push({ w: it.w, h: it.h, off });
  withSprite++;
}

let c = '';
c += `/* >>>FML_SPRITES   generated by fmltools/fml-sprites.js — ${withSprite}/${refs.length} refids have a baked sprite */\n`;
c += `typedef struct { short w, h; int off; } Spr;\n`;
c += `static const Spr lv_spr[] = {${spr.length ? spr.map(s => `{${s.w},${s.h},${s.off}}`).join(',') : '{0,0,0}'}};\n`;
c += `static const unsigned char lv_pool[] = {${pool.length ? pool.join(',') : '0'}};\n`;
c += `/* <<<FML_SPRITES */`;

const re = /\/\* >>>FML_SPRITES[\s\S]*?<<<FML_SPRITES \*\//;
if (!re.test(src)) { console.error('no FML_SPRITES sentinels in', opt.out); process.exit(1); }
src = src.replace(re, c);
fs.writeFileSync(cartPath, src);
console.log(`fml-sprites: ${withSprite}/${refs.length} refids have sprites, pool ${pool.length} px (${(pool.length/1024).toFixed(0)}KB)\n  -> spliced into ${opt.out}`);
